package app.inkflow.reader;

import android.app.*;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.*;
import android.widget.*;

public class BookSettingsActivity extends Activity {
    private BookProgressStore store;
    @Override protected void onCreate(Bundle b){super.onCreate(b);store=new BookProgressStore(this);getWindow().setStatusBarColor(Ui.BG);getWindow().setNavigationBarColor(Ui.BG);build();}
    private void build(){
        ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(Ui.dp(this,18),Ui.dp(this,14),Ui.dp(this,18),Ui.dp(this,26));box.setBackgroundColor(Ui.BG);Ui.safeInsets(box,this,0,0,0,0);sc.addView(box);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=btn("‹",true,32);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));TextView h=Ui.text(this,"Настройки читалки",22,Ui.TEXT);h.setTypeface(Typeface.DEFAULT_BOLD);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(0,-2,1);hp.leftMargin=Ui.dp(this,10);head.addView(h,hp);box.addView(head);
        TextView sub=Ui.text(this,"Эти параметры используются по умолчанию во всех книгах. В самой книге их можно менять тем же образом.",12,Ui.MUTED);add(box,sub,8);
        section(box,"ЧТЕНИЕ"); cycle(box,"Режим по умолчанию",new String[]{"КНИГА","ЛЕНТА"},store.getMode(),v->store.setMode(v)); cycle(box,"Перелистывание",new String[]{"КНИГА 3D","СЛАЙД","ЗАТУХАНИЕ","БЕЗ"},store.getAnimation(),v->store.setAnimation(v)); seek(box,"Скорость",160,700,store.getTurnMs(),v->store.setTurnMs(v)," мс"); sw(box,"Две страницы в альбомной",store.getTwoPage(),v->store.setTwoPage(v));sw(box,"Тап-зоны",store.getTapZones(),v->store.setTapZones(v));sw(box,"Кнопки громкости листают",store.getVolumeKeys(),v->store.setVolumeKeys(v));
        section(box,"ТЕКСТ");seek(box,"Размер шрифта",14,36,store.getFontSp(),v->store.setFontSp(v)," sp");seek(box,"Межстрочный интервал",120,210,store.getLinePct(),v->store.setLinePct(v),"%");seek(box,"Поля",6,42,store.getMargins(),v->store.setMargins(v)," px");seek(box,"Абзац",0,42,store.getIndent(),v->store.setIndent(v)," px");cycle(box,"Шрифт",new String[]{"КНИЖНЫЙ","БЕЗ ЗАСЕЧЕК","МОНО"},store.getFontFamily(),v->store.setFontFamily(v));sw(box,"Выравнивание по ширине",store.getJustify(),v->store.setJustify(v));
        section(box,"ЭКРАН");cycle(box,"Тема",new String[]{"СЕПИЯ","НОЧЬ","ДЕНЬ","ЧЁРНЫЙ"},store.getTheme(),v->store.setTheme(v));seek(box,"Яркость (0 = системная)",0,100,store.getBrightness(),v->store.setBrightness(v),"%");cycle(box,"Ориентация",new String[]{"АВТО","ПОРТРЕТ","АЛЬБОМ"},store.getOrientation(),v->store.setOrientation(v));sw(box,"Не выключать экран",store.getKeepScreen(),v->store.setKeepScreen(v));
        TextView reset=btn("СБРОСИТЬ НАСТРОЙКИ",false,12);reset.setOnClickListener(v->{store.resetReaderSettings();build();});add(box,reset,20);setContentView(sc);
    }
    private interface I{void set(int v);}private interface B{void set(boolean v);} private TextView btn(String s,boolean gold,float sz){TextView t=Ui.text(this,s,sz,gold?0xFF201400:Ui.TEXT);t.setGravity(Gravity.CENTER);t.setTypeface(Typeface.DEFAULT_BOLD);t.setBackground(gold?Ui.goldButton(this):Ui.softButton(this));return t;}
    private void section(LinearLayout b,String s){TextView t=Ui.text(this,s,11,Ui.GOLD);t.setTypeface(Typeface.DEFAULT_BOLD);add(b,t,18);}private void add(LinearLayout b,View v,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,v instanceof TextView&&((TextView)v).getText().toString().startsWith("СБРОС")?Ui.dp(this,48):-2);p.topMargin=Ui.dp(this,top);b.addView(v,p);}
    private void cycle(LinearLayout b,String title,String[] vals,int current,I cb){LinearLayout c=new LinearLayout(this);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(Ui.dp(this,12),Ui.dp(this,9),Ui.dp(this,12),Ui.dp(this,9));c.setBackground(Ui.panel(this));TextView a=Ui.text(this,title,14,Ui.TEXT);a.setTypeface(Typeface.DEFAULT_BOLD);c.addView(a,new LinearLayout.LayoutParams(0,-2,1));final int[] ix={current};TextView v=btn(vals[ix[0]],true,10);v.setOnClickListener(x->{ix[0]=(ix[0]+1)%vals.length;v.setText(vals[ix[0]]);cb.set(ix[0]);});c.addView(v,new LinearLayout.LayoutParams(Ui.dp(this,118),Ui.dp(this,38)));add(b,c,7);}
    private void sw(LinearLayout b,String title,boolean checked,B cb){Switch s=new Switch(this);s.setText(title);s.setTextColor(Ui.TEXT);s.setTextSize(14);s.setChecked(checked);s.setPadding(Ui.dp(this,12),Ui.dp(this,5),Ui.dp(this,12),Ui.dp(this,5));s.setBackground(Ui.panel(this));s.setOnCheckedChangeListener((x,v)->cb.set(v));add(b,s,7);}
    private void seek(LinearLayout b,String title,int min,int max,int val,I cb,String suffix){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(Ui.dp(this,12),Ui.dp(this,8),Ui.dp(this,12),Ui.dp(this,8));c.setBackground(Ui.panel(this));LinearLayout r=new LinearLayout(this);TextView a=Ui.text(this,title,14,Ui.TEXT);a.setTypeface(Typeface.DEFAULT_BOLD);r.addView(a,new LinearLayout.LayoutParams(0,-2,1));TextView vv=Ui.text(this,val+suffix,12,Ui.GOLD);r.addView(vv);c.addView(r);SeekBar s=new SeekBar(this);s.setMax(max-min);s.setProgress(val-min);s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){int x=val;public void onProgressChanged(SeekBar q,int p,boolean f){x=min+p;vv.setText(x+suffix);}public void onStartTrackingTouch(SeekBar q){}public void onStopTrackingTouch(SeekBar q){cb.set(x);}});c.addView(s);add(b,c,7);}
}
