const fs=require('fs'),vm=require('vm'),assert=require('assert');
function boot(saved={}){
 const nodes=new Map(),events={};const node=()=>({classList:{add(){},remove(){},toggle(){}},style:{},setAttribute(){},addEventListener(){},textContent:'',innerHTML:'',disabled:false,querySelector:()=>node()});
 const ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});nodes.set('#world',{...node(),getContext:()=>ctx});
 const window={Assets:{ready:true,images:new Proxy({}, {get:()=>({width:1536,height:1536})}),load:()=>Promise.resolve()}};
 const s={localStorageData:saved,console,Math,innerWidth:1280,innerHeight:720,devicePixelRatio:1,performance:{now:()=>0},localStorage:{getItem:k=>saved[k]||null,setItem:(k,v)=>saved[k]=v,removeItem:k=>delete saved[k]},document:{createElement:()=>({...node(),getContext:()=>ctx}),querySelector:k=>{if(!nodes.has(k))nodes.set(k,node());return nodes.get(k)},querySelectorAll:()=>[],body:node(),addEventListener(){}},window,addEventListener:(k,fn)=>events[k]=fn,requestAnimationFrame:fn=>s.frame=fn};vm.createContext(s);for(let f of ['progression.js','game.js'])vm.runInContext(fs.readFileSync('app/src/main/assets/'+f,'utf8'),s);return {g:window.__game,events,s,nodes};
}
let {g,events,s,nodes}=boot();assert.equal(g.state,'menu');g.reset();assert.equal(g.state,'play');assert.equal(typeof g.p.energy,'number','actor must have energy');
function step(n){for(let i=0;i<n;i++){g.update(1/60);for(let k of Object.keys(g.pressed))delete g.pressed[k]}}
g.keys.d=true;step(60);g.keys.d=false;assert(g.p.x>350);g.p.x=200;g.p.y=565;g.p.vy=0;g.p.ground=true;g.p.jumps=0;g.pressed[' ']=true;step(1);assert.equal(g.p.jumps,1);g.pressed[' ']=true;step(1);assert.equal(g.p.jumps,2);g.pressed[' ']=true;step(1);assert.equal(g.p.jumps,2);
g.reset();let e=g.enemies[0];g.p.x=e.x-50;g.p.face=1;let old=e.hp;g.pressed.j=true;step(1);assert.equal(e.hp,old,'damage must wait for animation hit frame');step(10);assert(e.hp<old);let first=e.hp;step(9);assert.equal(e.hp,first,'one attack must not hit enemy twice');
g.damageEnemy(e,10000,'test');assert.equal(g.kills,1);assert.equal(g.corpses.length,1);g.p.hp=20;g.p.energy=5;g.p.x=e.x;g.p.y=e.y;g.p.vy=0;g.p.ground=true;g.p.attack=0;g.p.attackCd=0;g.p.special=0;g.p.inv=0;g.pressed.e=true;step(1);assert(g.p.eating>0);g.hurt(5);assert.equal(g.p.eating,0,'incoming damage interrupts feeding');g.p.hp=20;g.p.energy=5;g.p.inv=10;g.pressed.e=true;step(1);step(100);assert(g.p.hp>=55);assert(g.p.energy>=50);assert(g.corpses[0].eaten);let hp=g.p.hp;g.pressed.e=true;step(100);assert.equal(g.p.hp,hp,'corpse cannot heal twice');
g.p.energy=10;g.p.special=0;g.p.specialCd=0;assert(!g.special('bolt'));assert.equal(g.p.energy,10);g.p.energy=100;assert(g.special('bolt'));assert.equal(g.p.energy,75);assert(!g.special('slam'),'animation must block concurrent specials');step(100);g.p.ground=true;g.p.energy=100;assert(g.special('slam'));assert.equal(g.p.energy,65);
g.p.dashCd=0;g.p.special=0;g.pressed.k=true;step(1);assert(g.p.dash>0);assert(g.p.dashCd>0);g.p.x=940;g.p.y=900;g.p.inv=0;g.p.dash=0;g.p.special=0;step(1);assert.equal(g.p.x,150);
events.keydown({key:'Escape',preventDefault(){}});assert.equal(g.state,'paused');let x=g.p.x;g.keys.d=true;step(60);assert.equal(g.p.x,x);nodes.get('#resume').onclick();assert.equal(g.state,'play');assert(!g.keys.d,'resume must clear held inputs');
g.profile.inventory.life=1;g.p.hp=1;assert(g.useItem('life'));assert.equal(g.p.hp,51);assert(!g.useItem('life'));g.profile.points=1;g.openPanel('mutations');assert.equal(g.state,'panel');assert(g.buyUpgrade('vitality'));assert.equal(g.stats().hp,120);g.togglePause();assert.equal(g.state,'play');
g.p.x=200;g.p.y=565;g.p.hp=51;g.saveRun();let b=boot(s.localStorageData);b.g.continueRun();assert.equal(b.g.state,'play');assert.equal(b.g.p.hp,51);assert.equal(b.g.profile.upgrades.vitality,1);s.frame(16);s.frame(32);console.log('PASS: movement, double jump, hit frames, one hit per swing, corpse, interrupted feeding, one-time healing/energy, special costs and lock, dash, fall, pause input, item consumption, upgrade, offline continuation, render');
// Opening menu panels must not replace an existing raid snapshot.
const preserved=s.localStorageData['deadlight-run-v2'];let menu=boot(s.localStorageData);menu.g.openPanel('inventory');assert.equal(s.localStorageData['deadlight-run-v2'],preserved,'menu inventory overwrote saved raid');menu.g.p.hp=1;menu.g.profile.inventory.life=2;assert(!menu.g.useItem('life'));assert.equal(menu.g.profile.inventory.life,2);menu.g.togglePause();assert.equal(menu.g.state,'menu');assert.equal(s.localStorageData['deadlight-run-v2'],preserved);
for(let mutate of [r=>r.loot={},r=>r.enemies[0]=null,r=>r.corpses=[null]]){const data={...s.localStorageData};let r=JSON.parse(preserved);mutate(r);data['deadlight-run-v2']=JSON.stringify(r);const runtime=boot(data);assert.doesNotThrow(()=>runtime.g.continueRun());assert.equal(runtime.g.state,'play')}
// Killing while high in a double jump can save a valid aerial position.
g.reset();g.p.y=180;g.p.x=500;g.saveRun();let aerial=boot(s.localStorageData);aerial.g.continueRun();assert.equal(aerial.g.p.x,500);assert.equal(aerial.g.p.y,180);console.log('PASS: menu panel preserves raid, nested corrupt run recovery, aerial save reload');
