package ru.vibecut.editor

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

object ProjectStore {
    private const val PREFS = "vibecut_projects_v1"
    private const val INDEX_KEY = "project_index"
    private const val MIGRATED_KEY = "legacy_migrated"
    private const val PROJECT_PREFIX = "project_"
    private const val LEGACY_PREFS = "vibecut_project"
    private const val LEGACY_KEY = "autosave"

    fun create(context: Context, name: String = "Новый проект"): SavedProject {
        ensureMigrated(context)
        val now=System.currentTimeMillis()
        return SavedProject(id=UUID.randomUUID().toString(),name=name.trim().ifBlank{"Новый проект"},createdAt=now,updatedAt=now).also{saveInternal(context,it)}
    }
    fun save(context:Context,project:SavedProject){ensureMigrated(context);saveInternal(context,project.copy(updatedAt=System.currentTimeMillis()))}
    fun load(context:Context,id:String):SavedProject?{ensureMigrated(context);return loadWithoutMigration(context,id)}
    fun list(context:Context):List<ProjectSummary>{ensureMigrated(context);return readIndex(context).mapNotNull{id->loadWithoutMigration(context,id)?.let{p->ProjectSummary(p.id,p.name,p.updatedAt,p.clips.size,p.clips.sumOf{it.durationMs})}}.sortedByDescending{it.updatedAt}}
    fun delete(context:Context,id:String){ensureMigrated(context);prefs(context).edit().remove(PROJECT_PREFIX+id).apply();writeIndex(context,readIndex(context).filterNot{it==id})}
    fun duplicate(context:Context,id:String):SavedProject?{val source=load(context,id)?:return null;val now=System.currentTimeMillis();return source.copy(id=UUID.randomUUID().toString(),name="${source.name} · копия",createdAt=now,updatedAt=now).also{saveInternal(context,it)}}

    private fun prefs(context:Context)=context.getSharedPreferences(PREFS,Context.MODE_PRIVATE)
    private fun saveInternal(context:Context,project:SavedProject){prefs(context).edit().putString(PROJECT_PREFIX+project.id,projectToJson(project).toString()).apply();val ids=readIndex(context).toMutableList();if(project.id !in ids){ids+=project.id;writeIndex(context,ids)}}
    private fun loadWithoutMigration(context:Context,id:String):SavedProject?{val raw=prefs(context).getString(PROJECT_PREFIX+id,null)?:return null;return runCatching{projectFromJson(JSONObject(raw),id)}.getOrNull()}
    private fun readIndex(context:Context):List<String>{val raw=prefs(context).getString(INDEX_KEY,"[]")?:"[]";return runCatching{val a=JSONArray(raw);buildList{for(i in 0 until a.length())a.optString(i).takeIf{it.isNotBlank()}?.let(::add)}}.getOrDefault(emptyList())}
    private fun writeIndex(context:Context,ids:List<String>){val a=JSONArray();ids.distinct().forEach(a::put);prefs(context).edit().putString(INDEX_KEY,a.toString()).apply()}
    private fun ensureMigrated(context:Context){val p=prefs(context);if(p.getBoolean(MIGRATED_KEY,false))return;p.edit().putBoolean(MIGRATED_KEY,true).apply();if(readIndex(context).isNotEmpty())return;val raw=context.getSharedPreferences(LEGACY_PREFS,Context.MODE_PRIVATE).getString(LEGACY_KEY,null)?:return;val id=UUID.randomUUID().toString();runCatching{projectFromJson(JSONObject(raw),id).copy(id=id,name="Восстановленный проект")}.getOrNull()?.let{saveInternal(context,it)}}

    private fun projectToJson(p:SavedProject)=JSONObject().apply{
        put("id",p.id);put("name",p.name);put("createdAt",p.createdAt);put("updatedAt",p.updatedAt);put("selectedId",p.selectedId)
        put("clips",JSONArray().apply{p.clips.forEach{put(clipToJson(it))}})
        put("backgroundAudio",p.backgroundAudio?.let(::audioToJson));put("positionedAudioTracks",JSONArray().apply{p.positionedAudioTracks.forEach{put(positionedAudioToJson(it))}})
        put("subtitles",JSONArray().apply{p.subtitles.forEach{put(subtitleToJson(it))}});put("subtitleStyle",subtitleStyleToJson(p.subtitleStyle));put("export",exportToJson(p.exportSettings))
    }
    private fun projectFromJson(j:JSONObject,fallbackId:String):SavedProject{
        fun <T> arr(name:String,parser:(JSONObject)->T):List<T>{val a=j.optJSONArray(name)?:JSONArray();return buildList{for(i in 0 until a.length())a.optJSONObject(i)?.let{add(parser(it))}}}
        return SavedProject(id=j.optString("id",fallbackId).ifBlank{fallbackId},name=j.optString("name","Новый проект").ifBlank{"Новый проект"},createdAt=j.optLong("createdAt",System.currentTimeMillis()),updatedAt=j.optLong("updatedAt",System.currentTimeMillis()),clips=arr("clips",::clipFromJson),selectedId=j.optString("selectedId").takeIf{it.isNotBlank()&&it!="null"},backgroundAudio=j.optJSONObject("backgroundAudio")?.let(::audioFromJson),positionedAudioTracks=arr("positionedAudioTracks",::positionedAudioFromJson),subtitles=arr("subtitles",::subtitleFromJson),subtitleStyle=j.optJSONObject("subtitleStyle")?.let(::subtitleStyleFromJson)?:SubtitleStyle(),exportSettings=j.optJSONObject("export")?.let(::exportFromJson)?:ExportSettings())
    }

    private fun clipToJson(c:VideoClip)=JSONObject().apply{
        put("id",c.id);put("uri",c.uri);put("name",c.name);put("sourceDurationMs",c.sourceDurationMs);put("trimStartMs",c.trimStartMs);put("trimEndMs",c.trimEndMs);put("muted",c.muted);put("audioVolume",c.audioVolume.toDouble());put("audioFadeInMs",c.audioFadeInMs);put("audioFadeOutMs",c.audioFadeOutMs);put("rotationDegrees",c.rotationDegrees);put("speed",c.speed.toDouble());put("brightness",c.brightness.toDouble());put("contrast",c.contrast.toDouble());put("saturation",c.saturation.toDouble());put("hue",c.hue.toDouble());put("lightness",c.lightness.toDouble());put("crop",c.crop.toDouble());put("flipHorizontal",c.flipHorizontal);put("flipVertical",c.flipVertical);put("motion",c.motion.name);put("motionStrength",c.motionStrength.toDouble());put("colorEffect",c.colorEffect.name);put("redScale",c.redScale.toDouble());put("greenScale",c.greenScale.toDouble());put("blueScale",c.blueScale.toDouble());put("maskType",c.maskType.name);put("maskSize",c.maskSize.toDouble());put("vignette",c.vignette.toDouble());put("transitionOut",c.transitionOut.name);put("transitionDurationMs",c.transitionDurationMs)
        put("keyframes",JSONArray().apply{c.keyframes.forEach{put(keyframeToJson(it))}});put("stickers",JSONArray().apply{c.stickers.forEach{put(stickerToJson(it))}});put("animatedStickers",JSONArray().apply{c.animatedStickers.forEach{put(animatedStickerToJson(it))}})
        put("overlayText",c.overlayText);put("textX",c.textX.toDouble());put("textY",c.textY.toDouble());put("textScale",c.textScale.toDouble());put("textRotation",c.textRotation.toDouble());put("textColor",c.textColor);put("textBackground",c.textBackground);put("textBold",c.textBold);put("textItalic",c.textItalic)
    }
    private fun clipFromJson(j:JSONObject):VideoClip{
        fun <T> arr(name:String,parser:(JSONObject)->T):List<T>{val a=j.optJSONArray(name)?:JSONArray();return buildList{for(i in 0 until a.length())a.optJSONObject(i)?.let{add(parser(it))}}}
        val source=j.optLong("sourceDurationMs",1L).coerceAtLeast(1L)
        return VideoClip(id=j.optString("id",UUID.randomUUID().toString()),uri=j.getString("uri"),name=j.optString("name","Видео"),sourceDurationMs=source,trimStartMs=j.optLong("trimStartMs",0L),trimEndMs=j.optLong("trimEndMs",source),muted=j.optBoolean("muted",false),audioVolume=j.optDouble("audioVolume",1.0).toFloat(),audioFadeInMs=j.optLong("audioFadeInMs",0L),audioFadeOutMs=j.optLong("audioFadeOutMs",0L),rotationDegrees=j.optInt("rotationDegrees",0),speed=j.optDouble("speed",1.0).toFloat(),brightness=j.optDouble("brightness",0.0).toFloat(),contrast=j.optDouble("contrast",0.0).toFloat(),saturation=j.optDouble("saturation",0.0).toFloat(),hue=j.optDouble("hue",0.0).toFloat(),lightness=j.optDouble("lightness",0.0).toFloat(),crop=j.optDouble("crop",0.0).toFloat(),flipHorizontal=j.optBoolean("flipHorizontal",false),flipVertical=j.optBoolean("flipVertical",false),motion=enumOrDefault(j.optString("motion"),ClipMotion.NONE),motionStrength=j.optDouble("motionStrength",0.14).toFloat(),colorEffect=enumOrDefault(j.optString("colorEffect"),ColorEffect.NONE),redScale=j.optDouble("redScale",1.0).toFloat(),greenScale=j.optDouble("greenScale",1.0).toFloat(),blueScale=j.optDouble("blueScale",1.0).toFloat(),maskType=enumOrDefault(j.optString("maskType"),MaskType.NONE),maskSize=j.optDouble("maskSize",0.82).toFloat(),vignette=j.optDouble("vignette",0.0).toFloat(),transitionOut=enumOrDefault(j.optString("transitionOut"),TransitionType.NONE),transitionDurationMs=j.optLong("transitionDurationMs",650L),keyframes=arr("keyframes",::keyframeFromJson),stickers=arr("stickers",::stickerFromJson),animatedStickers=arr("animatedStickers",::animatedStickerFromJson),overlayText=j.optString("overlayText",""),textX=j.optDouble("textX",0.0).toFloat(),textY=j.optDouble("textY",-0.72).toFloat(),textScale=j.optDouble("textScale",0.72).toFloat(),textRotation=j.optDouble("textRotation",0.0).toFloat(),textColor=j.optInt("textColor",-1),textBackground=j.optBoolean("textBackground",true),textBold=j.optBoolean("textBold",true),textItalic=j.optBoolean("textItalic",false))
    }

    private fun keyframeToJson(k:TransformKeyframe)=JSONObject().apply{put("id",k.id);put("timeMs",k.timeMs);put("x",k.x.toDouble());put("y",k.y.toDouble());put("scale",k.scale.toDouble());put("rotation",k.rotation.toDouble());put("easing",k.easing.name)}
    private fun keyframeFromJson(j:JSONObject)=TransformKeyframe(id=j.optString("id",UUID.randomUUID().toString()),timeMs=j.optLong("timeMs",0L),x=j.optDouble("x",0.0).toFloat(),y=j.optDouble("y",0.0).toFloat(),scale=j.optDouble("scale",1.0).toFloat(),rotation=j.optDouble("rotation",0.0).toFloat(),easing=enumOrDefault(j.optString("easing"),KeyframeEasing.EASE_IN_OUT))
    private fun trackingToJson(t:TrackingPoint)=JSONObject().apply{put("timeMs",t.timeMs);put("x",t.x.toDouble());put("y",t.y.toDouble());put("objectScale",t.objectScale.toDouble())}
    private fun trackingFromJson(j:JSONObject)=TrackingPoint(j.optLong("timeMs",0L),j.optDouble("x",0.0).toFloat(),j.optDouble("y",0.0).toFloat(),j.optDouble("objectScale",1.0).toFloat())

    private fun stickerToJson(s:StickerLayer)=JSONObject().apply{put("id",s.id);put("uri",s.uri);put("name",s.name);put("x",s.x.toDouble());put("y",s.y.toDouble());put("scale",s.scale.toDouble());put("rotation",s.rotation.toDouble());put("alpha",s.alpha.toDouble());put("startMs",s.startMs);put("endMs",s.endMs);put("keyframes",JSONArray().apply{s.keyframes.forEach{put(keyframeToJson(it))}});put("trackingPath",JSONArray().apply{s.trackingPath.forEach{put(trackingToJson(it))}})}
    private fun stickerFromJson(j:JSONObject):StickerLayer{fun <T> arr(name:String,p:(JSONObject)->T):List<T>{val a=j.optJSONArray(name)?:JSONArray();return buildList{for(i in 0 until a.length())a.optJSONObject(i)?.let{add(p(it))}}};return StickerLayer(id=j.optString("id",UUID.randomUUID().toString()),uri=j.getString("uri"),name=j.optString("name","Изображение"),x=j.optDouble("x",0.0).toFloat(),y=j.optDouble("y",0.0).toFloat(),scale=j.optDouble("scale",0.35).toFloat(),rotation=j.optDouble("rotation",0.0).toFloat(),alpha=j.optDouble("alpha",1.0).toFloat(),startMs=j.optLong("startMs",0L),endMs=j.optLong("endMs",Long.MAX_VALUE),keyframes=arr("keyframes",::keyframeFromJson),trackingPath=arr("trackingPath",::trackingFromJson))}
    private fun animatedStickerToJson(s:AnimatedStickerLayer)=JSONObject().apply{put("id",s.id);put("kind",s.kind.name);put("x",s.x.toDouble());put("y",s.y.toDouble());put("scale",s.scale.toDouble());put("rotation",s.rotation.toDouble());put("alpha",s.alpha.toDouble());put("startMs",s.startMs);put("endMs",s.endMs);put("speed",s.speed.toDouble());put("loop",s.loop);put("keyframes",JSONArray().apply{s.keyframes.forEach{put(keyframeToJson(it))}});put("trackingPath",JSONArray().apply{s.trackingPath.forEach{put(trackingToJson(it))}})}
    private fun animatedStickerFromJson(j:JSONObject):AnimatedStickerLayer{fun <T> arr(name:String,p:(JSONObject)->T):List<T>{val a=j.optJSONArray(name)?:JSONArray();return buildList{for(i in 0 until a.length())a.optJSONObject(i)?.let{add(p(it))}}};return AnimatedStickerLayer(id=j.optString("id",UUID.randomUUID().toString()),kind=enumOrDefault(j.optString("kind"),AnimatedStickerKind.SPARKLE),x=j.optDouble("x",0.0).toFloat(),y=j.optDouble("y",0.0).toFloat(),scale=j.optDouble("scale",0.35).toFloat(),rotation=j.optDouble("rotation",0.0).toFloat(),alpha=j.optDouble("alpha",1.0).toFloat(),startMs=j.optLong("startMs",0L),endMs=j.optLong("endMs",Long.MAX_VALUE),speed=j.optDouble("speed",1.0).toFloat(),loop=j.optBoolean("loop",true),keyframes=arr("keyframes",::keyframeFromJson),trackingPath=arr("trackingPath",::trackingFromJson))}

    private fun audioToJson(a:AudioTrack)=JSONObject().apply{put("uri",a.uri);put("name",a.name);put("volume",a.volume.toDouble())}
    private fun audioFromJson(j:JSONObject)=AudioTrack(j.getString("uri"),j.optString("name","Музыка"),j.optDouble("volume",0.65).toFloat())
    private fun positionedAudioToJson(a:PositionedAudioTrack)=JSONObject().apply{put("id",a.id);put("uri",a.uri);put("name",a.name);put("sourceDurationMs",a.sourceDurationMs);put("startAtMs",a.startAtMs);put("volume",a.volume.toDouble())}
    private fun positionedAudioFromJson(j:JSONObject)=PositionedAudioTrack(j.optString("id",UUID.randomUUID().toString()),j.getString("uri"),j.optString("name","Звук"),j.optLong("sourceDurationMs",1L).coerceAtLeast(1L),j.optLong("startAtMs",0L).coerceAtLeast(0L),j.optDouble("volume",0.85).toFloat())
    private fun subtitleToJson(s:SubtitleCue)=JSONObject().apply{put("id",s.id);put("startMs",s.startMs);put("endMs",s.endMs);put("text",s.text)}
    private fun subtitleFromJson(j:JSONObject)=SubtitleCue(j.optString("id",UUID.randomUUID().toString()),j.optLong("startMs",0L),j.optLong("endMs",2000L),j.optString("text",""))
    private fun subtitleStyleToJson(s:SubtitleStyle)=JSONObject().apply{put("fontScale",s.fontScale.toDouble());put("textColor",s.textColor);put("backgroundColor",s.backgroundColor);put("backgroundEnabled",s.backgroundEnabled);put("verticalPosition",s.verticalPosition.toDouble());put("fontKey",s.fontKey);put("fontDisplayName",s.fontDisplayName);put("fontFilePath",s.fontFilePath);put("outlineColor",s.outlineColor);put("outlineWidth",s.outlineWidth.toDouble());put("shadowColor",s.shadowColor);put("shadowRadius",s.shadowRadius.toDouble());put("bold",s.bold);put("italic",s.italic);put("uppercase",s.uppercase);put("letterSpacing",s.letterSpacing.toDouble());put("accentColor",s.accentColor);put("animation",s.animation.name)}
    private fun subtitleStyleFromJson(j:JSONObject)=SubtitleStyle(fontScale=j.optDouble("fontScale",1.0).toFloat(),textColor=j.optInt("textColor",-1),backgroundColor=j.optInt("backgroundColor",0xB3000000.toInt()),backgroundEnabled=j.optBoolean("backgroundEnabled",true),verticalPosition=j.optDouble("verticalPosition",0.84).toFloat(),fontKey=j.optString("fontKey","sans-serif"),fontDisplayName=j.optString("fontDisplayName","Системный"),fontFilePath=j.optString("fontFilePath",""),outlineColor=j.optInt("outlineColor",0xFF000000.toInt()),outlineWidth=j.optDouble("outlineWidth",1.6).toFloat(),shadowColor=j.optInt("shadowColor",0xB3000000.toInt()),shadowRadius=j.optDouble("shadowRadius",1.2).toFloat(),bold=j.optBoolean("bold",true),italic=j.optBoolean("italic",false),uppercase=j.optBoolean("uppercase",false),letterSpacing=j.optDouble("letterSpacing",0.0).toFloat(),accentColor=j.optInt("accentColor",0xFFFFD54F.toInt()),animation=enumOrDefault(j.optString("animation"),SubtitleAnimation.NONE))
    private fun exportToJson(e:ExportSettings)=JSONObject().apply{put("height",e.height);put("maxFrameRate",e.maxFrameRate);if(e.aspectRatio==null)put("aspectRatio",JSONObject.NULL)else put("aspectRatio",e.aspectRatio.toDouble());put("cropToFill",e.cropToFill);put("videoCodec",e.videoCodec.name)}
    private fun exportFromJson(j:JSONObject)=ExportSettings(j.optInt("height",1080),j.optInt("maxFrameRate",30),if(j.isNull("aspectRatio"))null else j.optDouble("aspectRatio").toFloat(),j.optBoolean("cropToFill",false),enumOrDefault(j.optString("videoCodec"),VideoCodec.H264))
    private inline fun <reified T:Enum<T>> enumOrDefault(value:String?,default:T):T=runCatching{enumValueOf<T>(value.orEmpty())}.getOrDefault(default)
}
