plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dinomosaic.kids'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dinomosaic.kids.clean20260914'
        minSdk 23
        targetSdk 35
        versionCode 8
        versionName '1.2.0'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.yandex.android:mobileads:8.4.0'
    implementation 'ru.rustore.sdk:review:10.0.0'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.0.21'
}
