import { districts,jobs,homes,vehicles,businesses,upgrades,marketLabels } from '../data/world.js';
import { people } from '../data/people.js';
import { dialogues,nextDialogue } from '../data/dialogues.js';
import { milestones,routesToSuccess,goalReached,goalsSnapshot,successRoutes } from '../data/goals.js';
import { romancePeople,romanceAccess,romancePortraitAtlas,romanceGifts } from '../data/romance.js';
import { romanceConflictChoices } from '../systems/romance.js';
import { events } from '../data/events.js';
import { incidents } from '../data/incidents.js';
import { investments } from '../data/investments.js';
import { crimes } from '../data/crime.js';
import { activities } from '../data/activities.js';
import { casinoGames,casinoLimit,casinoRemaining } from '../data/casino.js';
import { blackjackValue,cardLabel,pokerScore,isRed } from '../systems/casinoTable.js';
import { backgrounds,characters,heroStage,transport,portraits,items,casinoArt } from '../assets/manifest.js';
import { byId,districtUnlocked,travelPrice,travelOptions,netWorth,businessStrategies } from '../systems/economy.js';

export const money=n=>`${Math.round(n).toLocaleString('ru-RU')} ₽`;
export const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const b=(label,action,id='',disabled=false,cls='')=>`<button class="${cls}" data-action="${action}" data-id="${id}" ${disabled?'disabled':''}>${label}</button>`;
const statNames={health:'Здоровье',energy:'Энергия',mood:'Настроение',respect:'Уважение',fame:'Известность',stress:'Стресс',appeal:'Привлекательность',contacts:'Связи',crime:'Криминал',business:'Деловая репутация',life:'Качество жизни'};
const statsPrimary=['health','energy','mood','stress'];
const statsSecondary=['respect','fame','appeal','contacts','crime','business','life'];
const nav=[['city','ГОРОД','01'],['work','РАБОТА','02'],['assets','ВЕЩИ','03'],['business','ДЕЛА','04'],['people','ЛЮДИ','05'],['story','ЦЕЛИ','06']];
const homeRank=id=>homes.findIndex(x=>x.id===id);

function bar(key,value,large=false) {const short={health:'ЗДР.',energy:'ЭНЕР.',mood:'НАСТР.',stress:'СТР.'}[key]||statNames[key];return `<div class="stat ${large?'large':''} ${key==='stress'||key==='crime'?'warning':''}"><div class="stat-caption"><span><span class="stat-full">${statNames[key]}</span><span class="stat-short" title="${statNames[key]}">${short}</span></span><strong>${value}</strong></div><div class="stat-track"><i style="width:${Math.min(100,value)}%"></i></div></div>`;}
function currentGoal(s) {
  const count=new Set([...(s.achievedRoutes||[]),...successRoutes(s).map(x=>x.id)]).size;
  return `Достигнуто направлений: ${count}/3. Работа, бизнес, связи и риск можно совмещать.`;
}
const routeDone=(s,route)=>(s.achievedRoutes||[]).includes(route.id)||goalReached(s,route);
function goalRequirements(s,goal){const v=goalsSnapshot(s);return Object.entries(goal.need).map(([key,target])=>{const names={wealth:'Капитал',businesses:'Дела',respect:'Уважение',contacts:'Связи',crime:'Криминал',jobs:'Смены',homeRank:'Жильё',vehicleRank:'Транспорт',district:'Район'};return `<span class="${key==='district'?v.districts.includes(target)?'met':'':v[key]>=target?'met':''}">${names[key]}: ${key==='district'?(v.districts.includes(target)?'посещён':'впереди'):key==='wealth'?`${money(v[key])} / ${money(target)}`:`${v[key]} / ${target}`}</span>`}).join('')}
function recoveryStrip(s) {
  if(s.stats.energy>=35||s.jailDays)return '';
  const target=Math.min(100,75+Math.round((byId(homes,s.home)?.restore||28)*.2)+Math.round(s.stats.life*.08));
  const rested=s.lastRestDay===s.day;
  return `<div class="recovery-strip" role="region" aria-label="Восстановление энергии"><div class="recovery-copy"><strong>СИЛЫ НА ИСХОДЕ · ${s.stats.energy}/100</strong><span>${rested?'Передышка уже была':'Передышка +22 за 1 ч'} · сон до ${target} за 8 ч</span></div><div class="recovery-actions">${b(rested?'УЖЕ ОТДЫХАЛ':'ПЕРЕДЫШКА','activity','rest',rested,'rest-button')}${b('СПАТЬ','activity','sleep',false,'sleep-button')}</div></div>`;
}
export function shell(s,tab,shopType,mini,earningMode='legal',dialogueId=null,dialogueResult=null,travelId=null,peopleMode='contacts') {
  const d=byId(districts,s.district),nw=netWorth(s),won=routesToSuccess.find(route=>routeDone(s,route));
  return `<div class="app-shell">
    <header class="masthead"><div class="brand"><div class="brand-mark">ИГ<span>ВК</span></div><div><div class="brand-title">ИЗ ГРЯЗИ <em>В КНЯЗИ</em></div><div class="brand-tag">РОССИЯ НЕ ПРОЩАЕТ, НО ИНОГДА ДАЁТ ШАНС</div></div></div><div class="top-economy"><div><small>НАЛИЧНЫЕ</small><strong class="cash">${money(s.money)}</strong></div><div><small>СОСТОЯНИЕ</small><strong>${money(nw)}</strong></div><div><small>ВРЕМЯ</small><strong>ДЕНЬ ${s.day} <span class="time">${String(s.hour).padStart(2,'0')}:00</span></strong></div></div><button class="header-menu" data-action="menu" title="Сохранение и настройки">☰</button></header>
    <div class="workspace">
      <aside class="sidebar"><div class="id-card"><div class="portrait-mini"><span>${nw>=30000000?'СОСТОЯЛСЯ':nw>=100000?'ПРЕДПРИНИМАТЕЛЬ':'ЖИТЕЛЬ'}</span><img class="portrait-character" src="${characters[heroStage(s)]}" alt=""></div><div class="id-meta"><span class="eyebrow">ЛИЧНОЕ ДЕЛО / № 001</span><h2>${nw>=30000000?'Человек с видом':nw>=100000?'Хозяин положения':'Человек с района'}</h2><p>${esc(byId(homes,s.home).name)} · ${esc(byId(vehicles,s.vehicle).name)}</p></div></div><div class="side-section"><h3>СОСТОЯНИЕ</h3>${statsPrimary.map(key=>bar(key,s.stats[key],true)).join('')}</div><div class="side-section traits"><h3>РЕПУТАЦИЯ</h3>${statsSecondary.map(key=>`<div class="trait"><span>${statNames[key]}</span><strong>${s.stats[key]}</strong></div>`).join('')}</div><div class="side-section skill-lines"><h3>НАВЫКИ</h3><div><span>Хватка</span><b>УР. ${s.skills.grit}</b></div><div><span>Обаяние</span><b>УР. ${s.skills.charm}</b></div><div><span>Смекалка</span><b>УР. ${s.skills.focus}</b></div></div></aside>
      <main class="main-content"><section class="scene-wrap scene-tier-${d.tier}"><div class="scene-top"><span class="weather-tag"><span class="weather-dot"></span>${esc(d.weather.toUpperCase())}</span><span class="scene-index">РАЙОН ${String(d.tier+1).padStart(2,'0')} / 06</span></div><div id="scene"></div><div class="scene-hotspots"><button class="hotspot hotspot-work" data-tab="work" aria-label="Открыть работу"><i></i><span>РАБОТА</span></button><button class="hotspot hotspot-people" data-tab="people" aria-label="Открыть людей"><i></i><span>ЛЮДИ</span></button><button class="hotspot hotspot-assets" data-tab="assets" aria-label="Открыть покупки"><i></i><span>ПОКУПКИ</span></button></div><div class="scene-overlay"><div><span class="eyebrow">ТЕКУЩАЯ ЛОКАЦИЯ</span><h1>${esc(d.name)}</h1><p>${esc(d.subtitle)}</p></div><button class="scene-map" data-tab="city">КАРТА ГОРОДА <span>↗</span></button></div></section><nav class="main-nav" aria-label="Разделы игры">${nav.map(([id,label,num])=>`<button data-tab="${id}" class="${tab===id?'active':''}"><small>${num}</small><span>${label}</span></button>`).join('')}</nav>${recoveryStrip(s)}<section class="view" id="view">${view(s,tab,shopType,earningMode,peopleMode)}</section></main>
      <aside class="rightbar"><div class="paper-pin"></div><div class="right-card chapter-preview"><span class="eyebrow">ДОСЬЕ / 3 ПУТИ</span><h3>${esc(won?.name||'УСПЕХ ВПЕРЕДИ')}</h3><p>${esc(won?.text||'Совмещай работу, дела, связи и риск.')}</p><div class="goal-label">СЛЕДУЮЩИЙ РУБЕЖ</div><div class="goal-text">${esc(currentGoal(s))}</div>${b('ОТКРЫТЬ ЦЕЛИ','tab-story','','','text-button')}</div><div class="right-card small-economy"><span class="eyebrow">ЭКОНОМИКА СЕГОДНЯ</span><div><span>Рынок</span><strong>${marketLabels[s.market]}</strong></div><div><span>Бизнесов</span><strong>${Object.keys(s.businesses).length}</strong></div><div><span>Долг</span><strong class="${s.debt?'danger-text':''}">${money(s.debt)}</strong></div><div><span>Рабочих смен</span><strong>${s.jobsDone}</strong></div></div><div class="right-card journal"><span class="eyebrow">ЛЕНТА ГОРОДА</span><div class="journal-scroll">${s.log.slice(0,7).map(e=>`<div class="log-entry ${e.type}"><small>ДЕНЬ ${e.day} · ${String(e.hour).padStart(2,'0')}:00</small><p>${esc(e.text)}</p></div>`).join('')}</div></div><div class="auto-save">● АВТОСОХРАНЕНИЕ ВКЛЮЧЕНО</div></aside>
    </div><div id="toast-zone" aria-live="polite"></div><div id="modal-root">${modal(s,mini,dialogueId,dialogueResult,travelId)}</div></div>`;
}

function view(s,tab,shopType,earningMode,peopleMode) {
  if(tab==='city')return city(s);
  if(tab==='work')return work(s,earningMode);
  if(tab==='assets')return assets(s,shopType);
  if(tab==='business')return business(s);
  if(tab==='people')return peopleView(s,peopleMode);
  return story(s);
}
function heading(kicker,title,sub) {return `<div class="section-heading"><div><span class="eyebrow">${kicker}</span><h2>${title}</h2><p>${sub}</p></div></div>`;}
function city(s) {
  return `${heading(`КАРТА / ${districts.length} РАЙОНОВ`,'Город без инструкции','Каждый район открывает работу, людей и дела. Выбирай способ дороги: время, цена и риск различаются.')}
    <div class="district-grid">${districts.map((d,i)=>{const unlocked=districtUnlocked(s,d),here=s.district===d.id;return `<article class="district-card ${here?'here':''} ${unlocked?'':'locked'}" style="--accent:${d.palette[2]};--district-image:url('${backgrounds[d.id]}')"><div class="district-no">0${i+1}<span>${here?'ВЫ ЗДЕСЬ':unlocked?'ДОСТУПЕН':'ЗАКРЫТ'}</span></div><h3>${esc(d.name)}</h3><p>${esc(d.subtitle)}</p><div class="district-places">${d.places.map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="district-bottom"><span>${here?`ТЫ УЖЕ ЗДЕСЬ`:unlocked?`ПЕШКОМ БЕСПЛАТНО · БИЛЕТ ${money(travelPrice(s,d.id))}`:`Доступ: уважение ${d.required.respect} ИЛИ капитал ${money(d.required.wealth)} ИЛИ связи ${d.required.contacts}`}</span>${here?'<span class="current-label">ТЕКУЩИЙ</span>':b(unlocked?'ВЫБРАТЬ ПУТЬ →':'ЗАКРЫТО','choose-travel',d.id,!unlocked,'small-button')}</div></article>`}).join('')}</div>
    <div class="two-column"><section class="utility-panel"><h3>ДЕНЬ В ГОРОДЕ</h3><p>Быт, знакомства и местные занятия меняются вместе с районом.</p><div class="activity-grid">${activities.filter(a=>!a.district||a.district===s.district).map(a=>`<button data-action="activity" data-id="${a.id}" ${s.money<a.cost||a.id==='rest'&&s.lastRestDay===s.day?'disabled':''}><strong>${esc(a.name)}</strong><small>${a.id==='rest'?(s.lastRestDay===s.day?'УЖЕ БЫЛА СЕГОДНЯ':'+22 энергии · 1 ч'):a.id==='sleep'?'до 80+ энергии · 8 ч':`${a.cost?money(a.cost):'БЕСПЛАТНО'} · ${a.hours} ч`}</small></button>`).join('')}</div></section><section class="utility-panel"><h3>СЕГОДНЯ В РАЙОНЕ</h3><p>Работа и люди меняются вместе с адресом. Загляни к местным — полезные знакомства редко выглядят полезными.</p><div class="local-lines"><div><span>Подработок</span><strong>${jobs.filter(j=>j.district===s.district).length}</strong></div><div><span>Тёмных дел</span><strong>${crimes.filter(c=>c.district===s.district).length}</strong></div><div><span>Знакомых лиц</span><strong>${people.filter(p=>p.district===s.district).length}</strong></div><div><span>Твоя машина</span><strong>${esc(byId(vehicles,s.vehicle).name)}</strong></div></div>${b('ПОСМОТРЕТЬ РАБОТУ →','tab-work','','','primary')}</section></div>`;
}
function work(s,mode='legal') {
  const local=jobs.filter(j=>j.district===s.district);
  const localCrime=crimes.filter(c=>c.district===s.district);
  const localFirms=businesses.filter(x=>x.district===s.district||s.businesses[x.id]);
  const paths=[['legal','РАБОТА','Смена · зарплата'],['business','БИЗНЕС','Капитал · риск'],['crime','КРИМИНАЛ','Куш · срок'],['casino','КАЗИНО','Ставка · шанс']];
  const selector=`<div class="earning-paths">${paths.map(([id,title,subtitle])=>`<button data-earn="${id}" class="${mode===id?'active':''} ${id}"><strong>${title}</strong><span>${subtitle}</span></button>`).join('')}</div>`;
  if(mode==='casino')return casino(s,selector);
  if(mode==='crime')return `${heading('ЗАРАБОТОК / ТЁМНАЯ СТОРОНА','Криминальные заказы','Высокая выплата не гарантирована. У каждого дела свой шанс провала. Розыск не накапливается; последствия зависят от конкретного случая.')}${selector}<div class="risk-summary"><strong>РИСК КАЖДОГО ДЕЛА ОТДЕЛЬНО</strong><span>Задержаний: ${s.arrestCount||0} · дел: ${s.crimesDone||0}</span></div><div class="job-grid earning-deck">${localCrime.map(c=>`<article class="job-card crime-card"><img class="earning-card-art" src="${backgrounds[c.district]}" alt=""><div class="job-top"><span class="ticket-label">НЕЛЕГАЛЬНЫЙ ЗАКАЗ</span><span>ДЕЛО № ${c.id.toUpperCase()}</span></div><h3>${esc(c.name)}</h3><p>${esc(c.description)}</p><div class="job-metrics"><div><small>ВЫПЛАТА</small><strong>${money(c.pay)}</strong></div><div><small>АРЕСТ · БАЗА</small><strong>${Math.round(c.arrest*100)}%</strong></div><div><small>ТРАВМА</small><strong>${Math.round(c.injury*100)}%</strong></div></div><div class="crime-consequence">При задержании: штраф до ${money(c.fine)}, арест до ${c.jail} дн. или побои · ${c.hours} ч · энергия −${c.energy}</div>${b('РИСКНУТЬ','crime',c.id,s.stats.energy<c.energy||s.stats.health<20||s.jailDays>0,'primary')}</article>`).join('')}</div>`;
  if(mode==='business')return `${heading('ЗАРАБОТОК / КАПИТАЛ','Своё дело','Бизнес платит каждый день, но аренда, персонал, поломки и кризисы забирают часть выручки.')}${selector}<div class="job-grid earning-deck">${localFirms.map(x=>{const owned=!!s.businesses[x.id];return `<article class="job-card venture-card"><img class="earning-card-art" src="${x.id==='casino'?casinoArt.floor:backgrounds[x.district]}" alt=""><div class="job-top"><span class="ticket-label">${owned?'ТВОЙ БИЗНЕС':'ВЛОЖЕНИЕ'}</span><span>АВАРИИ ${Math.round(x.risk*15)}%/ДЕНЬ</span></div><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="job-metrics"><div><small>ЦЕНА</small><strong>${money(x.price)}</strong></div><div><small>ВЫРУЧКА</small><strong>${money(x.base)}/Д</strong></div><div><small>РАСХОД</small><strong>${money(x.upkeep)}/Д</strong></div></div><div class="crime-consequence">Потребуются ремонт, команда и запас денег на плохой рынок.</div>${owned?b('УПРАВЛЯТЬ','tab-business',x.id,false,'primary'):b('КУПИТЬ БИЗНЕС','buy-business',x.id,s.money<x.price,'primary')}</article>`}).join('')}</div>${b('ВСЕ ДЕЛА И ВЛОЖЕНИЯ →','tab-business','','','text-button')}`;
  return `${heading('ЗАРАБОТОК / ЧЕСТНЫЙ ТРУД','Работа найдётся','Фиксированная оплата за смену. Шанс травмы мал; ареста нет. Навык и результат мини-игры влияют на сумму.')}${selector}<div class="job-grid earning-deck">${local.map(j=>`<article class="job-card legal-card"><img class="earning-card-art" src="${backgrounds[j.district]}" alt=""><div class="job-top"><span class="ticket-label">ЛЕГАЛЬНАЯ СМЕНА</span><span>ТРАВМА ${Math.round(j.risk*100)}%</span></div><h3>${esc(j.name)}</h3><p>${esc(j.description)}</p><div class="job-metrics"><div><small>БАЗА</small><strong>${money(j.pay)}</strong></div><div><small>ВРЕМЯ</small><strong>${j.hours} Ч</strong></div><div><small>ЭНЕРГИЯ</small><strong>−${j.energy}</strong></div></div><div class="crime-consequence">Никаких штрафов и ареста. Усталость и стресс остаются.</div>${b('ВЫЙТИ НА СМЕНУ','job',j.id,s.stats.energy<j.energy||s.stats.health<12||s.jailDays>0,'primary')}</article>`).join('')}</div>`;
}
function casino(s,selector) {
  const remaining=casinoRemaining(s),max=Math.max(0,Math.min(s.money,remaining)),bet=Math.min(100,max),record=s.casino||{rounds:0,wins:0,wagered:0,returned:0,history:[]};
  return `${heading('ЗАРАБОТОК / АЗАРТ','Казино «Зеро»','Рулетка, 21 и покер — полноценные партии с решениями. Ставка уходит в банк сразу; можно выиграть или потерять её.')}${selector}
    <section class="casino-hero" style="--casino-floor:url('${casinoArt.floor}')"><div class="casino-hero-copy"><span class="eyebrow">ЗАЛ ОТКРЫТ / 24 ЧАСА</span><h3>УДАЧА ЛЮБИТ СЧЁТ</h3><p>Дом всегда оставляет себе преимущество. Все шансы указаны до ставки.</p></div></section>
    <div class="casino-status"><div><small>НА СЕГОДНЯ</small><strong>${money(remaining)} / ${money(s.casinoDaily?.day===s.day&&s.casinoDaily.limit||casinoLimit(s))}</strong></div><div><small>РАУНДОВ</small><strong>${record.rounds}</strong></div><div><small>ИТОГ ЗА ВСЁ ВРЕМЯ</small><strong class="${record.returned-record.wagered<0?'danger-text':''}">${record.returned-record.wagered>=0?'+':''}${money(record.returned-record.wagered)}</strong></div></div>
    <div class="casino-bet"><label for="casino-stake">ТВОЯ СТАВКА</label><div class="casino-bet-entry"><input id="casino-stake" type="number" min="50" max="${max}" step="50" value="${bet}" inputmode="numeric" aria-label="Ставка в рублях"><span>₽</span></div><div class="casino-chips">${[50,250,1000,5000,25000].map(n=>`<button type="button" data-bet="${n}" ${n>max?'disabled':''}>${money(n)}</button>`).join('')}</div></div>
    <div class="casino-grid">${casinoGames.map((game,i)=>`<article class="casino-card"><div class="casino-card-art ${game.asset}" style="--casino-floor:url('${casinoArt.floor}')"><img src="${casinoArt[game.asset]||casinoArt.floor}" alt="" loading="lazy"></div><div class="casino-card-body"><span class="eyebrow">СТОЛ 0${i+1}</span><h3>${esc(game.name)}</h3><p>${esc(game.description)}</p><div class="casino-odds"><span>ИГРА <b>${esc(game.chance)}</b></span><span>ВЫПЛАТА <b>${esc(game.payout)}</b></span></div>${b('СЕСТЬ ЗА СТОЛ','casino',game.id,max<50||s.stats.energy<4||s.jailDays>0,'primary')}</div></article>`).join('')}</div>
    <section class="casino-history"><h3>ПОСЛЕДНИЕ РАУНДЫ</h3>${record.history.length?record.history.slice(0,5).map(x=>`<div><span>ДЕНЬ ${x.day} · ${esc(x.game)}<small>${esc(x.result)}</small></span><strong class="${x.net<0?'danger-text':''}">${x.net>=0?'+':''}${money(x.net)}</strong></div>`).join(''):'<p>За столом пока тихо.</p>'}</section>`;
}
function assets(s,type) {
  const selected=type||'home';const list={home:homes,vehicle:vehicles,upgrade:upgrades}[selected];
  return `${heading('ПОКУПКИ / СТАТУС / УДОБСТВО','Вложить в себя','Жильё восстанавливает силы. Транспорт экономит время и цену поездок. Вещи повышают навыки.')}
  <div class="subtabs">${[['home','ЖИЛЬЁ'],['vehicle','ТРАНСПОРТ'],['upgrade','ВЕЩИ И НАВЫКИ']].map(([id,label])=>`<button data-shop="${id}" class="${selected===id?'active':''}">${label}</button>`).join('')}</div><div class="asset-grid">${list.map((item,i)=>{
    const owned=selected==='home'?s.ownedHomes.includes(item.id):selected==='vehicle'?s.ownedVehicles.includes(item.id):s.upgrades.includes(item.id);
    const equipped=selected==='home'?s.home===item.id:selected==='vehicle'?s.vehicle===item.id:false;
    const meta=selected==='home'?`ВОССТ. +${item.restore} · ${item.daily?`ЖИЛЬЁ ${money(item.daily)}/ДЕНЬ`:'ЖИЛЬЁ БЕСПЛАТНО · БЫТ 110 ₽/ДЕНЬ'}`:selected==='vehicle'?`ПРОЕЗД ×${item.fareFactor} · СОДЕРЖ. ${money(item.upkeep)}/ДЕНЬ`:`${{grit:'ХВАТКА',charm:'ОБАЯНИЕ',focus:'СМЕКАЛКА'}[item.stat]} +${item.amount}`;
    return `<article class="asset-card"><div class="asset-art asset-${selected} asset-index-${i}"><span>${String(i+1).padStart(2,'0')}</span><img class="asset-raster" src="${selected==='home'?backgrounds[['yard','yard','market','center','glass','glass','heights','heights'][i]]:selected==='vehicle'?(transport[item.id]||characters.poor):(items[item.id]||characters[['worker','jacket','middle','suit','magnate','rich'][Math.max(0,i-6)]])}" alt=""></div><div class="asset-body"><small>${meta}</small><h3>${esc(item.name)}</h3><p>${esc(item.description)}</p><div class="asset-footer"><strong>${item.price?money(item.price):'БЕСПЛАТНО'}</strong>${equipped?'<span class="owned">ИСПОЛЬЗУЕТСЯ</span>':owned?selected==='upgrade'?'<span class="owned">КУПЛЕНО</span>':b('ВЫБРАТЬ','equip-'+selected,item.id,false,'small-button'):b('КУПИТЬ','buy-'+selected,item.id,s.money<item.price,'small-button')}</div></div></article>`}).join('')}</div>`;
}
function business(s) {
  return `${heading('ПРЕДПРИНИМАТЕЛЬСТВО / ИНВЕСТИЦИИ','Деньги должны работать','Бизнес даёт ежедневный доход, но требует персонал, ремонт и переживает кризисы. Рынок меняется каждый день.')}
  ${s.debt?`<div class="debt-panel"><div><span class="eyebrow">ДОЛГ / ПРОЦЕНТЫ КАЖДЫЙ ДЕНЬ</span><strong>${money(s.debt)}</strong><p>Погашение уменьшает ежедневные расходы и будущие проценты.</p></div><div><input id="debt-amount" type="number" min="1" max="${Math.min(s.money,s.debt)}" value="${Math.max(0,Math.min(s.money,s.debt))}">${b('ПОГАСИТЬ','pay-debt','','','small-button')}</div></div>`:''}
  <div class="business-grid">${[...businesses].sort((a,b)=>byId(districts,a.district).tier-byId(districts,b.district).tier||a.price-b.price).map((item,i)=>{const owned=s.businesses[item.id],district=byId(districts,item.district),unlocked=districtUnlocked(s,district),strategy=businessStrategies[owned?.strategy]||businessStrategies.normal,profit=item.base*(owned?.level||1)*(owned?.staff?1.32:1)*strategy.income-(item.upkeep*(owned?1+.38*(owned.level-1):1)+(owned?.staff?item.staff:0))*strategy.expense;return `<article class="business-card ${owned?'is-owned':''}"><div class="business-band" style="--district-image:url('${item.id==='casino'?casinoArt.floor:backgrounds[item.district]}')"><span>ДЕЛО ${String(i+1).padStart(2,'0')}</span><span>${esc(district.short.toUpperCase())}</span></div><div class="business-content"><h3>${esc(item.name)}</h3><p>${esc(item.description)}</p><div class="business-numbers"><div><small>ДОХОД ДО РАСХОДОВ</small><strong>${money(item.base)}/ДЕНЬ</strong></div><div><small>ОБСЛУЖИВАНИЕ</small><strong>${money(item.upkeep)}/ДЕНЬ</strong></div></div>${owned?`<div class="firm-state"><span>УРОВЕНЬ ${owned.level}/5</span><span>СОСТОЯНИЕ ${owned.condition}%</span><span>РЕЖИМ ${strategy.label.toUpperCase()}</span><strong>≈ ${money(profit)}/ДЕНЬ</strong></div><div class="firm-controls">${b('РАСШИРИТЬ','manage-upgrade',item.id,owned.level>=5||s.money<Math.round(item.upgrade*Math.pow(1.65,owned.level-1)))}${b(owned.staff?'КОМАНДА НАНЯТА':'НАНЯТЬ','manage-staff',item.id,owned.staff||s.money<item.staff*3)}${b('РЕМОНТ','manage-repair',item.id,owned.condition>=100||s.money<item.upkeep*3)}</div><div class="strategy-controls"><small>КАК ВЕСТИ ДЕЛО</small>${Object.entries(businessStrategies).map(([key,mode])=>`<button data-action="manage-strategy-${key}" data-id="${item.id}" class="${(owned.strategy||'normal')===key?'active':''}">${mode.label}<span>доход ×${mode.income} · риск ×${mode.risk}</span></button>`).join('')}</div>`:b(unlocked?`КУПИТЬ ЗА ${money(item.price)}`:'РАЙОН ЗАКРЫТ','buy-business',item.id,!unlocked||s.money<item.price,'primary')}</div></article>`}).join('')}</div>
  <section class="investments"><div class="invest-heading"><div><span class="eyebrow">КАПИТАЛ / ТЕРПЕНИЕ</span><h2>Вложения</h2><p>Виртуальные сделки. Выплата приходит через несколько игровых дней и может оказаться меньше вложения.</p></div></div><div class="invest-grid">${investments.map(x=>`<article><div class="invest-title"><h3>${esc(x.name)}</h3><span>${x.days} ДНЕЙ</span></div><p>${esc(x.description)}</p><div class="invest-band">ВОЗМОЖНЫЙ ИТОГ · ${Math.round(x.low*100)}–${Math.round(x.high*100)}%</div><label>СУММА <input type="number" min="${x.min}" step="1000" value="${x.min}" id="invest-${x.id}"></label>${b('ВЛОЖИТЬ','invest',x.id,s.money<x.min,'small-button')}</article>`).join('')}</div>${s.investments?.length?`<div class="active-investments"><h3>ДЕЙСТВУЮЩИЕ ВЛОЖЕНИЯ</h3>${s.investments.map(x=>`<div><span>${esc(byId(investments,x.id)?.name)}</span><strong>${money(x.amount)}</strong><small>ДЕНЬ ${x.maturity}</small></div>`).join('')}</div>`:''}</section>`;
}
function peopleView(s,mode='contacts') {
  return `<div class="people-mode"><button data-people-mode="contacts" class="${mode==='contacts'?'active':''}">ЗНАКОМЫЕ</button><button data-people-mode="romance" class="${mode==='romance'?'active':''}">ОТНОШЕНИЯ</button></div>${mode==='romance'?romance(s):contacts(s)}`;
}
const establishedRomance=(s,person)=>{const p=s.romance?.profiles?.[person.id];return !!(s.romance?.partner===person.id||p?.everPartner||p?.married||p?.days>0);};
function romanceCard(s,person) {
  const active=s.romance?.partner,p=s.romance?.profiles?.[person.id],reason=romanceAccess(s,person),met=!!p?.met,partner=active===person.id,available=!reason&&(!person.district||s.district===person.district),doneToday=p?.lastDay===s.day,rapport=p?.rapport||0,stage=p?.appearance||0,established=establishedRomance(s,person);
  const control=(label,action,disabled=false)=>`<button data-romance-action="${action}" data-id="${person.id}" ${disabled?'disabled':''}>${label}</button>`;
  return `<article class="romance-card stage-${stage} ${partner?'partner':''}"><div class="romance-portrait" style="--romance-atlas:url('${romancePortraitAtlas}');--portrait-pos:${person.portrait*25}%"><span>0${person.portrait+1}</span><small>${partner?'ВМЕСТЕ':established?'БЫЛИ ВМЕСТЕ':met?'ЗНАКОМЫ':'НОВАЯ ВСТРЕЧА'}</small></div><div class="romance-body"><span class="eyebrow">${esc(person.role.toUpperCase())}</span><h3>${esc(person.name)}</h3><p>${esc(p?.last||person.description)}</p>${met?`<div class="romance-trust"><span>ДОВЕРИЕ</span><strong>${rapport}/100</strong><i style="width:${rapport}%"></i></div>`:''}<div class="romance-status">${met?`Встреч: ${p.meetings||0} · вместе: ${partner?p.days||0:0} дн. · ссор: ${p.quarrels||0}`:reason?esc(reason):'Вы ещё не знакомы'}</div><div class="romance-actions">${!met?control('ПОЗНАКОМИТЬСЯ','meet',!available||doneToday):`${control('ПОГОВОРИТЬ','talk',doneToday)}${control(`СВИДАНИЕ · ${money(person.dateCost)}`,'date',doneToday||s.money<person.dateCost)}`}${met&&!partner&&!active?control(`БЫТЬ ВМЕСТЕ · ${person.commit} ДОВ.`,'commit',rapport<person.commit):''}${partner&&!p?.married?control('ПОЖЕНИТЬСЯ','marry',(p?.days||0)<8||rapport<80):''}${partner?control('РАССТАТЬСЯ','separate'):''}</div>${met?`<details class="gift-picker"><summary>ВЫБРАТЬ ПОДАРОК · 3 ВАРИАНТА</summary><div>${romanceGifts.map(g=>{const price=Math.round(person.giftCost*g.factor);return control(`${g.name} · ${money(price)}`,`gift-${g.id}`,doneToday||s.money<price)}).join('')}</div></details>`:''}${doneToday?'<small class="romance-hint">Сегодня вы уже виделись. Следующий шаг — завтра.</small>':''}</div></article>`;
}
function romance(s) {
  const active=s.romance?.partner;
  const established=romancePeople.filter(person=>establishedRomance(s,person));
  return `${heading('ПАРЫ / СЕМЬЯ / ПРОШЛОЕ','Личная жизнь','Здесь появляются отношения, которые ты действительно начал. Знакомства и свидания до решения быть вместе остаются в разделе «Знакомые».')}
  <div class="romance-summary">${active?`СЕЙЧАС ВМЕСТЕ · ${esc(romancePeople.find(p=>p.id===active)?.name||active)}`:'СЕЙЧАС ТЫ ОДИН'}<span>${established.length?`ИСТОРИЙ ОТНОШЕНИЙ · ${established.length}`:'СНАЧАЛА ПОЗНАКОМЬСЯ И РЕШИ БЫТЬ ВМЕСТЕ'}</span></div>
  ${established.length?`<div class="romance-grid">${established.map(person=>romanceCard(s,person)).join('')}</div>`:'<div class="romance-empty"><strong>Пока нет отношений</strong><p>Ищи людей в своём районе, знакомься и проводи время вместе. Когда вы решите стать парой, ваша история появится здесь.</p><button data-people-mode="contacts">ПЕРЕЙТИ К ЗНАКОМЫМ →</button></div>'}`;
}
function contacts(s) {
  const local=people.filter(p=>p.district===s.district||p.id==='valera'&&s.district==='market'||p.id==='azamat'&&s.district==='industrial'||p.id==='lida'&&s.district==='center'||p.id==='vera'&&s.district==='glass'||p.id==='artur'&&s.district==='heights');
  const prospects=romancePeople.filter(person=>!establishedRomance(s,person)&&(person.district===s.district||person.id==='irina'&&s.romance?.profiles?.irina?.met));
  return `${heading('СВЯЗИ / РАЗГОВОРЫ / УСЛУГИ','Люди решают','Выбирай ответ: отношения и события меняются. Каждая тема проходит один раз; доверие открывает услуги.')}
  ${prospects.length?`<section class="romance-prospects"><div class="prospect-heading"><span class="eyebrow">ВСТРЕЧИ В ЭТОМ РАЙОНЕ</span><p>Познакомься, поговори, сходи на свидание. Личная история появится в «Отношениях», когда вы станете парой.</p></div><div class="romance-grid">${prospects.map(person=>romanceCard(s,person)).join('')}</div></section>`:''}
  <div class="people-grid">${local.map((p,i)=>{
    const rel=s.relations[p.id]||0,available=s.stats.respect>=p.threshold||s.stats.contacts>=Math.ceil(p.threshold/3)||netWorth(s)>=p.threshold*18000,scene=nextDialogue(s,p.id),seen=s.dialogueProgress?.[p.id]||0,total=dialogues[p.id]?.length||0;
    const quote=s.dialogueLast?.[p.id]||p.lines[0];
    return `<article class="person-card"><div class="person-head" style="--person:${p.accent}"><img class="person-portrait-raster" src="${portraits[p.id]||portraits[{yard:'valera',market:'azamat',industrial:'lida',center:'vera',glass:'artur',heights:'minister'}[p.district]||'valera']}" alt=""><span class="person-number">0${i+1}</span></div><div class="person-info"><span class="eyebrow">${esc(p.role.toUpperCase())}</span><h3>${esc(p.name)}</h3><p>${esc(quote)}</p><div class="dialogue-progress">${scene?`СЛЕДУЮЩАЯ ТЕМА · ${esc(scene.topic)}`:'ВСЕ ТЕМЫ ОБСУЖДЕНЫ'}<span>${seen}/${total}</span></div><div class="relation"><span>ОТНОШЕНИЯ</span><strong>${rel}/100</strong></div><div class="person-actions">${b(available?(scene?'ПОГОВОРИТЬ':'ТЕМЫ ЗАКОНЧИЛИСЬ'):`УВАЖЕНИЕ ${p.threshold} / СВЯЗИ ${Math.ceil(p.threshold/3)}`,'talk',p.id,!available||!scene||s.stats.energy<5,'small-button')}${b(`${esc(p.favor)}${p.cost?` · ${money(p.cost)}`:''}`,'favor',p.id,!available||rel<2||s.money<p.cost)}</div>${s.stats.energy<5&&scene?'<small class="person-hint">На разговор нужно 5 энергии. Переведи дух.</small>':''}</div></article>`;
  }).join('')}</div>`;
}
function story(s) {
  const won=routesToSuccess.find(route=>routeDone(s,route));
  return `${heading('СВОБОДНАЯ ИГРА / ПУТИ / ДОСТИЖЕНИЯ','Твой путь',`Достигнуто направлений: ${new Set([...(s.achievedRoutes||[]),...successRoutes(s).map(x=>x.id)]).size}/3. Развивай несколько путей одновременно и играй дальше без глав и финального экрана.`)}
  <div class="story-layout"><div class="story-list">${routesToSuccess.map((route,i)=>`<article class="chapter-row goal-route ${routeDone(s,route)?'complete':'future'}" style="--chapter-image:url('${backgrounds[route.art]}')"><span class="chapter-num">0${i+1}</span><div><small>ПУТЬ К УСПЕХУ</small><h3>${esc(route.name)}</h3><p>${esc(route.text)}</p><div class="goal-requirements">${goalRequirements(s,route)}</div></div><span class="chapter-state">${routeDone(s,route)?'ДОСТИГНУТО':'ВПЕРЕДИ'}</span></article>`).join('')}${milestones.map((goal,i)=>`<article class="chapter-row ${goalReached(s,goal)?'complete':'future'}" style="--chapter-image:url('${backgrounds[goal.art]}')"><span class="chapter-num">${String(i+4).padStart(2,'0')}</span><div><small>НЕОБЯЗАТЕЛЬНАЯ ЦЕЛЬ</small><h3>${esc(goal.name)}</h3><p>${esc(goal.text)}</p></div><span class="chapter-state">${goalReached(s,goal)?'СДЕЛАНО':'ВПЕРЕДИ'}</span></article>`).join('')}</div><div class="story-sidebar"><div class="goal-paper"><span class="eyebrow">СВОБОДА ВЫБОРА</span><h3>${esc(won?.name||'Путь открыт')}</h3><p>${esc(currentGoal(s))}</p></div><div class="goal-paper"><span class="eyebrow">ЛИЧНАЯ СТАТИСТИКА</span><div class="record"><span>ЗАРАБОТАНО</span><strong>${money(s.totalEarned)}</strong></div><div class="record"><span>ОТРАБОТАНО</span><strong>${s.jobsDone} СМЕН</strong></div><div class="record"><span>КАПИТАЛ</span><strong>${money(netWorth(s))}</strong></div></div></div></div>`;
}
function dialogueModal(s,id,result) {
  const person=byId(people,id),scene=nextDialogue(s,id);
  if(!person)return '';
  const portrait=portraits[id]||portraits.valera;
  const effects={...(result?.effects||{})};if(result)effects.energy=(effects.energy||0)-5;
  const changes=Object.entries(effects).filter(([,n])=>n).map(([key,n])=>`${statNames[key]||key} ${n>0?'+':''}${n}`).join(' · ');
  return `<div class="modal-scrim"><div class="modal dialogue-modal" role="dialog" aria-modal="true" aria-label="Разговор с ${esc(person.name)}"><button class="close-modal" data-action="close-dialogue" aria-label="Закрыть разговор">×</button><div class="dialogue-person"><img src="${portrait}" alt=""><div><span class="eyebrow">РАЗГОВОР / ${esc(person.role.toUpperCase())}</span><h2>${esc(person.name)}</h2><small>ОТНОШЕНИЯ ${s.relations[id]||0}/100 · ТЕМА ${s.dialogueProgress?.[id]||0}/${dialogues[id]?.length||0}</small></div></div>${result?`<div class="dialogue-reply"><span class="eyebrow">${esc(result.dialogueTopic)}</span><p>${esc(result.dialogueReply)}</p></div><div class="dialogue-gains"><strong>ОТНОШЕНИЯ +${result.relationGain}</strong>${changes?`<span>${esc(changes)}</span>`:''}<span>Время +1 ч</span></div>${b('ЗАКОНЧИТЬ РАЗГОВОР','close-dialogue','','','primary big')}`:scene?`<div class="dialogue-question"><span class="eyebrow">${esc(scene.topic.toUpperCase())}</span><p>${esc(scene.prompt)}</p></div><div class="dialogue-choices">${scene.choices.map((choice,i)=>`<button data-dialogue-choice="${i}" ${choice.cost>s.money?'disabled':''}><span>0${i+1}</span><strong>${esc(choice.text)}</strong><small>${choice.cost?`−${money(choice.cost)}`:'ВЫБРАТЬ ОТВЕТ'}</small></button>`).join('')}</div><div class="dialogue-note">ТВОЙ ОТВЕТ ИЗМЕНИТ ОТНОШЕНИЯ И ПОПАДЁТ В ДНЕВНИК</div>`:'<p>Новых тем пока нет.</p>'}</div></div>`;
}
function travelModal(s,id) {
  const district=byId(districts,id);if(!district)return '';
  const options=travelOptions(s,id);
  return `<div class="modal-scrim"><div class="modal travel-modal" role="dialog" aria-modal="true" aria-label="Дорога в ${esc(district.name)}"><button class="close-modal" data-action="close-travel" aria-label="Закрыть">×</button><span class="eyebrow">КАРТА / ВЫБОР МАРШРУТА</span><h2>${esc(district.name)}</h2><p>Дорога зависит от способа. Пешком всегда бесплатно; билет защищает от штрафа.</p><div class="travel-options">${options.map(x=>`<button data-travel-mode="${x.id}" data-id="${id}" ${s.stats.energy<x.energy||s.money<x.cost?'disabled':''}><strong>${esc(x.name)}</strong><span>${x.cost?money(x.cost):'БЕСПЛАТНО'} · ${x.hours} ч · энергия −${x.energy}</span><small>${esc(x.detail)}${x.risk?` Риск ${Math.round(x.risk*100)}%.`:''}${x.fine?` Штраф ${money(x.fine)}.`:''}</small></button>`).join('')}</div></div></div>`;
}
function incidentIllustration(art,portrait=null) {
  if(portrait!==null&&portrait!==undefined)return `<div class="romance-incident-portrait" style="--romance-atlas:url('${romancePortraitAtlas}');--portrait-pos:${portrait*25}%"></div>`;
  const scenes=[['yard','boots'],['yard',''],['market',''],['market',''],['industrial',''],['yard',''],['yard',''],['industrial',''],['yard',''],['industrial',''],['center','jacket'],['glass','jacket'],['market','bike'],['market',''],['center',''],['yard','']];
  const [district,item]=scenes[art]||scenes[0];const image=items[item]||transport[item]||'';
  return `<div class="incident-illustration" style="--incident-bg:url('${backgrounds[district]}')">${image?`<img src="${image}" alt="">`:''}</div>`;
}
function incidentModal(s) {
  const active=s.recentIncident,item=incidents.find(x=>x.id===active?.id)||active;
  if(!item)return '';
  return `<div class="modal-scrim"><div class="modal incident-modal" role="dialog" aria-modal="true" aria-label="Случайное событие">${incidentIllustration(item.art,item.portrait)}<span class="eyebrow">СЛУЧИЛОСЬ ПОСЛЕ ДЕЙСТВИЯ</span><h2>${esc(item.title)}</h2><p>${esc(item.text)}</p><div class="decision-options">${item.choices?.length?item.choices.map((x,i)=>`<button data-incident-choice="${i}" ${x.cost>s.money?'disabled':''}><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(x.text)}</strong></button>`).join(''):'<button data-incident-choice="0"><strong>ПРОДОЛЖИТЬ</strong></button>'}</div></div></div>`;
}
const scoreNames=['Старшая карта','Пара','Две пары','Тройка','Стрит','Флеш','Фул-хаус','Каре','Стрит-флеш'];
const casinoCard=(card,hidden=false)=>`<span class="playing-card ${card&&['♥','♦'].includes(card.suit)?'red':''} ${hidden?'back':''}">${hidden?'◆':cardLabel(card)}</span>`;
function casinoTableModal(s){
  const t=s.casinoTable;if(!t)return '';
  const game=byId(casinoGames,t.id),done=t.phase==='done',button=(label,action,value='',disabled=false)=>`<button type="button" data-casino-action="${action}" data-casino-value="${value}" ${disabled?'disabled':''}>${label}</button>`;
  let body='';
  if(t.id==='roulette')body=`<div class="casino-rival"><img src="${portraits.zoya}" alt=""><div><strong>Крупье Нина</strong><small>Ставки закрываются после выбора. Зеро — отдельный сектор.</small></div></div><div class="roulette-wheel"><span>${t.pocket===null?'?':t.pocket}</span></div>${!done?`<div class="casino-choice-row">${[['КРАСНОЕ','red'],['ЧЁРНОЕ','black'],['ЧЁТНОЕ','even'],['НЕЧЁТНОЕ','odd']].map(([label,id])=>`<button class="${t.selection===id?'chosen':''}" data-casino-action="select" data-casino-value="${id}">${label}</button>`).join('')}</div><div class="roulette-numbers">${Array.from({length:37},(_,i)=>`<button class="${t.selection===`n${i}`?'chosen':''}" data-casino-action="select" data-casino-value="n${i}">${i}</button>`).join('')}</div><p class="table-picked">${t.selection?`Выбрано: ${t.selection[0]==='n'?`число ${t.selection.slice(1)}`:{red:'красное',black:'чёрное',even:'чётное',odd:'нечётное'}[t.selection]}`:'Выбери цвет, чётность или число.'}</p>${button('КРУТИТЬ РУЛЕТКУ','spin','',!t.selection)}`:''}`;
  const seats=t.opponents?`<div class="casino-seats">${t.opponents.map((o,i)=>`<div class="casino-seat ${o.folded?'folded':''}" style="--seat-delay:${i*90}ms"><img src="${portraits[o.portrait]}" alt=""><strong>${esc(o.name)}</strong><small>${esc(done||t.drawn?o.status:o.style)}</small><em>${done?o.hand.map(cardLabel).join(' · '):t.id==='blackjack'?`${cardLabel(o.hand[0])} · ◆`:'◆ ◆ ◆ ◆ ◆'}</em>${done?`<span>${t.id==='blackjack'?blackjackValue(o.hand):o.folded?'СБРОСИЛ':scoreNames[pokerScore(o.hand)[0]]}</span>`:''}</div>`).join('')}</div>`:'';
  if(t.id==='blackjack')body=`<div class="casino-rival"><img src="${portraits.zoya}" alt=""><div><strong>Крупье Нина</strong><small>Три соперника играют против крупье вместе с тобой.</small></div></div><small class="table-label">КРУПЬЕ ${done?blackjackValue(t.rival):'?'}</small><div class="playing-hand">${t.rival.map((c,i)=>casinoCard(c,!done&&i>0)).join('')}</div>${seats}<small class="table-label">ТВОИ КАРТЫ · ${blackjackValue(t.player)}</small><div class="playing-hand">${t.player.map(c=>casinoCard(c)).join('')}</div>${!done?`<div class="table-actions">${button('ВЗЯТЬ КАРТУ','hit')}${button('ОСТАНОВИТЬСЯ','stand')}${button('УДВОИТЬ','double','',s.money<t.stake||casinoRemaining(s)<t.stake)}</div>`:''}`;
  if(t.id==='poker')body=`<div class="table-pot">ОБЩИЙ БАНК · ${money(t.pot)}</div>${seats}<small class="table-label">ТВОЯ РУКА · ${scoreNames[pokerScore(t.player)[0]]}</small><div class="playing-hand">${t.player.map((c,i)=>!done&&!t.drawn?`<button class="card-select ${t.selected.includes(i)?'selected':''}" data-casino-action="toggle" data-casino-value="${i}">${casinoCard(c)}<small>${t.selected.includes(i)?'ЗАМЕНИТЬ':'ОСТАВИТЬ'}</small></button>`:casinoCard(c)).join('')}</div>${!done?(t.drawn?`<div class="table-actions">${button('ОТКРЫТЬ КАРТЫ','showdown')}${button(`ПОВЫСИТЬ +${money(t.stake)}`,'raise','',s.money<t.stake||casinoRemaining(s)<t.stake)}${button('СБРОСИТЬ','fold')}</div>`:`<p class="table-picked">Отметь до трёх карт для замены. Можно оставить все.</p>${button('ОБМЕНЯТЬ / ПРОДОЛЖИТЬ','draw')}`):''}`;
  return `<div class="modal-scrim"><div class="modal casino-table-modal ${done?'finished':''}" role="dialog" aria-modal="true" aria-label="${esc(game.name)}" style="--casino-floor:url('${casinoArt.floor}')"><span class="eyebrow">КАЗИНО «ЗЕРО» / ${esc(game.name.toUpperCase())}</span><h2>${esc(game.name)}</h2><div class="table-bank">СТАВКА ${money(t.wager)} · НА РУКАХ ${money(s.money)}</div>${body}${done?`<div class="table-result"><strong>${esc(t.result)}</strong><span>${t.returned>=t.wager?'+':''}${money(t.returned-t.wager)}</span></div>${button('ВЫЙТИ ИЗ-ЗА СТОЛА','close')}`:`<div class="table-forfeit">${button('ПРЕРВАТЬ ПАРТИЮ · СТАВКА ПРОПАДЁТ','close')}</div>`}</div></div>`;
}
function romanceConflictModal(s){
  const c=s.romance?.conflict;if(!c)return '';
  const person=byId(romancePeople,c.partnerId),choices=romanceConflictChoices(s);
  return `<div class="modal-scrim"><div class="modal romance-conflict-modal" role="dialog" aria-modal="true" aria-label="${esc(c.title)}"><div class="romance-conflict-art" style="--romance-atlas:url('${romancePortraitAtlas}');--portrait-pos:${person.portrait*25}%"></div><span class="eyebrow">ЛИЧНАЯ ЖИЗНЬ / ${c.kind==='affair'?'ИЗМЕНА':'ССОРА'}</span><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p><div class="romance-conflict-stats">ДОВЕРИЕ ${s.romance.profiles[c.partnerId]?.rapport||0}/100 · ТВОЙ ОТВЕТ ИЗМЕНИТ ОТНОШЕНИЯ</div><div class="romance-conflict-options">${choices.map((choice,i)=>`<button data-romance-choice="${i}" ${choice.cost>s.money?'disabled':''}><b>0${i+1}</b><span>${esc(choice.text)}</span><small>${choice.cost?money(choice.cost):'БЕЗ РАСХОДА ДЕНЕГ'}</small></button>`).join('')}</div></div></div>`;
}
export function modal(s,mini,dialogueId=null,dialogueResult=null,travelId=null) {
  if(mini)return `<div class="modal-scrim"><div class="modal mini-modal" style="--mini-bg:url('${backgrounds[mini.job.district]}')">${mini.render()}</div></div>`;
  if(s.casinoTable)return casinoTableModal(s);
  if(s.romance?.conflict)return romanceConflictModal(s);
  if(s.recentIncident)return incidentModal(s);
  if(travelId)return travelModal(s,travelId);
  if(s.jailDays>0)return `<div class="modal-scrim"><div class="modal decision-modal jail-modal"><div class="modal-emblem">ЗАДЕРЖАНИЕ</div><span class="eyebrow">ИЗОЛЯТОР / БЕЗ ВИДА НА ГОРОД</span><h2>ТВОЙ СРОК</h2><p>Суд не оценил предприимчивость. Осталось ${s.jailDays} дн. Работать, покупать и ездить нельзя; расходы продолжают списываться.</p><div class="jail-count">${s.jailDays} <small>ДНЕЙ ДО СВОБОДЫ</small></div><button class="primary big" data-action="serve">ОТСИДЕТЬ ДЕНЬ</button><div class="modal-foot">ГОРОД ПОДОЖДЁТ. ПРОЦЕНТЫ — НЕТ.</div></div></div>`;
  if(dialogueId)return dialogueModal(s,dialogueId,dialogueResult);
  if(!s.pending)return '';
  const data=events.find(x=>x.id===s.pending.id);
  if(!data)return '';
  return `<div class="modal-scrim"><div class="modal decision-modal"><div class="modal-emblem">СОБЫТИЕ</div><span class="eyebrow">ГОРОД НЕ СПРАШИВАЕТ</span><h2>${esc(data.title)}</h2><p>${esc(data.text)}</p><div class="decision-options">${data.choices.map((c,i)=>`<button data-choice="${i}" ${c.cost>s.money?'disabled':''}><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(c.text)}</strong>${c.cost?`<small>− ${money(c.cost)}</small>`:''}</button>`).join('')}</div><div class="modal-foot">РЕШЕНИЕ ОСТАНЕТСЯ С ТОБОЙ</div></div></div>`;
}
export function menuModal(s) {return `<div class="modal-scrim dismissable"><div class="modal menu-modal"><button class="close-modal" data-action="close-menu">×</button><span class="eyebrow">ТЕХНИЧЕСКАЯ ПАПКА</span><h2>Сохранение</h2><p>Прогресс сохраняется в этом браузере после каждого действия. Можно перенести его файлом.</p><div class="menu-actions">${b('СОХРАНИТЬ СЕЙЧАС','save','','','primary')}${b('ЭКСПОРТ JSON','export')}${b('ИМПОРТ JSON','import')}${b('НОВАЯ ИГРА','reset')}</div><p class="menu-note">Версия сохранения: ${s.version}. Офлайн-доход учитывается за семь игровых дней максимум.</p><input id="import-file" type="file" accept="application/json,.json" hidden></div></div>`;}





