import test from 'node:test';import assert from 'node:assert/strict';
import {freshState} from '../src/systems/state.js';import {GameEngine} from '../src/systems/engine.js';import {dailyVitals} from '../src/systems/lifestyle.js';import {moveHome,housingDay} from '../src/systems/housing.js';import {events} from '../src/data/events.js';import {eventEligible} from '../src/data/contextEvents.js';import {shell} from '../src/ui/views.js';
globalThis.localStorage={setItem(){}};
function employed(){const s=freshState();s.money=500000;s.stats.health=95;s.stats.mood=85;s.stats.appeal=85;const g=new GameEngine(s,()=>.99);g.hire('janitor');moveHome(s,'room');return {s,g};}
test('animated skip waits for ordinary choices then resumes the same planned period',()=>{const {s,g}=employed();g.startTimeSkip('career','janitor',1,'expired');assert.equal(s.day,1);g.advanceTimeSkip();s.pending={type:'event',id:'bonus'};g.advanceTimeSkip();assert.equal(s.day,2);assert.ok(s.activeSkip);g.resolveChoice(1);g.advanceTimeSkip();assert.equal(s.day,3);assert.equal(s.activeSkip.planned,30);assert.equal(s.activeSkip.worked,2);});
test('animated skip finishes when employment ends and preserves its earned balance',()=>{const {s,g}=employed();g.startTimeSkip('career','janitor',1,'basic');g.advanceTimeSkip();g.state.employment=null;g.advanceTimeSkip();assert.equal(s.activeSkip,null);assert.match(s.timeSkip.stop,/Работа/);assert.equal(s.timeSkip.worked,1);});
test('animated skip finishes on insufficient food money, without stealing another day',()=>{const {s,g}=employed();g.startTimeSkip('career','janitor',1,'elite');s.money=0;g.advanceTimeSkip();assert.equal(s.day,1);assert.equal(s.activeSkip,null);assert.match(s.timeSkip.stop,/денег/);});
test('time skip food selection survives navigation and save data',()=>{const {s,g}=employed();g.chooseSkipDiet('expired');assert.equal(s.skipDiet,'expired');const html=shell(s,'work','home',null,'career');assert.match(html,/<option value="expired" selected/);});
test('new host owns the free sofa and a quarrel with Valera cannot evict the player',()=>{const s=freshState();assert.ok(s.social.sergey?.met);s.social.valera.score=-50;housingDay(s,()=>.99);assert.equal(s.home,'sofa');s.social.sergey.score=-50;housingDay(s,()=>.99);assert.equal(s.home,'station');assert.match(shell(s,'life','home',null),/ТЕКУЩИЙ НОЧЛЕГ.*Ночлег на вокзале/s);});
test('empty nutrition worsens health; prolonged fasting can cause collapse and death',()=>{const s=freshState();s.stats.health=95;s.vitals.nutrition=0;dailyVitals(s,()=>.99);assert.ok(s.stats.health<90);s.day=3;dailyVitals(s,()=>0);assert.match(s.recentIncident?.title||'',/сознание/);s.recentIncident=null;s.stats.health=90;s.vitals.unfedDays=6;s.day=8;dailyVitals(s,()=>0);assert.equal(s.death?.cause,'Истощение от голода');});
test('manual meals reset fasting and food during skipping prevents starvation',()=>{const s=freshState(),g=new GameEngine(s,()=>.99);s.vitals.unfedDays=4;s.money=1000;g.setDiet('basic');assert.equal(s.vitals.unfedDays,0);dailyVitals(s,()=>0,{fed:true});assert.equal(s.vitals.unfedDays,0);assert.equal(s.death,null);});
test('diary comes last and contains all character parameters while HUD has three vital stats',()=>{const s=freshState();const html=shell(s,'story','home',null);assert.ok(html.indexOf('data-tab="life"')<html.indexOf('data-tab="story"'));assert.match(html,/ЛИЧНОЕ ДЕЛО/);assert.match(html,/Иммунитет|ИММУНИТЕТ/);const hud=html.match(/<div class="side-section"><h3>СОСТОЯНИЕ[\s\S]*?<\/div><div class="side-section traits/)[0];assert.doesNotMatch(hud,/НАСТР\.|СТР\./);});
test('vehicle bragging event is impossible without owned car, and has meaningful alternatives',()=>{const s=freshState();s.day=100;const e=events.find(x=>x.id==='date');assert.equal(eventEligible(s,e),false);s.vehicle='sedan';assert.equal(eventEligible(s,e),true);});
test('several ordinary events leave the original salary date and skip target intact',()=>{const {s,g}=employed();g.startTimeSkip('career','janitor',1,'basic');for(let i=0;i<30;i++){if([4,12,21].includes(i)){s.pending={type:'event',id:'bonus'};g.advanceTimeSkip();assert.ok(s.activeSkip);g.resolveChoice(1);}g.advanceTimeSkip();}assert.equal(s.day,31);assert.equal(s.timeSkip.worked,30);assert.ok(s.timeSkip.earned>0);assert.equal(s.employment.nextPay,61);});
test('Valera opens a real paid shift while Sergey remains the separate host',()=>{const s=freshState(),g=new GameEngine(s,()=>.99);assert.equal(g.jobReady('garage-help').ok,false);assert.equal(g.person('valera','talk',0).ok,true);assert.equal(g.jobReady('garage-help').ok,true);assert.match(shell(s,'work','home',null),/Помочь в гараже Валеры/);assert.ok(s.social.sergey.met);});
test('past crimes can have delayed consequences and an unpaid sentence stops a running activity',()=>{const {s,g}=employed();s.criminalCases=[{name:'Чужая посылка',day:1,due:2,expires:100,fine:5000,jail:4,risk:1}];g.startTimeSkip('career','janitor',1,'basic');g.advanceTimeSkip();assert.match(s.recentIncident.text,/Чужая посылка/);assert.ok(s.activeSkip);g.resolveIncident(1);g.advanceTimeSkip();assert.equal(s.jailDays,4);assert.equal(s.activeSkip,null);assert.match(s.timeSkip.stop,/Заключение/);});
