import test from 'node:test';import assert from 'node:assert/strict';import {freshState} from '../src/systems/state.js';import {GameEngine} from '../src/systems/engine.js';import {routineDay,salaryFor} from '../src/systems/routine.js';import {careers} from '../src/data/lifestyle.js';import {shell} from '../src/ui/views.js';import {incidentEligible,incidents} from '../src/data/incidents.js';import {moveHome} from '../src/systems/housing.js';import {jobEncounters} from '../src/data/jobEncounters.js';
globalThis.localStorage={setItem(){}};
test('full scheduled months pay the quoted salary across different weekday counts',()=>{const s=freshState(),g=new GameEngine(s,()=>.99);s.stats.health=95;s.stats.mood=85;s.stats.appeal=85;s.money=500000;g.hire('janitor');for(let day=2;day<=121;day++){s.day=day;routineDay(s,()=>.99);}const pay=s.ledger.filter(x=>x.category==='Зарплата');assert.equal(pay.length,4);assert.ok(pay.every(x=>x.amount===salaryFor(s,careers[0])));});
test('an owner without employment starts business duties after waking at seven',()=>{const s=freshState();s.day=2;s.businesses.stall={level:1,staff:false,condition:100};routineDay(s,()=>.99);assert.equal(s.lastRoutine.hours,15);});
test('garage shift is shown only after a real referral',()=>{const s=freshState(),g=new GameEngine(s,()=>.99);assert.doesNotMatch(shell(s,'work','home',null),/Помочь в гараже Валеры/);g.person('valera','talk',0);assert.match(shell(s,'work','home',null),/Помочь в гараже Валеры/);});
test('a scrap shift cannot draw parcel delivery, checkout or office incidents',()=>{const s=freshState();s.lastJob={id:'scrap',day:2};s.day=2;for(const id of ['box','shortchange','late-client','unexpected-audit'])assert.equal(incidentEligible(s,incidents.find(x=>x.id===id)),false,id);s.lastJob.id='courier';assert.equal(incidentEligible(s,incidents.find(x=>x.id==='box')),true);});
test('post-shift encounters concern the actual completed task and include tangible choices',()=>{assert.ok(jobEncounters.length>=20);for(const e of jobEncounters){assert.ok(e.jobs.length);assert.ok(e.choices.some(c=>!c.cost));const s=freshState();s.lastJob={id:e.jobs[0],day:2};s.day=2;assert.equal(incidentEligible(s,e),true);s.lastJob.id='unrelated';assert.equal(incidentEligible(s,e),false);}});
test('a sick leave day preserves the contract, consumes its scheduled day and does not earn an absent shift',()=>{const s=freshState(),g=new GameEngine(s,()=>.99);s.money=500000;g.hire('janitor');assert.equal(g.requestLeave().ok,true);moveHome(s,'room');g.activity('sleep');assert.equal(s.day,2);assert.equal(s.hour,7);assert.equal(s.employment.worked,0);assert.equal(s.employment.accrued,0);assert.ok(s.employment);assert.equal(g.requestLeave().ok,false);});
test('the daily planner reports existing commitments, available time and real payment dates',()=>{const s=freshState(),g=new GameEngine(s,()=>.99);s.money=50000;g.hire('janitor');moveHome(s,'room');assert.match(shell(s,'story','home',null),/ПЛАН ДНЯ/);assert.match(shell(s,'story','home',null),/день 31/);assert.match(shell(s,'story','home',null),/БЛИЖАЙШИЕ ПЛАТЕЖИ/);});

test('office shifts can draw their own contextual task encounters',()=>{const s=freshState(),g=new GameEngine(s,()=>.99);s.lastJob={id:'showing',day:s.day};g.rng=()=>0;const e=g.maybeIncident('office',1);assert.ok(e);const poolSeen=new Set();for(let i=0;i<50;i++){s.recentIncident=null;s.incidentHistory=[];g.rng=()=>i/50;const picked=g.maybeIncident('office',1);if(picked)poolSeen.add(picked.id);}assert.ok([...poolSeen].some(id=>id.startsWith('shift-encounter-')));});
