package ru.filemaster.offline;

import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.ContentValues;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.provider.MediaStore;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.tom_roush.pdfbox.android.PDFBoxResourceLoader;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends AppCompatActivity {
    private static final int PICK_FILES = 1001, PICK_ONE = 1002, DRAW_SIGNATURE = 1003, CAMERA_CAPTURE = 1004, MANUAL_CROP = 1005;
    private static final int BG = Color.rgb(247, 248, 252), TEXT = Color.rgb(25, 28, 36), MUTED = Color.rgb(93, 99, 112), BLUE = Color.rgb(49, 87, 213), GREEN = Color.rgb(0, 150, 112);

    private final ExecutorService worker = Executors.newSingleThreadExecutor();
    private String action = "";
    private Uri pendingPdf, pendingCryptoPdf, cameraUri;
    private boolean categoryOpen = false;

    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        PDFBoxResourceLoader.init(getApplicationContext());
        WindowCompat.setDecorFitsSystemWindows(getWindow(), false);
        renderHome();
        Intent incoming = getIntent();
        if (Intent.ACTION_VIEW.equals(incoming.getAction()) && incoming.getData() != null) {
            pendingPdf = incoming.getData(); showPdfQuickActions(pendingPdf);
        }
    }

    @Override protected void onResume() { super.onResume(); if (!categoryOpen && getWindow().getDecorView().isAttachedToWindow()) renderHome(); }

    private void renderHome() {
        categoryOpen = false;
        ScrollView scroll = baseScroll(); LinearLayout root = contentRoot(); scroll.addView(root);
        LinearLayout hero = new LinearLayout(this); hero.setOrientation(LinearLayout.VERTICAL); hero.setPadding(dp(20),dp(20),dp(20),dp(20)); hero.setBackground(gradient(new int[]{Color.rgb(42,76,194),Color.rgb(91,111,232)},dp(22))); hero.setElevation(dp(2));
        root.addView(hero, marginParams(0,0,0,18)); hero.addView(text("ФайлМастер",30,Color.WHITE,true));
        TextView tagline=text("PDF, документы, сканы, фото, таблицы и архивы — полностью локально",15,Color.rgb(234,238,255),false); tagline.setPadding(0,dp(5),0,dp(14)); hero.addView(tagline);
        TextView offline=text("✓  Офлайн   •   без регистрации   •   файлы не покидают телефон",13,Color.WHITE,true); offline.setPadding(dp(12),dp(9),dp(12),dp(9)); GradientDrawable off=rounded(Color.argb(42,255,255,255),dp(12)); off.setStroke(dp(1),Color.argb(70,255,255,255)); offline.setBackground(off); hero.addView(offline);

        root.addView(section("Быстрые действия","Самое нужное — в один тап"));
        root.addView(quickRow(quick("Сканировать","4 угла • несколько страниц",v->startActivity(new Intent(this,ScanSessionActivity.class))), quick("Объединить PDF","Несколько → один",v->pick(true,"application/pdf","merge_pdf"))));
        root.addView(quickRow(quick("Подписать PDF","Пальцем",v->pick(false,"application/pdf","sign_pdf")), quick("Создать ZIP","Несколько файлов",v->pick(true,"*/*","zip"))));
        root.addView(quickRow(quick("Редактировать PDF","Ручка и маркер",v->pick(false,"application/pdf","annotate_pdf")), quick("Мои файлы","Поиск и сортировка",v->startActivity(new Intent(this,ResultsActivity.class)))));
        addRecent(root);

        root.addView(section("Все инструменты","Полный набор по категориям"));
        root.addView(category("PDF","PDF","Редактор, формы, Office, batch и защита","31 инструмент",Color.rgb(235,239,255),BLUE,v->renderCategory("pdf")));
        root.addView(category("SCAN","Сканер и OCR","4 угла, камера, галерея и OCR","6 инструментов",Color.rgb(231,249,244),GREEN,v->renderCategory("scan")));
        root.addView(category("SIGN","Подписи PDF","Рукописная и электронная подпись","3 инструмента",Color.rgb(255,244,227),Color.rgb(199,116,0),v->renderCategory("sign")));
        root.addView(category("DOC","Документы и текст","Word, ODT, TXT, HTML, Markdown","8 инструментов",Color.rgb(236,245,255),Color.rgb(28,105,184),v->renderCategory("docs")));
        root.addView(category("XLS","Таблицы","Все листы, CSV, PDF и формулы","6 инструментов",Color.rgb(232,248,238),Color.rgb(36,132,72),v->renderCategory("sheets")));
        root.addView(category("PPT","Презентации","PPTX ↔ PDF/TXT","2 инструмента",Color.rgb(255,239,231),Color.rgb(204,83,26),v->renderCategory("slides")));
        root.addView(category("IMG","Изображения","Convert, batch, watermark, metadata","13 инструментов",Color.rgb(245,237,255),Color.rgb(126,68,187),v->renderCategory("images")));
        root.addView(category("ZIP","Архиватор","ZIP, 7Z, RAR, TAR и пароли","8 инструментов",Color.rgb(241,243,246),Color.rgb(82,91,107),v->renderCategory("archives")));
        TextView allFiles=text("Открыть файловый менеджер ФайлМастер",14,BLUE,true); allFiles.setGravity(Gravity.CENTER); allFiles.setPadding(dp(10),dp(14),dp(10),dp(8)); allFiles.setOnClickListener(v->startActivity(new Intent(this,ResultsActivity.class))); root.addView(allFiles);
        TextView about=text("О приложении и приватности",14,BLUE,true); about.setGravity(Gravity.CENTER); about.setPadding(dp(10),dp(12),dp(10),dp(18)); about.setOnClickListener(v->showAbout()); root.addView(about);
        setContentView(scroll);
    }

    private void addRecent(LinearLayout root) {
        List<RecentStore.Entry> recent=RecentStore.list(this); if(recent.isEmpty())return;
        LinearLayout titleRow=new LinearLayout(this); titleRow.setGravity(Gravity.CENTER_VERTICAL); titleRow.addView(section("Недавние файлы","Последние результаты"),new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));
        TextView clear=text("Очистить",13,BLUE,true); clear.setPadding(dp(8),dp(14),0,dp(8)); clear.setOnClickListener(v->{RecentStore.clear(this);renderHome();}); titleRow.addView(clear); root.addView(titleRow);
        for(int i=0;i<Math.min(4,recent.size());i++)root.addView(recentRow(recent.get(i)));
    }

    private View recentRow(RecentStore.Entry e){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.HORIZONTAL);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(14),dp(12),dp(12),dp(12));GradientDrawable bg=rounded(Color.WHITE,dp(15));bg.setStroke(dp(1),Color.rgb(231,233,240));box.setBackground(bg);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.addView(text(e.name.isBlank()?"Файл":e.name,15,TEXT,true));c.addView(text(e.mime.isBlank()?"Результат":e.mime,12,MUTED,false));box.addView(c,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));box.addView(text("⋮",26,BLUE,true),new LinearLayout.LayoutParams(dp(42),dp(46)));box.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(e.name).setItems(new String[]{"Открыть","Поделиться"},(d,w)->{if(w==0)openResult(e.uri);else shareResult(e.uri);}).show());box.setLayoutParams(marginParams(0,0,0,8));return box;}

    private void renderCategory(String id){categoryOpen=true;ScrollView scroll=baseScroll();LinearLayout root=contentRoot();scroll.addView(root);String title,sub;switch(id){case"scan"->{title="Сканер и OCR";sub="Камера, 4 угла, перспектива и распознавание";}case"sign"->{title="Подписи PDF";sub="Рукописная и электронная подпись";}case"docs"->{title="Документы и текст";sub="Word, ODT, TXT, HTML, Markdown и RTF";}case"sheets"->{title="Таблицы";sub="XLSX, CSV, все листы и формулы";}case"slides"->{title="Презентации";sub="PPTX и PDF";}case"images"->{title="Изображения";sub="Конвертация, batch, watermark и privacy";}case"archives"->{title="Архиватор";sub="Создание, просмотр и распаковка";}default->{title="PDF";sub="Редактор, Office, формы, batch и защита";}}
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView back=text("←",30,TEXT,false);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->renderHome());top.addView(back,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(text(title,27,TEXT,true));names.addView(text(sub,14,MUTED,false));top.addView(names,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));root.addView(top);
        TextView local=text("✓  Все операции выполняются на устройстве",13,GREEN,true);local.setPadding(dp(12),dp(9),dp(12),dp(9));local.setBackground(rounded(Color.rgb(233,249,244),dp(12)));root.addView(local,marginParams(0,0,0,16));
        switch(id){case"scan"->addScanTools(root);case"sign"->addSignTools(root);case"docs"->addDocumentTools(root);case"sheets"->addSheetTools(root);case"slides"->addPresentationTools(root);case"images"->addImageTools(root);case"archives"->addArchiveTools(root);default->addPdfTools(root);}setContentView(scroll);
    }

    private void addScanTools(LinearLayout r){r.addView(tool("Многостраничный скан с 4 углами","Каждая страница → перспектива → один PDF",v->startActivity(new Intent(this,ScanSessionActivity.class))));r.addView(tool("Исправить перспективу готового фото","Вручную выставить четыре угла",v->pick(false,"image/*","manual_crop_image")));r.addView(tool("Быстрый скан одной страницы","Автообрезка и PDF",v->captureScan()));r.addView(tool("Улучшить фото документа","Автообрезка, Ч/Б и контраст",v->pick(false,"image/*","scan_photo")));r.addView(tool("OCR фото RU + EN","Фото → TXT",v->pick(false,"image/*","ocr")));r.addView(tool("OCR целого PDF RU + EN","Все страницы → TXT",v->pick(false,"application/pdf","ocr_pdf")));}

    private void addPdfTools(LinearLayout r){
        r.addView(section("Редактор и формы",null));r.addView(tool("Ручка / маркер по PDF","Рисование пальцем",v->pick(false,"application/pdf","annotate_pdf")));r.addView(tool("Надёжно скрыть область","Разрушительное удаление данных",v->pick(false,"application/pdf","redact_pdf")));r.addView(tool("Заполнить PDF-форму","Текст, флажки, радиокнопки и списки",v->pick(false,"application/pdf","fill_pdf_form")));
        r.addView(section("PDF → Office",null));r.addView(tool("PDF → DOCX","Редактируемый текст с разрывами страниц",v->pick(false,"application/pdf","pdf_docx")));r.addView(tool("PDF → XLSX","Эвристическое разбиение строк и колонок",v->pick(false,"application/pdf","pdf_xlsx")));r.addView(tool("PDF → PPTX","Каждая страница как визуально точный слайд",v->pick(false,"application/pdf","pdf_pptx")));
        r.addView(section("Страницы и конвертация",null));r.addView(tool("Объединить PDF","Склеить несколько PDF",v->pick(true,"application/pdf","merge_pdf")));r.addView(tool("Разделить PDF","Каждая страница отдельно",v->pick(false,"application/pdf","split_pdf")));r.addView(tool("Извлечь страницы","Например: 1,3,5-8",v->pick(false,"application/pdf","extract_pages")));r.addView(tool("Удалить страницы","Номера или диапазоны",v->pick(false,"application/pdf","remove_pages")));r.addView(tool("Повернуть на 90°","Все страницы",v->pick(false,"application/pdf","rotate_pdf")));r.addView(tool("Обратный порядок","Последняя станет первой",v->pick(false,"application/pdf","reverse_pdf")));r.addView(tool("Добавить номера страниц","По центру снизу",v->pick(false,"application/pdf","page_numbers")));r.addView(tool("Обрезать поля PDF","Одинаковый процент со всех сторон",v->pick(false,"application/pdf","crop_pdf")));r.addView(tool("Извлечь встроенные изображения","Картинки из PDF → PNG",v->pick(false,"application/pdf","extract_pdf_images")));r.addView(tool("Фото → PDF","Несколько изображений",v->pick(true,"image/*","images_pdf")));r.addView(tool("PDF → JPG","Все страницы",v->pick(false,"application/pdf","pdf_jpg")));r.addView(tool("PDF → TXT","Встроенный текст",v->pick(false,"application/pdf","pdf_text")));
        r.addView(section("Обработка и защита",null));r.addView(tool("Сжать PDF","Три уровня",v->pick(false,"application/pdf","compress_pdf")));r.addView(tool("Пересобрать / восстановить","Повторно сохранить структуру",v->pick(false,"application/pdf","repair_pdf")));r.addView(tool("Водяной знак","Текст на каждой странице",v->pick(false,"application/pdf","watermark_pdf")));r.addView(tool("Очистить метаданные","Свойства и XMP",v->pick(false,"application/pdf","clean_metadata")));r.addView(tool("Сравнить два PDF","Отчёт различий",v->pick(true,"application/pdf","compare_pdf")));r.addView(tool("Защитить паролем","Локальное шифрование",v->pick(false,"application/pdf","protect_pdf")));r.addView(tool("Снять известный пароль","Нужен действующий пароль",v->pick(false,"application/pdf","unlock_pdf")));
        r.addView(section("Пакетно",null));r.addView(tool("Сжать несколько PDF","Один режим для выбранных файлов",v->pick(true,"application/pdf","batch_pdf_compress")));r.addView(tool("Водяной знак на несколько PDF","Один текст для всех",v->pick(true,"application/pdf","batch_pdf_watermark")));r.addView(tool("Очистить метаданные нескольких","Пакетная privacy-очистка",v->pick(true,"application/pdf","batch_pdf_clean")));r.addView(tool("Несколько PDF → JPG","Экспорт страниц всех файлов",v->pick(true,"application/pdf","batch_pdf_jpg")));r.addView(tool("OCR нескольких PDF","Отдельный TXT для каждого",v->pick(true,"application/pdf","batch_pdf_ocr")));r.addView(tool("Защитить несколько PDF","Один пароль для всех",v->pick(true,"application/pdf","batch_pdf_protect")));
    }

    private void addSignTools(LinearLayout r){r.addView(tool("Рукописная подпись","Нарисовать пальцем",v->pick(false,"application/pdf","sign_pdf")));r.addView(tool("Электронная подпись PKCS#12",".p12/.pfx + пароль → CMS/PKCS#7",v->pick(false,"application/pdf","crypto_sign_pdf")));r.addView(tool("Проверить электронные подписи","Локальная криптографическая проверка",v->pick(false,"application/pdf","verify_signatures")));}
    private void addDocumentTools(LinearLayout r){r.addView(tool("DOCX → TXT","Извлечь текст Word",v->pick(false,"application/vnd.openxmlformats-officedocument.wordprocessingml.document","docx_txt")));r.addView(tool("DOCX → PDF","Текстовый экспорт",v->pick(false,"application/vnd.openxmlformats-officedocument.wordprocessingml.document","docx_pdf")));r.addView(tool("ODT → TXT","Извлечь текст",v->pick(false,"application/vnd.oasis.opendocument.text","odt_txt")));r.addView(tool("ODT → PDF","Текстовый экспорт",v->pick(false,"application/vnd.oasis.opendocument.text","odt_pdf")));r.addView(tool("TXT / HTML / Markdown / RTF → PDF","Создать PDF",v->pick(false,"*/*","text_pdf")));r.addView(tool("HTML / Markdown / RTF → TXT","Очистить разметку",v->pick(false,"*/*","text_txt")));r.addView(tool("TXT / Markdown / HTML → DOCX","Создать Word",v->pick(false,"*/*","text_docx")));r.addView(tool("TXT / Markdown / HTML → ODT","Создать ODT",v->pick(false,"*/*","text_odt")));}
    private void addPresentationTools(LinearLayout r){r.addView(tool("PPTX → TXT","Текст по слайдам",v->pick(false,"application/vnd.openxmlformats-officedocument.presentationml.presentation","pptx_txt")));r.addView(tool("PPTX → PDF","Текст слайдов → PDF",v->pick(false,"application/vnd.openxmlformats-officedocument.presentationml.presentation","pptx_pdf")));}
    private void addSheetTools(LinearLayout r){r.addView(tool("XLSX → CSV","Первый лист",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_csv")));r.addView(tool("Все листы XLSX → CSV","Каждый лист в отдельный CSV",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_all_csv")));r.addView(tool("XLSX → PDF","Первый лист",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_pdf")));r.addView(tool("Все листы XLSX → PDF","Один PDF со всеми листами",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_all_pdf")));r.addView(tool("CSV / TSV → XLSX","Авторазделитель",v->pick(false,"*/*","csv_xlsx")));r.addView(tool("Отчёт XLSX","Листы, строки, ячейки и формулы",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_report")));}
    private void addImageTools(LinearLayout r){r.addView(section("Один файл",null));r.addView(tool("Сжать изображение","JPEG 78%",v->pick(false,"image/*","image_compress")));r.addView(tool("Изменить размер","Максимальная сторона",v->pick(false,"image/*","image_resize")));r.addView(tool("Обрезать края","Процент со всех сторон",v->pick(false,"image/*","image_crop")));r.addView(tool("Повернуть на 90°","Новая копия",v->pick(false,"image/*","image_rotate")));r.addView(tool("Отразить по горизонтали","Зеркальная копия",v->pick(false,"image/*","image_flip")));r.addView(tool("Сделать Ч/Б","Оттенки серого",v->pick(false,"image/*","image_gray")));r.addView(tool("Водяной знак","Текст снизу справа",v->pick(false,"image/*","image_watermark")));r.addView(tool("Удалить метаданные / EXIF","Полная декодировка и новая кодировка",v->pick(false,"image/*","image_strip_metadata")));r.addView(tool("Конвертировать JPG / PNG / WebP","Выходной формат",v->pick(false,"image/*","image_convert")));r.addView(section("Пакетно",null));r.addView(tool("Сжать несколько","JPEG 78%",v->pick(true,"image/*","image_batch_compress")));r.addView(tool("Конвертировать несколько","JPG / PNG / WebP",v->pick(true,"image/*","image_batch_convert")));r.addView(tool("Водяной знак на несколько","Один текст для всех",v->pick(true,"image/*","image_batch_watermark")));r.addView(tool("Очистить метаданные нескольких","Privacy batch",v->pick(true,"image/*","image_batch_strip_metadata")));}
    private void addArchiveTools(LinearLayout r){r.addView(tool("Посмотреть ZIP / 7Z / RAR","Список без распаковки",v->pick(false,"*/*","archive_list")));r.addView(section("Создать",null));r.addView(tool("Создать ZIP","Несколько файлов",v->pick(true,"*/*","zip")));r.addView(tool("ZIP с паролем AES-256","Защищённый архив",v->pick(true,"*/*","zip_password")));r.addView(tool("Создать 7Z","LZMA2",v->pick(true,"*/*","7z")));r.addView(tool("Создать TAR.GZ","gzip-архив",v->pick(true,"*/*","targz")));r.addView(section("Распаковать",null));r.addView(tool("ZIP / 7Z / RAR","В Загрузки/ФайлМастер",v->pick(false,"*/*","extract")));r.addView(tool("ZIP с паролем","AES/ZipCrypto",v->pick(false,"application/zip","extract_zip_password")));r.addView(tool("TAR / GZ / BZ2 / XZ","Также TAR.GZ/BZ2/XZ",v->pick(false,"*/*","extract_extra")));}

    private void captureScan(){try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"Скан_исходник_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");v.put(MediaStore.Images.Media.RELATIVE_PATH,Environment.DIRECTORY_PICTURES+"/ФайлМастер/Сканы");cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(cameraUri==null)throw new IllegalStateException("Не удалось подготовить файл для камеры");Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);if(i.resolveActivity(getPackageManager())==null)throw new IllegalStateException("На устройстве не найдено приложение камеры");startActivityForResult(i,CAMERA_CAPTURE);}catch(Exception e){showError(e);}}
    private void pick(boolean multi,String mime,String next){action=next;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,multi);startActivityForResult(i,multi?PICK_FILES:PICK_ONE);}

    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);
        if(requestCode==CAMERA_CAPTURE){if(resultCode==RESULT_OK&&cameraUri!=null){Uri raw=cameraUri;runTask("Улучшаю скан и создаю PDF…",()->{Uri enhanced=ImageTools.enhanceDocument(this,raw);List<Uri> one=new ArrayList<>();one.add(enhanced);PdfTools.imagesToPdf(this,one);try{getContentResolver().delete(raw,null,null);}catch(Exception ignored){}return enhanced;},"Скан сохранён как JPG и PDF");}else if(cameraUri!=null)try{getContentResolver().delete(cameraUri,null,null);}catch(Exception ignored){}cameraUri=null;return;}
        if(requestCode==MANUAL_CROP){if(resultCode==RESULT_OK&&data!=null){String raw=data.getStringExtra("cropped_uri");if(raw!=null)showSuccess("Перспектива исправлена",Uri.parse(raw));}return;}
        if(resultCode!=RESULT_OK||data==null)return;
        if(requestCode==DRAW_SIGNATURE){String path=data.getStringExtra("signature_path");if(path!=null&&pendingPdf!=null){File sig=new File(path);runTask("Добавляю подпись…",()->PdfTools.addVisibleSignature(this,pendingPdf,sig),"Подписанный PDF сохранён");}return;}
        List<Uri> uris=collectUris(data);if(uris.isEmpty())return;Uri first=uris.get(0);
        try{switch(action){
            case"manual_crop_image"->{Intent c=new Intent(this,ManualCropActivity.class);c.putExtra("image_uri",first.toString());startActivityForResult(c,MANUAL_CROP);}
            case"annotate_pdf"->launchPagedPdfActivity(first,PdfAnnotateActivity.class,"Номер страницы для рисования");
            case"redact_pdf"->launchPagedPdfActivity(first,PdfRedactActivity.class,"Номер страницы для скрытия данных");
            case"fill_pdf_form"->{Intent f=new Intent(this,PdfFormActivity.class);f.putExtra("pdf_uri",first.toString());startActivity(f);}
            case"pdf_docx"->runTask("Создаю редактируемый DOCX…",()->PdfOfficeTools.toDocx(this,first),"DOCX сохранён");
            case"pdf_xlsx"->runTask("Распознаю строки и колонки…",()->PdfOfficeTools.toXlsx(this,first),"XLSX сохранён");
            case"pdf_pptx"->runTask("Создаю слайды из страниц…",()->PdfOfficeTools.toPptxVisual(this,first),"PPTX сохранён");
            case"merge_pdf"->runTask("Объединяю PDF…",()->PdfTools.merge(this,uris),"PDF объединён");case"split_pdf"->runTask("Разделяю PDF…",()->PdfTools.split(this,first),"Страницы сохранены");
            case"extract_pages"->ask("Какие страницы извлечь?","Например: 1,3,5-8",false,x->runTask("Извлекаю страницы…",()->PdfTools.extractPages(this,first,x),"Новый PDF создан"));case"remove_pages"->ask("Какие страницы удалить?","Например: 2,4-6",false,x->runTask("Удаляю страницы…",()->PdfTools.removePages(this,first,x),"PDF сохранён"));
            case"rotate_pdf"->runTask("Поворачиваю…",()->PdfTools.rotateAll(this,first,90),"PDF повёрнут");case"reverse_pdf"->runTask("Меняю порядок…",()->PdfTools.reversePages(this,first),"Порядок изменён");case"page_numbers"->runTask("Добавляю номера…",()->PdfTools.addPageNumbers(this,first),"Номера добавлены");
            case"crop_pdf"->ask("Обрезать поля на сколько %?","Например: 5",false,x->{try{float p=Float.parseFloat(x.trim().replace(',','.'));runTask("Обрезаю поля…",()->PdfExtraTools.cropMargins(this,first,p),"PDF обрезан");}catch(Exception e){showError(new IllegalArgumentException("Введите число от 1 до 34"));}});
            case"extract_pdf_images"->runTask("Извлекаю изображения…",()->PdfExtraTools.extractEmbeddedImages(this,first),"Изображения сохранены");case"pdf_text"->runTask("Извлекаю текст…",()->PdfTools.extractText(this,first),"TXT сохранён");case"images_pdf"->runTask("Создаю PDF…",()->PdfTools.imagesToPdf(this,uris),"PDF создан");case"pdf_jpg"->runTask("Экспортирую страницы…",()->PdfTools.pdfToJpeg(this,first),"JPG сохранены");
            case"compress_pdf"->chooseCompression(first);case"repair_pdf"->runTask("Пересобираю PDF…",()->PdfExtraTools.repair(this,first),"Новый PDF сохранён");case"watermark_pdf"->ask("Текст водяного знака","Например: КОПИЯ",false,x->runTask("Добавляю водяной знак…",()->PdfExtraTools.watermark(this,first,x),"Водяной знак добавлен"));case"clean_metadata"->runTask("Удаляю метаданные…",()->PdfExtraTools.removeMetadata(this,first),"PDF очищен");case"compare_pdf"->runTask("Сравниваю PDF…",()->PdfExtraTools.compareText(this,uris),"Отчёт сохранён");case"protect_pdf"->ask("Пароль для PDF","Минимум 4 символа",true,x->runTask("Шифрую PDF…",()->PdfTools.protect(this,first,x),"PDF защищён"));case"unlock_pdf"->ask("Текущий пароль PDF","Введите пароль",true,x->runTask("Снимаю защиту…",()->PdfTools.unlock(this,first,x),"PDF без пароля сохранён"));
            case"batch_pdf_compress"->chooseBatchCompression(uris);case"batch_pdf_watermark"->ask("Текст для всех PDF","Например: КОПИЯ",false,x->runTask("Добавляю знак на PDF…",()->BatchPdfTools.watermark(this,uris,x),"PDF обработаны"));case"batch_pdf_clean"->runTask("Очищаю метаданные…",()->BatchPdfTools.cleanMetadata(this,uris),"PDF очищены");case"batch_pdf_jpg"->runTask("Экспортирую PDF в JPG…",()->BatchPdfTools.toJpg(this,uris),"Страницы экспортированы");case"batch_pdf_ocr"->runTask("Распознаю PDF…",()->BatchPdfTools.ocr(this,uris),"OCR завершён");case"batch_pdf_protect"->ask("Пароль для всех PDF","Минимум 4 символа",true,x->runTask("Защищаю PDF…",()->BatchPdfTools.protect(this,uris,x),"PDF защищены"));
            case"sign_pdf"->{pendingPdf=first;startActivityForResult(new Intent(this,SignatureActivity.class),DRAW_SIGNATURE);}case"crypto_sign_pdf"->{pendingCryptoPdf=first;pick(false,"*/*","crypto_pick_cert");}case"crypto_pick_cert"->{Uri pdf=pendingCryptoPdf;if(pdf==null)throw new IllegalStateException("Сначала выберите PDF");ask("Пароль сертификата","Пароль .p12/.pfx",true,x->runTask("Создаю электронную подпись…",()->DigitalSignatureTools.signPdf(this,pdf,first,x),"Подписанный PDF сохранён"));}case"verify_signatures"->runTask("Проверяю подписи…",()->DigitalSignatureTools.verifyPdf(this,first),"Отчёт сохранён");
            case"ocr"->runOcr(first);case"ocr_pdf"->runTask("Распознаю PDF…",()->OcrTools.recognizePdfToTxt(this,first),"OCR TXT сохранён");case"scan_photo"->runTask("Улучшаю документ…",()->ImageTools.enhanceDocument(this,first),"Скан сохранён");
            case"image_compress"->runTask("Сжимаю изображение…",()->ImageTools.compress(this,first,78),"Сжатая копия сохранена");case"image_batch_compress"->runTask("Сжимаю изображения…",()->ImageTools.compressBatch(this,uris,78),"Изображения сжаты");case"image_rotate"->runTask("Поворачиваю…",()->ImageTools.rotate90(this,first),"Копия сохранена");case"image_flip"->runTask("Отражаю…",()->ImageTools.flipHorizontal(this,first),"Копия сохранена");case"image_gray"->runTask("Делаю Ч/Б…",()->ImageTools.grayscale(this,first),"Ч/Б копия сохранена");
            case"image_crop"->ask("Обрезать края на сколько %?","Например: 10",false,x->{try{int p=Integer.parseInt(x.trim());runTask("Обрезаю…",()->ImageTools.cropMargins(this,first,p),"Копия сохранена");}catch(Exception e){showError(new IllegalArgumentException("Введите число от 1 до 35"));}});case"image_resize"->ask("Максимальная сторона","Например: 1600",false,x->{try{int s=Integer.parseInt(x.trim());if(s<320||s>8000)throw new NumberFormatException();runTask("Меняю размер…",()->ImageTools.resize(this,first,s),"Изображение сохранено");}catch(Exception e){showError(new IllegalArgumentException("Введите число от 320 до 8000"));}});
            case"image_watermark"->ask("Текст водяного знака","Например: © Моё фото",false,x->runTask("Добавляю знак…",()->ImageTools.watermark(this,first,x),"Водяной знак добавлен"));case"image_batch_watermark"->ask("Текст для всех изображений","Например: © Моё фото",false,x->runTask("Добавляю знаки…",()->ImageTools.watermarkBatch(this,uris,x),"Изображения обработаны"));case"image_strip_metadata"->runTask("Удаляю EXIF/XMP…",()->ImageTools.stripMetadata(this,first),"Метаданные удалены");case"image_batch_strip_metadata"->runTask("Очищаю метаданные…",()->ImageTools.stripMetadataBatch(this,uris),"Изображения очищены");case"image_convert"->chooseImageFormat(false,uris);case"image_batch_convert"->chooseImageFormat(true,uris);
            case"docx_txt"->runTask("Извлекаю текст DOCX…",()->DocxTools.toTxt(this,first),"TXT сохранён");case"docx_pdf"->runTask("Создаю PDF…",()->DocxTools.toPdf(this,first),"PDF сохранён");case"odt_txt"->runTask("Извлекаю ODT…",()->OpenDocumentTools.odtToTxt(this,first),"TXT сохранён");case"odt_pdf"->runTask("Создаю PDF…",()->OpenDocumentTools.odtToPdf(this,first),"PDF сохранён");case"text_pdf"->runTask("Создаю PDF…",()->TextTools.toPdf(this,first),"PDF сохранён");case"text_txt"->runTask("Извлекаю текст…",()->TextTools.toTxt(this,first),"TXT сохранён");case"text_docx"->runTask("Создаю DOCX…",()->OfficeCreateTools.textToDocx(this,first),"DOCX сохранён");case"text_odt"->runTask("Создаю ODT…",()->OfficeCreateTools.textToOdt(this,first),"ODT сохранён");case"pptx_txt"->runTask("Извлекаю PPTX…",()->PresentationTools.toTxt(this,first),"TXT сохранён");case"pptx_pdf"->runTask("Создаю PDF…",()->PresentationTools.toPdf(this,first),"PDF сохранён");
            case"xlsx_csv"->runTask("Конвертирую XLSX…",()->SheetTools.xlsxToCsv(this,first),"CSV сохранён");case"xlsx_all_csv"->runTask("Экспортирую все листы…",()->SheetExtraTools.allSheetsToCsv(this,first),"Листы сохранены как CSV");case"xlsx_pdf"->runTask("Создаю PDF…",()->SheetTools.xlsxToPdf(this,first),"PDF сохранён");case"xlsx_all_pdf"->runTask("Создаю PDF всех листов…",()->SheetExtraTools.allSheetsToPdf(this,first),"PDF сохранён");case"csv_xlsx"->runTask("Создаю XLSX…",()->SheetTools.csvToXlsx(this,first),"XLSX сохранён");case"xlsx_report"->runTask("Анализирую XLSX…",()->SheetExtraTools.workbookReport(this,first),"Отчёт сохранён");
            case"archive_list"->runTextTask("Читаю архив…",()->ArchiveTools.listContents(this,first),"Содержимое архива");case"zip"->runTask("Создаю ZIP…",()->ArchiveTools.createZip(this,uris),"ZIP создан");case"zip_password"->ask("Пароль ZIP","AES-256, минимум 4 символа",true,x->runTask("Создаю ZIP…",()->ArchiveTools.createEncryptedZip(this,uris,x),"Защищённый ZIP создан"));case"7z"->runTask("Создаю 7Z…",()->ArchiveTools.create7z(this,uris),"7Z создан");case"targz"->runTask("Создаю TAR.GZ…",()->ArchiveTools.createTarGz(this,uris),"TAR.GZ создан");case"extract"->runTask("Распаковываю…",()->ArchiveTools.extract(this,first),"Архив распакован");case"extract_zip_password"->ask("Пароль ZIP","Введите пароль",true,x->runTask("Распаковываю…",()->ArchiveTools.extractEncryptedZip(this,first,x),"Архив распакован"));case"extract_extra"->runTask("Распаковываю…",()->ArchiveExtraTools.extract(this,first),"Архив распакован");
        }}catch(Exception e){showError(e);}}

    private void launchPagedPdfActivity(Uri uri,Class<?> cls,String title){ask(title,"Например: 1",false,x->{try{int page=Integer.parseInt(x.trim());if(page<1)throw new NumberFormatException();Intent i=new Intent(this,cls);i.putExtra("pdf_uri",uri.toString());i.putExtra("page",page);startActivity(i);}catch(Exception e){showError(new IllegalArgumentException("Введите номер страницы от 1"));}});}
    private void chooseImageFormat(boolean batch,List<Uri> uris){String[] labels={"JPG","PNG","WebP"},formats={"jpg","png","webp"};new AlertDialog.Builder(this).setTitle("Выходной формат").setItems(labels,(d,w)->{if(batch)runTask("Конвертирую изображения…",()->ImageTools.convertBatch(this,uris,formats[w]),"Изображения конвертированы");else runTask("Конвертирую изображение…",()->ImageTools.convert(this,uris.get(0),formats[w]),"Изображение конвертировано");}).setNegativeButton("Отмена",null).show();}
    private void chooseCompression(Uri uri){String[] m={"Сильное — 90 DPI / JPEG 55%","Среднее — 120 DPI / JPEG 70%","Бережное — 150 DPI / JPEG 82%"};new AlertDialog.Builder(this).setTitle("Уровень сжатия").setItems(m,(d,w)->{int dpi=w==0?90:w==1?120:150;float q=w==0?.55f:w==1?.70f:.82f;runTask("Сжимаю PDF…",()->PdfExtraTools.compressRaster(this,uri,dpi,q),"Сжатый PDF сохранён");}).show();}
    private void chooseBatchCompression(List<Uri> uris){String[] m={"Сильное — 90 DPI / 55%","Среднее — 120 DPI / 70%","Бережное — 150 DPI / 82%"};new AlertDialog.Builder(this).setTitle("Сжатие всех выбранных PDF").setItems(m,(d,w)->{int dpi=w==0?90:w==1?120:150;float q=w==0?.55f:w==1?.70f:.82f;runTask("Сжимаю PDF…",()->BatchPdfTools.compress(this,uris,dpi,q),"PDF сжаты");}).show();}

    private void runOcr(Uri uri){ProgressDialog d=ProgressDialog.show(this,"OCR","Распознаю текст на устройстве…",true,false);worker.submit(()->{try{String result=OcrTools.recognize(this,uri);Uri out=FileStore.publishBytes(this,result.getBytes(StandardCharsets.UTF_8),"OCR_"+System.currentTimeMillis()+".txt","text/plain",null);runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle("Распознанный текст").setMessage(result.isBlank()?"Текст не найден":result).setPositiveButton("Готово",null).setNeutralButton("Копировать",(x,w)->copyText(result)).setNegativeButton("Открыть TXT",(x,w)->openResult(out)).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();showError(e);});}});}
    private interface Work{Object run()throws Exception;}private interface TextWork{String run()throws Exception;}private interface InputCallback{void onValue(String v);}
    private void runTask(String label,Work work,String success){ProgressDialog d=ProgressDialog.show(this,"ФайлМастер",label,true,false);worker.submit(()->{try{Object result=work.run();runOnUiThread(()->{d.dismiss();if(result instanceof Uri)showSuccess(success,(Uri)result);else Toast.makeText(this,success+(result instanceof Integer?" ("+result+")":""),Toast.LENGTH_LONG).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();showError(e);});}});}
    private void runTextTask(String label,TextWork work,String title){ProgressDialog d=ProgressDialog.show(this,"ФайлМастер",label,true,false);worker.submit(()->{try{String result=work.run();runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle(title).setMessage(result).setPositiveButton("Закрыть",null).setNeutralButton("Копировать",(x,w)->copyText(result)).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();showError(e);});}});}
    private void showSuccess(String success,Uri uri){new AlertDialog.Builder(this).setTitle("Готово").setMessage(success+"\n\nФайл: Загрузки / ФайлМастер").setPositiveButton("Открыть",(d,w)->openResult(uri)).setNeutralButton("Поделиться",(d,w)->shareResult(uri)).setNegativeButton("Закрыть",null).show();}
    private void openResult(Uri uri){try{String mime=getContentResolver().getType(uri);Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(uri,mime==null?"*/*":mime);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Открыть файл"));}catch(Exception e){Toast.makeText(this,"Файл сохранён, но открыть его не удалось",Toast.LENGTH_LONG).show();}}
    private void shareResult(Uri uri){try{String mime=getContentResolver().getType(uri);Intent i=new Intent(Intent.ACTION_SEND);i.setType(mime==null?"*/*":mime);i.putExtra(Intent.EXTRA_STREAM,uri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Поделиться файлом"));}catch(Exception e){showError(new IllegalStateException("Не удалось открыть меню отправки"));}}
    private void copyText(String value){ClipboardManager c=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("ФайлМастер",value));Toast.makeText(this,"Скопировано",Toast.LENGTH_SHORT).show();}
    private void ask(String title,String hint,boolean password,InputCallback cb){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setPadding(dp(16),dp(10),dp(16),dp(10));if(password)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Продолжить",(d,w)->{String v=e.getText().toString();if(v.isBlank())showError(new IllegalArgumentException("Поле не должно быть пустым"));else cb.onValue(v);}).setNegativeButton("Отмена",null).show();}
    private List<Uri> collectUris(Intent data){List<Uri> list=new ArrayList<>();ClipData c=data.getClipData();if(c!=null)for(int i=0;i<c.getItemCount();i++)list.add(c.getItemAt(i).getUri());else if(data.getData()!=null)list.add(data.getData());return list;}

    private void showPdfQuickActions(Uri uri){new AlertDialog.Builder(this).setTitle("Что сделать с PDF?").setItems(new String[]{"Редактировать / маркер","Скрыть область","Заполнить форму","PDF → DOCX","PDF → PPTX","Подписать пальцем","Электронная подпись","Сжать","PDF → JPG","OCR PDF","Проверить подписи"},(d,w)->{pendingPdf=uri;if(w==0)launchPagedPdfActivity(uri,PdfAnnotateActivity.class,"Страница");else if(w==1)launchPagedPdfActivity(uri,PdfRedactActivity.class,"Страница");else if(w==2){Intent f=new Intent(this,PdfFormActivity.class);f.putExtra("pdf_uri",uri.toString());startActivity(f);}else if(w==3)runTask("Создаю DOCX…",()->PdfOfficeTools.toDocx(this,uri),"DOCX сохранён");else if(w==4)runTask("Создаю PPTX…",()->PdfOfficeTools.toPptxVisual(this,uri),"PPTX сохранён");else if(w==5)startActivityForResult(new Intent(this,SignatureActivity.class),DRAW_SIGNATURE);else if(w==6){pendingCryptoPdf=uri;pick(false,"*/*","crypto_pick_cert");}else if(w==7)chooseCompression(uri);else if(w==8)runTask("Экспортирую…",()->PdfTools.pdfToJpeg(this,uri),"JPG сохранены");else if(w==9)runTask("Распознаю…",()->OcrTools.recognizePdfToTxt(this,uri),"OCR сохранён");else runTask("Проверяю подписи…",()->DigitalSignatureTools.verifyPdf(this,uri),"Отчёт сохранён");}).setNegativeButton("Закрыть",null).show();}
    private void showAbout(){new AlertDialog.Builder(this).setTitle("ФайлМастер").setMessage("Все основные операции выполняются локально на устройстве. OCR русского и английского языков встроен в APK. Файлы не отправляются на сервер.\n\nПоддерживаются PDF, сканы, подписи, DOCX/ODT/PPTX, XLSX/CSV, изображения и архивы.\n\nРезультаты: Загрузки / ФайлМастер").setPositiveButton("Понятно",null).show();}
    private void showError(Exception e){new AlertDialog.Builder(this).setTitle("Не получилось").setMessage(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage()).setPositiveButton("OK",null).show();}

    private ScrollView baseScroll(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(BG);ViewCompat.setOnApplyWindowInsetsListener(s,(v,i)->{Insets safe=i.getInsets(WindowInsetsCompat.Type.systemBars()|WindowInsetsCompat.Type.displayCutout());v.setPadding(0,safe.top,0,safe.bottom);return i;});return s;}
    private LinearLayout contentRoot(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(14),dp(16),dp(28));return r;}
    private View quickRow(View a,View b){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f);x.setMargins(0,0,dp(5),dp(10));LinearLayout.LayoutParams y=new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f);y.setMargins(dp(5),0,0,dp(10));r.addView(a,x);r.addView(b,y);return r;}
    private View quick(String t,String s,View.OnClickListener l){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setMinimumHeight(dp(86));b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(14),dp(14),dp(14),dp(14));GradientDrawable g=rounded(Color.WHITE,dp(17));g.setStroke(dp(1),Color.rgb(230,232,239));b.setBackground(g);b.setOnClickListener(l);b.addView(text(t,16,TEXT,true));b.addView(text(s,13,MUTED,false));return b;}
    private View category(String badge,String title,String sub,String count,int tint,int accent,View.OnClickListener l){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(12),dp(12),dp(12),dp(12));GradientDrawable g=rounded(Color.WHITE,dp(17));g.setStroke(dp(1),Color.rgb(231,233,240));b.setBackground(g);b.setOnClickListener(l);TextView icon=text(badge,badge.length()>3?11:12,accent,true);icon.setGravity(Gravity.CENTER);icon.setBackground(rounded(tint,dp(14)));b.addView(icon,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.VERTICAL);n.setPadding(dp(13),0,dp(8),0);n.addView(text(title,17,TEXT,true));n.addView(text(sub,13,MUTED,false));n.addView(text(count,11,accent,true));b.addView(n,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));TextView ar=text("›",29,Color.rgb(160,165,177),false);ar.setGravity(Gravity.CENTER);b.addView(ar,new LinearLayout.LayoutParams(dp(28),dp(54)));b.setLayoutParams(marginParams(0,0,0,10));return b;}
    private View section(String t,String s){LinearLayout w=new LinearLayout(this);w.setOrientation(LinearLayout.VERTICAL);w.setPadding(0,dp(12),0,dp(10));w.addView(text(t,21,TEXT,true));if(s!=null&&!s.isBlank())w.addView(text(s,14,MUTED,false));return w;}
    private View tool(String t,String s,View.OnClickListener l){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(16),dp(14),dp(12),dp(14));GradientDrawable g=rounded(Color.WHITE,dp(16));g.setStroke(dp(1),Color.rgb(231,233,240));b.setBackground(g);b.setOnClickListener(l);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.addView(text(t,16,TEXT,true));c.addView(text(s,13,MUTED,false));b.addView(c,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));TextView ar=text("›",28,Color.rgb(166,171,183),false);ar.setGravity(Gravity.CENTER);b.addView(ar,new LinearLayout.LayoutParams(dp(26),dp(48)));b.setLayoutParams(marginParams(0,0,0,9));return b;}
    private TextView text(String v,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(sp);t.setTextColor(color);t.setLineSpacing(0,1.05f);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private GradientDrawable rounded(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}private GradientDrawable gradient(int[]c,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,c);g.setCornerRadius(r);return g;}private LinearLayout.LayoutParams marginParams(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    @Override public void onBackPressed(){if(categoryOpen)renderHome();else super.onBackPressed();}@Override protected void onDestroy(){super.onDestroy();if(isFinishing())worker.shutdownNow();}
}
