package ru.filemaster.offline;

import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.ContentValues;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.provider.MediaStore;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.tom_roush.pdfbox.android.PDFBoxResourceLoader;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends AppCompatActivity {
    private static final int PICK_FILES=1001,PICK_ONE=1002,DRAW_SIGNATURE=1003,CAMERA_CAPTURE=1004,MANUAL_CROP=1005;
    private static final int BG=Color.rgb(247,248,252),TEXT=Color.rgb(25,28,36),MUTED=Color.rgb(93,99,112),BLUE=Color.rgb(49,87,213),GREEN=Color.rgb(0,150,112);
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private String action="";
    private Uri pendingPdf,pendingCryptoPdf,cameraUri;
    private boolean categoryOpen=false;

    @Override protected void onCreate(Bundle savedInstanceState){super.onCreate(savedInstanceState);PDFBoxResourceLoader.init(getApplicationContext());WindowCompat.setDecorFitsSystemWindows(getWindow(),false);renderHome();Intent incoming=getIntent();if(Intent.ACTION_VIEW.equals(incoming.getAction())&&incoming.getData()!=null){pendingPdf=incoming.getData();showPdfQuickActions(pendingPdf);}}

    private void renderHome(){categoryOpen=false;ScrollView scroll=baseScroll();LinearLayout root=contentRoot();scroll.addView(root);
        LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setPadding(dp(20),dp(20),dp(20),dp(20));hero.setBackground(gradient(new int[]{Color.rgb(42,76,194),Color.rgb(91,111,232)},dp(22)));hero.setElevation(dp(2));root.addView(hero,marginParams(0,0,0,18));hero.addView(text("ФайлМастер",30,Color.WHITE,true));TextView tag=text("PDF, Office, сканы, фото, таблицы и архивы — на устройстве",15,Color.rgb(234,238,255),false);tag.setPadding(0,dp(5),0,dp(14));hero.addView(tag);TextView off=text("✓ Офлайн  •  без регистрации  •  файлы не отправляются на сервер",13,Color.WHITE,true);off.setPadding(dp(12),dp(9),dp(12),dp(9));GradientDrawable ob=rounded(Color.argb(42,255,255,255),dp(12));ob.setStroke(dp(1),Color.argb(70,255,255,255));off.setBackground(ob);hero.addView(off);
        root.addView(section("Быстрые действия","Самое нужное — в один тап"));root.addView(quickRow(quick("Сканировать","4 угла • несколько страниц",v->startActivity(new Intent(this,ScanSessionActivity.class))),quick("Объединить PDF","Несколько → один",v->pick(true,"application/pdf","merge_pdf"))));root.addView(quickRow(quick("Редактировать PDF","Текст • фигуры • штампы",v->pick(false,"application/pdf","annotate_pdf")),quick("Подписать PDF","Рукописная подпись",v->pick(false,"application/pdf","sign_pdf"))));root.addView(quickRow(quick("Редактировать документ","DOCX • ODT • TXT",v->pick(false,"*/*","edit_document")),quick("Мои файлы","Поиск • сортировка • управление",v->startActivity(new Intent(this,ResultsActivity.class)))));
        addRecent(root);root.addView(section("Все инструменты","Категории полного локального набора"));root.addView(category("PDF","PDF","Редактор, формы, Office, batch, защита","32+",Color.rgb(235,239,255),BLUE,v->renderCategory("pdf")));root.addView(category("SCAN","Сканер и OCR","4 угла, перспектива, multi-page, RU+EN","6",Color.rgb(231,249,244),GREEN,v->renderCategory("scan")));root.addView(category("SIGN","Подписи","Рукописная, PKCS#12 и проверка","3",Color.rgb(255,244,227),Color.rgb(199,116,0),v->renderCategory("sign")));root.addView(category("DOC","Документы","DOCX, ODT, TXT, HTML, Markdown, RTF","9",Color.rgb(236,245,255),Color.rgb(28,105,184),v->renderCategory("docs")));root.addView(category("XLS","Таблицы","Редактор, все листы, формулы, CSV/TSV","7",Color.rgb(232,248,238),Color.rgb(36,132,72),v->renderCategory("sheets")));root.addView(category("PPT","Презентации","PPTX ↔ PDF/TXT","2",Color.rgb(255,239,231),Color.rgb(204,83,26),v->renderCategory("slides")));root.addView(category("IMG","Изображения","JPG/PNG/WebP/SVG/TIFF/HEIC/GIF","18+",Color.rgb(245,237,255),Color.rgb(126,68,187),v->renderCategory("images")));root.addView(category("ZIP","Архиватор","ZIP/7Z/RAR/TAR, edit, split, AES","12",Color.rgb(241,243,246),Color.rgb(82,91,107),v->renderCategory("archives")));
        TextView files=text("Открыть файловый менеджер ФайлМастер",14,BLUE,true);files.setGravity(Gravity.CENTER);files.setPadding(dp(10),dp(14),dp(10),dp(8));files.setOnClickListener(v->startActivity(new Intent(this,ResultsActivity.class)));root.addView(files);TextView about=text("О приложении и приватности",14,BLUE,true);about.setGravity(Gravity.CENTER);about.setPadding(dp(10),dp(10),dp(10),dp(18));about.setOnClickListener(v->showAbout());root.addView(about);setContentView(scroll);}

    private void addRecent(LinearLayout root){List<RecentStore.Entry> recent=RecentStore.list(this);if(recent.isEmpty())return;LinearLayout tr=new LinearLayout(this);tr.setGravity(Gravity.CENTER_VERTICAL);tr.addView(section("Недавние файлы","Последние результаты"),new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));TextView clear=text("Очистить",13,BLUE,true);clear.setPadding(dp(8),dp(14),0,dp(8));clear.setOnClickListener(v->{RecentStore.clear(this);renderHome();});tr.addView(clear);root.addView(tr);for(int i=0;i<Math.min(4,recent.size());i++){RecentStore.Entry e=recent.get(i);LinearLayout b=new LinearLayout(this);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(14),dp(11),dp(10),dp(11));GradientDrawable g=rounded(Color.WHITE,dp(15));g.setStroke(dp(1),Color.rgb(231,233,240));b.setBackground(g);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.addView(text(e.name.isBlank()?"Файл":e.name,15,TEXT,true));c.addView(text(e.mime.isBlank()?"Результат":e.mime,12,MUTED,false));b.addView(c,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));b.addView(text("⋮",26,BLUE,true),new LinearLayout.LayoutParams(dp(42),dp(44)));b.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(e.name).setItems(new String[]{"Открыть","Поделиться"},(d,w)->{if(w==0)openResult(e.uri);else shareResult(e.uri);}).show());b.setLayoutParams(marginParams(0,0,0,8));root.addView(b);}}

    private void renderCategory(String id){categoryOpen=true;ScrollView s=baseScroll();LinearLayout r=contentRoot();s.addView(r);String title,sub;switch(id){case"scan"->{title="Сканер и OCR";sub="Камера, перспектива, страницы и распознавание";}case"sign"->{title="Подписи PDF";sub="Видимая и криптографическая подпись";}case"docs"->{title="Документы";sub="Редактирование и преобразование текстовых документов";}case"sheets"->{title="Таблицы";sub="XLSX/CSV/TSV, формулы и все листы";}case"slides"->{title="Презентации";sub="PPTX и PDF";}case"images"->{title="Изображения";sub="Обычные и расширенные форматы";}case"archives"->{title="Архиватор";sub="Создание, редактирование, split и распаковка";}default->{title="PDF";sub="Редактор, формы, Office, batch и защита";}}
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView back=text("←",30,TEXT,false);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->renderHome());top.addView(back,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);names.addView(text(title,27,TEXT,true));names.addView(text(sub,14,MUTED,false));top.addView(names,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));r.addView(top);TextView local=text("✓ Всё выполняется локально",13,GREEN,true);local.setPadding(dp(12),dp(9),dp(12),dp(9));local.setBackground(rounded(Color.rgb(233,249,244),dp(12)));r.addView(local,marginParams(0,0,0,16));switch(id){case"scan"->addScanTools(r);case"sign"->addSignTools(r);case"docs"->addDocTools(r);case"sheets"->addSheetTools(r);case"slides"->addSlideTools(r);case"images"->addImageTools(r);case"archives"->addArchiveTools(r);default->addPdfTools(r);}setContentView(s);}

    private void addScanTools(LinearLayout r){r.addView(tool("Многостраничный скан с 4 углами","Камера → ручная перспектива каждой страницы → PDF",v->startActivity(new Intent(this,ScanSessionActivity.class))));r.addView(tool("Исправить перспективу фото","Перетащить четыре угла вручную",v->pick(false,"image/*","manual_crop_image")));r.addView(tool("Быстрый скан одной страницы","Автообрезка + улучшение + PDF",v->captureScan()));r.addView(tool("Улучшить фото документа","Автообрезка, Ч/Б и контраст",v->pick(false,"image/*","scan_photo")));r.addView(tool("OCR фото RU + EN","Фото → TXT",v->pick(false,"image/*","ocr")));r.addView(tool("OCR целого PDF RU + EN","Все страницы → TXT",v->pick(false,"application/pdf","ocr_pdf")));}
    private void addSignTools(LinearLayout r){r.addView(tool("Рукописная подпись","Нарисовать пальцем и встроить в PDF",v->pick(false,"application/pdf","sign_pdf")));r.addView(tool("Электронная подпись PKCS#12",".p12/.pfx + пароль → CMS/PKCS#7",v->pick(false,"application/pdf","crypto_sign_pdf")));r.addView(tool("Проверить электронные подписи","Локальная криптографическая проверка",v->pick(false,"application/pdf","verify_signatures")));}
    private void addDocTools(LinearLayout r){r.addView(tool("Редактировать DOCX / ODT / TXT","Изменить текст и сохранить DOCX/ODT/TXT/PDF",v->pick(false,"*/*","edit_document")));r.addView(tool("DOCX → TXT","Извлечь текст Word",v->pick(false,"application/vnd.openxmlformats-officedocument.wordprocessingml.document","docx_txt")));r.addView(tool("DOCX → PDF","Текстовый экспорт",v->pick(false,"application/vnd.openxmlformats-officedocument.wordprocessingml.document","docx_pdf")));r.addView(tool("ODT → TXT","Извлечь текст",v->pick(false,"application/vnd.oasis.opendocument.text","odt_txt")));r.addView(tool("ODT → PDF","Текстовый экспорт",v->pick(false,"application/vnd.oasis.opendocument.text","odt_pdf")));r.addView(tool("TXT / HTML / Markdown / RTF → PDF","Создать PDF",v->pick(false,"*/*","text_pdf")));r.addView(tool("HTML / Markdown / RTF → TXT","Очистить разметку",v->pick(false,"*/*","text_txt")));r.addView(tool("TXT / Markdown / HTML → DOCX","Создать DOCX",v->pick(false,"*/*","text_docx")));r.addView(tool("TXT / Markdown / HTML → ODT","Создать ODT",v->pick(false,"*/*","text_odt")));}
    private void addSheetTools(LinearLayout r){r.addView(tool("Редактировать XLSX / CSV / TSV","Текстовая сетка с формулами",v->pick(false,"*/*","edit_table")));r.addView(tool("XLSX → CSV","Первый лист",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_csv")));r.addView(tool("Все листы XLSX → CSV","Каждый лист отдельно",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_all_csv")));r.addView(tool("XLSX → PDF","Первый лист",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_pdf")));r.addView(tool("Все листы XLSX → PDF","Один PDF со всеми листами",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_all_pdf")));r.addView(tool("CSV / TSV → XLSX","Формулы с = сохраняются как формулы",v->pick(false,"*/*","csv_xlsx")));r.addView(tool("Отчёт XLSX","Листы, строки, ячейки и формулы",v->pick(false,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx_report")));}
    private void addSlideTools(LinearLayout r){r.addView(tool("PPTX → TXT","Извлечь текст по слайдам",v->pick(false,"application/vnd.openxmlformats-officedocument.presentationml.presentation","pptx_txt")));r.addView(tool("PPTX → PDF","Текстовый PDF",v->pick(false,"application/vnd.openxmlformats-officedocument.presentationml.presentation","pptx_pdf")));}

    private void addPdfTools(LinearLayout r){r.addView(section("Редактор и формы",null));r.addView(tool("Многостраничный визуальный редактор","Ручка, маркер, текст, прямоугольники, линии, штампы",v->pick(false,"application/pdf","annotate_pdf")));r.addView(tool("Надёжно скрыть область","Закрытая часть разрушается при пересборке страницы",v->pick(false,"application/pdf","redact_pdf")));r.addView(tool("Заполнить / создать PDF-форму","Текст, checkbox, radio, choice + конструктор новых полей",v->pick(false,"application/pdf","fill_pdf_form")));
        r.addView(section("PDF → Office",null));r.addView(tool("PDF → DOCX","Редактируемый текст с разрывами страниц",v->pick(false,"application/pdf","pdf_docx")));r.addView(tool("PDF → XLSX","Эвристическое разбиение строк/колонок",v->pick(false,"application/pdf","pdf_xlsx")));r.addView(tool("PDF → PPTX","Каждая страница как визуальный слайд",v->pick(false,"application/pdf","pdf_pptx")));
        r.addView(section("Страницы и конвертация",null));r.addView(tool("Объединить PDF","Несколько → один",v->pick(true,"application/pdf","merge_pdf")));r.addView(tool("Разделить PDF","Каждая страница отдельно",v->pick(false,"application/pdf","split_pdf")));r.addView(tool("Извлечь страницы","Например: 1,3,5-8",v->pick(false,"application/pdf","extract_pages")));r.addView(tool("Удалить страницы","Номера или диапазоны",v->pick(false,"application/pdf","remove_pages")));r.addView(tool("Повернуть на 90°","Все страницы",v->pick(false,"application/pdf","rotate_pdf")));r.addView(tool("Обратный порядок","Последняя станет первой",v->pick(false,"application/pdf","reverse_pdf")));r.addView(tool("Добавить номера страниц","По центру снизу",v->pick(false,"application/pdf","page_numbers")));r.addView(tool("Обрезать поля PDF","Процент со всех сторон",v->pick(false,"application/pdf","crop_pdf")));r.addView(tool("Извлечь встроенные изображения","Картинки → PNG",v->pick(false,"application/pdf","extract_pdf_images")));r.addView(tool("Фото → PDF","Несколько изображений",v->pick(true,"image/*","images_pdf")));r.addView(tool("PDF → JPG","Все страницы",v->pick(false,"application/pdf","pdf_jpg")));r.addView(tool("PDF → TXT","Встроенный текст",v->pick(false,"application/pdf","pdf_text")));
        r.addView(section("Обработка и защита",null));r.addView(tool("Сжать PDF","Три уровня",v->pick(false,"application/pdf","compress_pdf")));r.addView(tool("Пересобрать / восстановить","Повторно сохранить структуру",v->pick(false,"application/pdf","repair_pdf")));r.addView(tool("Водяной знак","Текст на каждой странице",v->pick(false,"application/pdf","watermark_pdf")));r.addView(tool("Очистить метаданные","Свойства и XMP",v->pick(false,"application/pdf","clean_metadata")));r.addView(tool("Сравнить два PDF","Текстовый отчёт",v->pick(true,"application/pdf","compare_pdf")));r.addView(tool("Защитить паролем","Локальное шифрование",v->pick(false,"application/pdf","protect_pdf")));r.addView(tool("Снять известный пароль","Нужен текущий пароль",v->pick(false,"application/pdf","unlock_pdf")));
        r.addView(section("Пакетно",null));r.addView(tool("Сжать несколько PDF","Один режим для всех",v->pick(true,"application/pdf","batch_pdf_compress")));r.addView(tool("Водяной знак на несколько","Один текст",v->pick(true,"application/pdf","batch_pdf_watermark")));r.addView(tool("Очистить метаданные нескольких","Privacy batch",v->pick(true,"application/pdf","batch_pdf_clean")));r.addView(tool("Несколько PDF → JPG","Все страницы",v->pick(true,"application/pdf","batch_pdf_jpg")));r.addView(tool("OCR нескольких PDF","Отдельный TXT для каждого",v->pick(true,"application/pdf","batch_pdf_ocr")));r.addView(tool("Защитить несколько PDF","Один пароль для всех",v->pick(true,"application/pdf","batch_pdf_protect")));}

    private void addImageTools(LinearLayout r){r.addView(section("Редактирование",null));r.addView(tool("Сжать","JPEG 78%",v->pick(false,"image/*","image_compress")));r.addView(tool("Изменить размер","Максимальная сторона",v->pick(false,"image/*","image_resize")));r.addView(tool("Обрезать края","Процент со всех сторон",v->pick(false,"image/*","image_crop")));r.addView(tool("Повернуть на 90°","Новая копия",v->pick(false,"image/*","image_rotate")));r.addView(tool("Отразить горизонтально","Зеркальная копия",v->pick(false,"image/*","image_flip")));r.addView(tool("Сделать Ч/Б","Оттенки серого",v->pick(false,"image/*","image_gray")));r.addView(tool("Водяной знак","Текст снизу справа",v->pick(false,"image/*","image_watermark")));r.addView(tool("Удалить EXIF/XMP","Перекодирование без метаданных",v->pick(false,"image/*","image_strip_metadata")));r.addView(tool("JPG / PNG / WebP","Конвертировать формат",v->pick(false,"image/*","image_convert")));
        r.addView(section("Расширенные форматы",null));r.addView(tool("SVG → PNG","Растеризация SVG локально",v->pick(false,"*/*","svg_png")));r.addView(tool("SVG → JPG","Белый фон + растр",v->pick(false,"*/*","svg_jpg")));r.addView(tool("TIFF → PNG","Первая страница TIFF",v->pick(false,"*/*","tiff_png")));r.addView(tool("Все страницы TIFF → PNG","Multi-page TIFF в папку",v->pick(false,"*/*","tiff_all_png")));r.addView(tool("HEIC / GIF / AVIF / другое → JPG/PNG/WebP","Системный декодер Android; зависит от кодека устройства",v->pick(false,"*/*","system_image_convert")));
        r.addView(section("Пакетно",null));r.addView(tool("Сжать несколько","JPEG 78%",v->pick(true,"image/*","image_batch_compress")));r.addView(tool("Конвертировать несколько","JPG / PNG / WebP",v->pick(true,"image/*","image_batch_convert")));r.addView(tool("Водяной знак на несколько","Один текст",v->pick(true,"image/*","image_batch_watermark")));r.addView(tool("Очистить метаданные нескольких","Privacy batch",v->pick(true,"image/*","image_batch_strip_metadata")));}

    private void addArchiveTools(LinearLayout r){r.addView(section("Просмотр и изменение",null));r.addView(tool("Посмотреть ZIP / 7Z / RAR","Список без распаковки",v->pick(false,"*/*","archive_list")));r.addView(tool("Редактировать ZIP","Добавить, удалить, переименовать, сохранить копию",v->pick(false,"application/zip","zip_edit")));
        r.addView(section("Создать",null));r.addView(tool("Создать ZIP","Несколько файлов",v->pick(true,"*/*","zip")));r.addView(tool("ZIP AES-256 с паролем","Защищённый архив",v->pick(true,"*/*","zip_password")));r.addView(tool("Создать 7Z","LZMA2",v->pick(true,"*/*","7z")));r.addView(tool("Создать TAR.GZ","gzip",v->pick(true,"*/*","targz")));r.addView(tool("Создать многотомный ZIP","Размер каждой части задаётся в МБ",v->pick(true,"*/*","split_zip_create")));r.addView(tool("Собрать многотомный ZIP","Выбрать .zip + все .z01/.z02/…",v->pick(true,"*/*","split_zip_merge")));
        r.addView(section("Распаковать",null));r.addView(tool("ZIP / 7Z / RAR","В Загрузки/ФайлМастер",v->pick(false,"*/*","extract")));r.addView(tool("ZIP с паролем","AES/ZipCrypto",v->pick(false,"application/zip","extract_zip_password")));r.addView(tool("TAR / GZ / BZ2 / XZ","Также TAR.GZ/BZ2/XZ",v->pick(false,"*/*","extract_extra")));}

    private void captureScan(){try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"Скан_исходник_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");v.put(MediaStore.Images.Media.RELATIVE_PATH,Environment.DIRECTORY_PICTURES+"/ФайлМастер/Сканы");cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(cameraUri==null)throw new IllegalStateException("Не удалось подготовить файл для камеры");Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);i.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);if(i.resolveActivity(getPackageManager())==null)throw new IllegalStateException("Камера не найдена");startActivityForResult(i,CAMERA_CAPTURE);}catch(Exception e){showError(e);}}
    private void pick(boolean multi,String mime,String next){action=next;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,multi);startActivityForResult(i,multi?PICK_FILES:PICK_ONE);}

    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==CAMERA_CAPTURE){if(resultCode==RESULT_OK&&cameraUri!=null){Uri raw=cameraUri;runTask("Улучшаю скан и создаю PDF…",()->{Uri enhanced=ImageTools.enhanceDocument(this,raw);PdfTools.imagesToPdf(this,List.of(enhanced));try{getContentResolver().delete(raw,null,null);}catch(Exception ignored){}return enhanced;},"Скан сохранён как JPG и PDF");}else if(cameraUri!=null)try{getContentResolver().delete(cameraUri,null,null);}catch(Exception ignored){}cameraUri=null;return;}if(requestCode==MANUAL_CROP){if(resultCode==RESULT_OK&&data!=null){String raw=data.getStringExtra("cropped_uri");if(raw!=null)showSuccess("Перспектива исправлена",Uri.parse(raw));}return;}if(resultCode!=RESULT_OK||data==null)return;if(requestCode==DRAW_SIGNATURE){String path=data.getStringExtra("signature_path");if(path!=null&&pendingPdf!=null)runTask("Добавляю подпись…",()->PdfTools.addVisibleSignature(this,pendingPdf,new File(path)),"Подписанный PDF сохранён");return;}List<Uri> uris=collectUris(data);if(uris.isEmpty())return;Uri first=uris.get(0);
        try{switch(action){
            case"manual_crop_image"->{Intent i=new Intent(this,ManualCropActivity.class);i.putExtra("image_uri",first.toString());startActivityForResult(i,MANUAL_CROP);}case"edit_document"->{Intent i=new Intent(this,DocumentEditorActivity.class);i.putExtra("document_uri",first.toString());startActivity(i);}case"edit_table"->{Intent i=new Intent(this,TableEditorActivity.class);i.putExtra("table_uri",first.toString());startActivity(i);}
            case"annotate_pdf"->{Intent i=new Intent(this,PdfVisualEditorActivity.class);i.putExtra("pdf_uri",first.toString());startActivity(i);}case"redact_pdf"->askPage(first,PdfRedactActivity.class,"Номер страницы для скрытия данных");case"fill_pdf_form"->{Intent i=new Intent(this,PdfFormActivity.class);i.putExtra("pdf_uri",first.toString());startActivity(i);}
            case"pdf_docx"->runTask("Создаю DOCX…",()->PdfOfficeTools.toDocx(this,first),"DOCX сохранён");case"pdf_xlsx"->runTask("Распознаю строки и колонки…",()->PdfOfficeTools.toXlsx(this,first),"XLSX сохранён");case"pdf_pptx"->runTask("Создаю PPTX…",()->PdfOfficeTools.toPptxVisual(this,first),"PPTX сохранён");
            case"merge_pdf"->runTask("Объединяю PDF…",()->PdfTools.merge(this,uris),"PDF объединён");case"split_pdf"->runTask("Разделяю PDF…",()->PdfTools.split(this,first),"Страницы сохранены");case"extract_pages"->ask("Какие страницы извлечь?","1,3,5-8",false,x->runTask("Извлекаю…",()->PdfTools.extractPages(this,first,x),"PDF создан"));case"remove_pages"->ask("Какие страницы удалить?","2,4-6",false,x->runTask("Удаляю…",()->PdfTools.removePages(this,first,x),"PDF сохранён"));case"rotate_pdf"->runTask("Поворачиваю…",()->PdfTools.rotateAll(this,first,90),"PDF повёрнут");case"reverse_pdf"->runTask("Меняю порядок…",()->PdfTools.reversePages(this,first),"Порядок изменён");case"page_numbers"->runTask("Нумерую…",()->PdfTools.addPageNumbers(this,first),"Номера добавлены");case"crop_pdf"->ask("Обрезать поля на сколько %?","5",false,x->{try{float p=Float.parseFloat(x.replace(',','.'));runTask("Обрезаю…",()->PdfExtraTools.cropMargins(this,first,p),"PDF обрезан");}catch(Exception e){showError(new IllegalArgumentException("Введите число от 1 до 34"));}});case"extract_pdf_images"->runTask("Извлекаю картинки…",()->PdfExtraTools.extractEmbeddedImages(this,first),"Изображения сохранены");case"images_pdf"->runTask("Создаю PDF…",()->PdfTools.imagesToPdf(this,uris),"PDF создан");case"pdf_jpg"->runTask("Экспортирую JPG…",()->PdfTools.pdfToJpeg(this,first),"JPG сохранены");case"pdf_text"->runTask("Извлекаю текст…",()->PdfTools.extractText(this,first),"TXT сохранён");case"compress_pdf"->chooseCompression(first);case"repair_pdf"->runTask("Пересобираю…",()->PdfExtraTools.repair(this,first),"PDF сохранён");case"watermark_pdf"->ask("Текст водяного знака","КОПИЯ",false,x->runTask("Добавляю знак…",()->PdfExtraTools.watermark(this,first,x),"Знак добавлен"));case"clean_metadata"->runTask("Очищаю метаданные…",()->PdfExtraTools.removeMetadata(this,first),"PDF очищен");case"compare_pdf"->runTask("Сравниваю…",()->PdfExtraTools.compareText(this,uris),"Отчёт сохранён");case"protect_pdf"->ask("Пароль PDF","Минимум 4 символа",true,x->runTask("Шифрую…",()->PdfTools.protect(this,first,x),"PDF защищён"));case"unlock_pdf"->ask("Текущий пароль","Введите пароль",true,x->runTask("Снимаю защиту…",()->PdfTools.unlock(this,first,x),"PDF сохранён"));
            case"batch_pdf_compress"->chooseBatchCompression(uris);case"batch_pdf_watermark"->ask("Текст для всех PDF","КОПИЯ",false,x->runTask("Обрабатываю PDF…",()->BatchPdfTools.watermark(this,uris,x),"PDF обработаны"));case"batch_pdf_clean"->runTask("Очищаю PDF…",()->BatchPdfTools.cleanMetadata(this,uris),"PDF очищены");case"batch_pdf_jpg"->runTask("Экспортирую JPG…",()->BatchPdfTools.toJpg(this,uris),"Страницы экспортированы");case"batch_pdf_ocr"->runTask("OCR PDF…",()->BatchPdfTools.ocr(this,uris),"OCR завершён");case"batch_pdf_protect"->ask("Пароль для всех PDF","Минимум 4 символа",true,x->runTask("Защищаю PDF…",()->BatchPdfTools.protect(this,uris,x),"PDF защищены"));
            case"sign_pdf"->{pendingPdf=first;startActivityForResult(new Intent(this,SignatureActivity.class),DRAW_SIGNATURE);}case"crypto_sign_pdf"->{pendingCryptoPdf=first;pick(false,"*/*","crypto_pick_cert");}case"crypto_pick_cert"->{Uri pdf=pendingCryptoPdf;if(pdf==null)throw new IllegalStateException("Сначала выберите PDF");ask("Пароль сертификата","Пароль .p12/.pfx",true,x->runTask("Подписываю…",()->DigitalSignatureTools.signPdf(this,pdf,first,x),"PDF подписан"));}case"verify_signatures"->runTask("Проверяю подписи…",()->DigitalSignatureTools.verifyPdf(this,first),"Отчёт сохранён");
            case"ocr"->runOcr(first);case"ocr_pdf"->runTask("Распознаю PDF…",()->OcrTools.recognizePdfToTxt(this,first),"OCR TXT сохранён");case"scan_photo"->runTask("Улучшаю фото…",()->ImageTools.enhanceDocument(this,first),"Скан сохранён");
            case"image_compress"->runTask("Сжимаю…",()->ImageTools.compress(this,first,78),"Копия сохранена");case"image_resize"->ask("Максимальная сторона","1600",false,x->{try{int n=Integer.parseInt(x);if(n<320||n>8000)throw new NumberFormatException();runTask("Меняю размер…",()->ImageTools.resize(this,first,n),"Копия сохранена");}catch(Exception e){showError(new IllegalArgumentException("Введите 320–8000"));}});case"image_crop"->ask("Обрезать края, %","10",false,x->{try{int n=Integer.parseInt(x);runTask("Обрезаю…",()->ImageTools.cropMargins(this,first,n),"Копия сохранена");}catch(Exception e){showError(new IllegalArgumentException("Введите 1–35"));}});case"image_rotate"->runTask("Поворачиваю…",()->ImageTools.rotate90(this,first),"Копия сохранена");case"image_flip"->runTask("Отражаю…",()->ImageTools.flipHorizontal(this,first),"Копия сохранена");case"image_gray"->runTask("Делаю Ч/Б…",()->ImageTools.grayscale(this,first),"Копия сохранена");case"image_watermark"->ask("Текст водяного знака","© Моё фото",false,x->runTask("Добавляю знак…",()->ImageTools.watermark(this,first,x),"Знак добавлен"));case"image_strip_metadata"->runTask("Удаляю EXIF/XMP…",()->ImageTools.stripMetadata(this,first),"Метаданные удалены");case"image_convert"->chooseImageFormat(false,uris);case"image_batch_compress"->runTask("Сжимаю изображения…",()->ImageTools.compressBatch(this,uris,78),"Изображения сжаты");case"image_batch_convert"->chooseImageFormat(true,uris);case"image_batch_watermark"->ask("Текст для всех","© Моё фото",false,x->runTask("Добавляю знаки…",()->ImageTools.watermarkBatch(this,uris,x),"Изображения обработаны"));case"image_batch_strip_metadata"->runTask("Очищаю метаданные…",()->ImageTools.stripMetadataBatch(this,uris),"Изображения очищены");
            case"svg_png"->runTask("Растеризую SVG…",()->ExtendedImageTools.svgToPng(this,first),"PNG сохранён");case"svg_jpg"->runTask("Растеризую SVG…",()->ExtendedImageTools.svgToJpg(this,first),"JPG сохранён");case"tiff_png"->runTask("Декодирую TIFF…",()->ExtendedImageTools.tiffFirstToPng(this,first),"PNG сохранён");case"tiff_all_png"->runTask("Декодирую TIFF…",()->ExtendedImageTools.tiffAllPagesToPng(this,first),"Страницы TIFF сохранены");case"system_image_convert"->chooseSystemImageFormat(first);
            case"docx_txt"->runTask("Извлекаю DOCX…",()->DocxTools.toTxt(this,first),"TXT сохранён");case"docx_pdf"->runTask("Создаю PDF…",()->DocxTools.toPdf(this,first),"PDF сохранён");case"odt_txt"->runTask("Извлекаю ODT…",()->OpenDocumentTools.odtToTxt(this,first),"TXT сохранён");case"odt_pdf"->runTask("Создаю PDF…",()->OpenDocumentTools.odtToPdf(this,first),"PDF сохранён");case"text_pdf"->runTask("Создаю PDF…",()->TextTools.toPdf(this,first),"PDF сохранён");case"text_txt"->runTask("Извлекаю текст…",()->TextTools.toTxt(this,first),"TXT сохранён");case"text_docx"->runTask("Создаю DOCX…",()->OfficeCreateTools.textToDocx(this,first),"DOCX сохранён");case"text_odt"->runTask("Создаю ODT…",()->OfficeCreateTools.textToOdt(this,first),"ODT сохранён");case"pptx_txt"->runTask("Извлекаю PPTX…",()->PresentationTools.toTxt(this,first),"TXT сохранён");case"pptx_pdf"->runTask("Создаю PDF…",()->PresentationTools.toPdf(this,first),"PDF сохранён");
            case"xlsx_csv"->runTask("Экспортирую XLSX…",()->SheetTools.xlsxToCsv(this,first),"CSV сохранён");case"xlsx_all_csv"->runTask("Экспортирую листы…",()->SheetExtraTools.allSheetsToCsv(this,first),"CSV сохранены");case"xlsx_pdf"->runTask("Создаю PDF…",()->SheetTools.xlsxToPdf(this,first),"PDF сохранён");case"xlsx_all_pdf"->runTask("Создаю PDF всех листов…",()->SheetExtraTools.allSheetsToPdf(this,first),"PDF сохранён");case"csv_xlsx"->runTask("Создаю XLSX…",()->SheetTools.csvToXlsx(this,first),"XLSX сохранён");case"xlsx_report"->runTask("Анализирую XLSX…",()->SheetExtraTools.workbookReport(this,first),"Отчёт сохранён");
            case"archive_list"->runTextTask("Читаю архив…",()->ArchiveTools.listContents(this,first),"Содержимое архива");case"zip_edit"->{Intent i=new Intent(this,ZipEditorActivity.class);i.putExtra("zip_uri",first.toString());startActivity(i);}case"zip"->runTask("Создаю ZIP…",()->ArchiveTools.createZip(this,uris),"ZIP создан");case"zip_password"->ask("Пароль ZIP","AES-256, минимум 4 символа",true,x->runTask("Создаю ZIP…",()->ArchiveTools.createEncryptedZip(this,uris,x),"ZIP создан"));case"7z"->runTask("Создаю 7Z…",()->ArchiveTools.create7z(this,uris),"7Z создан");case"targz"->runTask("Создаю TAR.GZ…",()->ArchiveTools.createTarGz(this,uris),"TAR.GZ создан");case"split_zip_create"->ask("Размер одной части, МБ","Например: 50",false,x->{try{int n=Integer.parseInt(x);runTask("Создаю многотомный ZIP…",()->SplitZipTools.create(this,uris,n),"Части ZIP сохранены");}catch(Exception e){showError(new IllegalArgumentException("Введите размер от 1 до 2048 МБ"));}});case"split_zip_merge"->runTask("Собираю split ZIP…",()->SplitZipTools.merge(this,uris),"ZIP объединён");case"extract"->runTask("Распаковываю…",()->ArchiveTools.extract(this,first),"Архив распакован");case"extract_zip_password"->ask("Пароль ZIP","Введите пароль",true,x->runTask("Распаковываю…",()->ArchiveTools.extractEncryptedZip(this,first,x),"Архив распакован"));case"extract_extra"->runTask("Распаковываю…",()->ArchiveExtraTools.extract(this,first),"Архив распакован");
        }}catch(Exception e){showError(e);}}

    private void askPage(Uri uri,Class<?> cls,String title){ask(title,"Например: 1",false,x->{try{int p=Integer.parseInt(x.trim());if(p<1)throw new NumberFormatException();Intent i=new Intent(this,cls);i.putExtra("pdf_uri",uri.toString());i.putExtra("page",p);startActivity(i);}catch(Exception e){showError(new IllegalArgumentException("Введите номер страницы от 1"));}});}
    private void chooseCompression(Uri uri){String[] a={"Сильное — 90 DPI / 55%","Среднее — 120 DPI / 70%","Бережное — 150 DPI / 82%"};new AlertDialog.Builder(this).setTitle("Уровень сжатия").setItems(a,(d,w)->{int dpi=w==0?90:w==1?120:150;float q=w==0?.55f:w==1?.70f:.82f;runTask("Сжимаю PDF…",()->PdfExtraTools.compressRaster(this,uri,dpi,q),"PDF сжат");}).show();}
    private void chooseBatchCompression(List<Uri> u){String[] a={"Сильное — 90 DPI / 55%","Среднее — 120 DPI / 70%","Бережное — 150 DPI / 82%"};new AlertDialog.Builder(this).setTitle("Сжатие всех PDF").setItems(a,(d,w)->{int dpi=w==0?90:w==1?120:150;float q=w==0?.55f:w==1?.70f:.82f;runTask("Сжимаю PDF…",()->BatchPdfTools.compress(this,u,dpi,q),"PDF сжаты");}).show();}
    private void chooseImageFormat(boolean batch,List<Uri> u){String[] l={"JPG","PNG","WebP"},f={"jpg","png","webp"};new AlertDialog.Builder(this).setTitle("Выходной формат").setItems(l,(d,w)->{if(batch)runTask("Конвертирую…",()->ImageTools.convertBatch(this,u,f[w]),"Изображения конвертированы");else runTask("Конвертирую…",()->ImageTools.convert(this,u.get(0),f[w]),"Изображение конвертировано");}).show();}
    private void chooseSystemImageFormat(Uri u){String[] l={"JPG","PNG","WebP"},f={"jpg","png","webp"};new AlertDialog.Builder(this).setTitle("Формат результата").setItems(l,(d,w)->runTask("Декодирую системным кодеком…",()->ExtendedImageTools.systemDecodeTo(this,u,f[w]),"Изображение сохранено")).show();}

    private void runOcr(Uri u){ProgressDialog d=ProgressDialog.show(this,"OCR","Распознаю текст на устройстве…",true,false);worker.submit(()->{try{String result=OcrTools.recognize(this,u);Uri out=FileStore.publishBytes(this,result.getBytes(StandardCharsets.UTF_8),"OCR_"+System.currentTimeMillis()+".txt","text/plain",null);runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle("Распознанный текст").setMessage(result.isBlank()?"Текст не найден":result).setPositiveButton("Готово",null).setNeutralButton("Копировать",(x,w)->copyText(result)).setNegativeButton("Открыть TXT",(x,w)->openResult(out)).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();showError(e);});}});}
    private interface Work{Object run()throws Exception;}private interface TextWork{String run()throws Exception;}private interface InputCallback{void onValue(String value);}
    private void runTask(String label,Work work,String success){ProgressDialog d=ProgressDialog.show(this,"ФайлМастер",label,true,false);worker.submit(()->{try{Object result=work.run();runOnUiThread(()->{d.dismiss();if(result instanceof Uri)showSuccess(success,(Uri)result);else Toast.makeText(this,success+(result instanceof Integer?" ("+result+")":""),Toast.LENGTH_LONG).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();showError(e);});}});}
    private void runTextTask(String label,TextWork work,String title){ProgressDialog d=ProgressDialog.show(this,"ФайлМастер",label,true,false);worker.submit(()->{try{String result=work.run();runOnUiThread(()->{d.dismiss();new AlertDialog.Builder(this).setTitle(title).setMessage(result).setPositiveButton("Закрыть",null).setNeutralButton("Копировать",(x,w)->copyText(result)).show();});}catch(Exception e){runOnUiThread(()->{d.dismiss();showError(e);});}});}
    private void showSuccess(String s,Uri u){new AlertDialog.Builder(this).setTitle("Готово").setMessage(s+"\n\nРезультат: Загрузки / ФайлМастер").setPositiveButton("Открыть",(d,w)->openResult(u)).setNeutralButton("Поделиться",(d,w)->shareResult(u)).setNegativeButton("Закрыть",null).show();}
    private void openResult(Uri u){try{String m=getContentResolver().getType(u);Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(u,m==null?"*/*":m);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Открыть файл"));}catch(Exception e){Toast.makeText(this,"Файл сохранён, но открыть его не удалось",Toast.LENGTH_LONG).show();}}
    private void shareResult(Uri u){try{String m=getContentResolver().getType(u);Intent i=new Intent(Intent.ACTION_SEND);i.setType(m==null?"*/*":m);i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Поделиться файлом"));}catch(Exception e){showError(new IllegalStateException("Не удалось открыть меню отправки"));}}
    private void copyText(String v){ClipboardManager c=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("ФайлМастер",v));Toast.makeText(this,"Скопировано",Toast.LENGTH_SHORT).show();}
    private void ask(String title,String hint,boolean password,InputCallback cb){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setPadding(dp(16),dp(10),dp(16),dp(10));if(password)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Продолжить",(d,w)->{String v=e.getText().toString();if(v.isBlank())showError(new IllegalArgumentException("Поле не должно быть пустым"));else cb.onValue(v);}).setNegativeButton("Отмена",null).show();}
    private List<Uri> collectUris(Intent data){List<Uri> l=new ArrayList<>();ClipData c=data.getClipData();if(c!=null)for(int i=0;i<c.getItemCount();i++)l.add(c.getItemAt(i).getUri());else if(data.getData()!=null)l.add(data.getData());return l;}
    private void showPdfQuickActions(Uri u){new AlertDialog.Builder(this).setTitle("Что сделать с PDF?").setItems(new String[]{"Редактировать","Скрыть область","Формы","PDF → DOCX","PDF → PPTX","Подписать пальцем","Электронная подпись","Сжать","PDF → JPG","OCR PDF","Проверить подписи"},(d,w)->{if(w==0){Intent i=new Intent(this,PdfVisualEditorActivity.class);i.putExtra("pdf_uri",u.toString());startActivity(i);}else if(w==1)askPage(u,PdfRedactActivity.class,"Страница");else if(w==2){Intent i=new Intent(this,PdfFormActivity.class);i.putExtra("pdf_uri",u.toString());startActivity(i);}else if(w==3)runTask("Создаю DOCX…",()->PdfOfficeTools.toDocx(this,u),"DOCX сохранён");else if(w==4)runTask("Создаю PPTX…",()->PdfOfficeTools.toPptxVisual(this,u),"PPTX сохранён");else if(w==5){pendingPdf=u;startActivityForResult(new Intent(this,SignatureActivity.class),DRAW_SIGNATURE);}else if(w==6){pendingCryptoPdf=u;pick(false,"*/*","crypto_pick_cert");}else if(w==7)chooseCompression(u);else if(w==8)runTask("Экспортирую…",()->PdfTools.pdfToJpeg(this,u),"JPG сохранены");else if(w==9)runTask("OCR…",()->OcrTools.recognizePdfToTxt(this,u),"OCR сохранён");else runTask("Проверяю…",()->DigitalSignatureTools.verifyPdf(this,u),"Отчёт сохранён");}).setNegativeButton("Закрыть",null).show();}
    private void showAbout(){new AlertDialog.Builder(this).setTitle("ФайлМастер 1.0").setMessage("ФайлМастер выполняет обработку локально. OCR RU/EN и библиотеки находятся внутри APK. Сервер и регистрация не нужны.\n\nСложная Office-вёрстка и редкие TIFF-кодеки могут упрощаться или не поддерживаться: приложение явно сообщает об этом, а не отправляет файл в облако.\n\nРезультаты: Загрузки / ФайлМастер").setPositiveButton("Понятно",null).show();}
    private void showError(Exception e){new AlertDialog.Builder(this).setTitle("Не получилось").setMessage(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage()).setPositiveButton("OK",null).show();}

    private ScrollView baseScroll(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(BG);ViewCompat.setOnApplyWindowInsetsListener(s,(v,i)->{Insets safe=i.getInsets(WindowInsetsCompat.Type.systemBars()|WindowInsetsCompat.Type.displayCutout());v.setPadding(0,safe.top,0,safe.bottom);return i;});return s;}private LinearLayout contentRoot(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(14),dp(16),dp(28));return r;}
    private View quickRow(View a,View b){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f);x.setMargins(0,0,dp(5),dp(10));LinearLayout.LayoutParams y=new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f);y.setMargins(dp(5),0,0,dp(10));r.addView(a,x);r.addView(b,y);return r;}private View quick(String t,String s,View.OnClickListener l){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setMinimumHeight(dp(86));b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(14),dp(14),dp(14),dp(14));GradientDrawable g=rounded(Color.WHITE,dp(17));g.setStroke(dp(1),Color.rgb(230,232,239));b.setBackground(g);b.setOnClickListener(l);b.addView(text(t,16,TEXT,true));b.addView(text(s,13,MUTED,false));return b;}
    private View category(String badge,String title,String sub,String count,int tint,int accent,View.OnClickListener l){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(12),dp(12),dp(12),dp(12));GradientDrawable g=rounded(Color.WHITE,dp(17));g.setStroke(dp(1),Color.rgb(231,233,240));b.setBackground(g);b.setOnClickListener(l);TextView icon=text(badge,badge.length()>3?11:12,accent,true);icon.setGravity(Gravity.CENTER);icon.setBackground(rounded(tint,dp(14)));b.addView(icon,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.VERTICAL);n.setPadding(dp(13),0,dp(8),0);n.addView(text(title,17,TEXT,true));n.addView(text(sub,13,MUTED,false));n.addView(text(count,11,accent,true));b.addView(n,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));TextView ar=text("›",29,Color.rgb(160,165,177),false);ar.setGravity(Gravity.CENTER);b.addView(ar,new LinearLayout.LayoutParams(dp(28),dp(54)));b.setLayoutParams(marginParams(0,0,0,10));return b;}private View section(String t,String s){LinearLayout w=new LinearLayout(this);w.setOrientation(LinearLayout.VERTICAL);w.setPadding(0,dp(12),0,dp(10));w.addView(text(t,21,TEXT,true));if(s!=null&&!s.isBlank())w.addView(text(s,14,MUTED,false));return w;}private View tool(String t,String s,View.OnClickListener l){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(16),dp(14),dp(12),dp(14));GradientDrawable g=rounded(Color.WHITE,dp(16));g.setStroke(dp(1),Color.rgb(231,233,240));b.setBackground(g);b.setOnClickListener(l);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.addView(text(t,16,TEXT,true));c.addView(text(s,13,MUTED,false));b.addView(c,new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f));TextView ar=text("›",28,Color.rgb(166,171,183),false);ar.setGravity(Gravity.CENTER);b.addView(ar,new LinearLayout.LayoutParams(dp(26),dp(48)));b.setLayoutParams(marginParams(0,0,0,9));return b;}
    private TextView text(String v,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(sp);t.setTextColor(c);t.setLineSpacing(0,1.05f);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable rounded(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}private GradientDrawable gradient(int[]c,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,c);g.setCornerRadius(r);return g;}private LinearLayout.LayoutParams marginParams(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
    @Override public void onBackPressed(){if(categoryOpen)renderHome();else super.onBackPressed();}@Override protected void onDestroy(){super.onDestroy();if(isFinishing())worker.shutdownNow();}
}
