import './style.css';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { clone as cloneSkinned } from 'three/addons/utils/SkeletonUtils.js';
import { YandexBridge } from './yandex.js';

const $ = s => document.querySelector(s);
const clamp = THREE.MathUtils.clamp;
const TAU = Math.PI * 2;

const I18N = {
  ru: {loadingTitle:'ПРОБУЖДЕНИЕ ДОЛИНЫ',subtitle:'Продержись 12 минут. Усиливай героя. Сломи Владыку Тумана.',best:'Лучший забег',start:'НАЧАТЬ ЗАБЕГ',controls:'УПРАВЛЕНИЕ',menuNote:'WASD / стрелки · рывок Space · на телефоне — виртуальный джойстик',time:'Время',level:'Ур.',kills:'Враги',bossIncoming:'ВЛАДЫКА ТУМАНА ПРИБЛИЖАЕТСЯ',choosePower:'ВЫБЕРИ СИЛУ',levelUp:'НОВЫЙ УРОВЕНЬ',reroll:'Обновить выбор',fallen:'ГЕРОЙ ПАЛ',victory:'ТУМАН РАССЕЯН',revive:'ВОЗРОДИТЬСЯ',again:'ЕЩЁ РАЗ',controlsText:'Двигайся WASD или стрелками. Герой атакует ближайшего врага автоматически. Space — рывок с короткой неуязвимостью. На телефоне используй джойстик слева и кнопку рывка справа.',dash:'РЫВОК',revived:'ВОЗРОЖДЕНИЕ',noAd:'РЕКЛАМА НЕДОСТУПНА',boss:'БОСС',minBoss:'ЭЛИТНЫЙ ВРАГ',loadError:'Не удалось загрузить 3D-ассеты.'},
  en: {loadingTitle:'THE VALE AWAKENS',subtitle:'Survive for 12 minutes. Grow stronger. Break the Lord of Mist.',best:'Best run',start:'START RUN',controls:'CONTROLS',menuNote:'WASD / arrows · Space dash · virtual joystick on mobile',time:'Time',level:'Lvl',kills:'Kills',bossIncoming:'THE LORD OF MIST IS COMING',choosePower:'CHOOSE POWER',levelUp:'LEVEL UP',reroll:'Reroll choices',fallen:'THE HERO FELL',victory:'THE MIST IS BROKEN',revive:'REVIVE',again:'RUN AGAIN',controlsText:'Move with WASD or arrow keys. The hero attacks the closest enemy automatically. Space performs a short invulnerable dash. On mobile use the left joystick and the dash button on the right.',dash:'DASH',revived:'REVIVED',noAd:'AD UNAVAILABLE',boss:'BOSS',minBoss:'ELITE ENEMY',loadError:'Failed to load 3D assets.'}
};

const UPGRADE_POOL = [
  {id:'damage',name:{ru:'Закалённая сталь',en:'Hardened Steel'},desc:{ru:'+25% к урону атак',en:'+25% attack damage'},max:8,apply:g=>g.player.damage*=1.25},
  {id:'speed',name:{ru:'Шаг охотника',en:"Hunter's Step"},desc:{ru:'+12% к скорости движения',en:'+12% movement speed'},max:6,apply:g=>g.player.speed*=1.12},
  {id:'haste',name:{ru:'Боевой ритм',en:'Battle Rhythm'},desc:{ru:'Атаки на 15% чаще',en:'Attack 15% faster'},max:7,apply:g=>g.player.attackDelay*=.85},
  {id:'vitality',name:{ru:'Живучесть',en:'Vitality'},desc:{ru:'+25 к максимуму здоровья и лечение',en:'+25 max HP and heal'},max:6,apply:g=>{g.player.maxHp+=25;g.player.hp=Math.min(g.player.maxHp,g.player.hp+35);}},
  {id:'reach',name:{ru:'Длинная дуга',en:'Long Arc'},desc:{ru:'+18% к дальности удара',en:'+18% melee reach'},max:5,apply:g=>g.player.attackRange*=1.18},
  {id:'cleave',name:{ru:'Рассекающий удар',en:'Cleave'},desc:{ru:'+1 цель за одну атаку',en:'+1 target per attack'},max:4,apply:g=>g.player.cleave+=1},
  {id:'armor',name:{ru:'Костяная броня',en:'Bone Armor'},desc:{ru:'Получаемый урон -12%',en:'Take 12% less damage'},max:5,apply:g=>g.player.damageTaken*=.88},
  {id:'dash',name:{ru:'Теневой рывок',en:'Shadow Dash'},desc:{ru:'Рывок перезаряжается на 18% быстрее',en:'Dash recharges 18% faster'},max:5,apply:g=>g.player.dashCooldown*=.82},
  {id:'crit',name:{ru:'Глаз хищника',en:'Predator Eye'},desc:{ru:'+10% шанс двойного урона',en:'+10% double-damage chance'},max:5,apply:g=>g.player.crit=Math.min(.6,g.player.crit+.1)}
];

class Input {
  constructor(){
    this.keys=new Set();this.joy=new THREE.Vector2();this.dashQueued=false;
    addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.code==='Space')this.dashQueued=true;},{passive:false});
    addEventListener('keyup',e=>this.keys.delete(e.code));this.setupJoystick();
  }
  setupJoystick(){
    const base=$('#joystick'),stick=$('#stick');let pid=null;
    const update=e=>{const r=base.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32;let dx=e.clientX-cx,dy=e.clientY-cy;const len=Math.hypot(dx,dy)||1;if(len>max){dx=dx/len*max;dy=dy/len*max;}this.joy.set(dx/max,-dy/max);stick.style.transform=`translate(${dx}px,${dy}px)`;};
    base.addEventListener('pointerdown',e=>{pid=e.pointerId;base.setPointerCapture(pid);update(e);});
    base.addEventListener('pointermove',e=>{if(e.pointerId===pid)update(e);});
    const end=e=>{if(e.pointerId!==pid)return;pid=null;this.joy.set(0,0);stick.style.transform='translate(0,0)';};
    base.addEventListener('pointerup',end);base.addEventListener('pointercancel',end);$('#dash-btn').addEventListener('pointerdown',e=>{e.preventDefault();this.dashQueued=true;});
  }
  vector(){const v=new THREE.Vector2(this.joy.x,this.joy.y);if(this.keys.has('KeyA')||this.keys.has('ArrowLeft'))v.x-=1;if(this.keys.has('KeyD')||this.keys.has('ArrowRight'))v.x+=1;if(this.keys.has('KeyW')||this.keys.has('ArrowUp'))v.y+=1;if(this.keys.has('KeyS')||this.keys.has('ArrowDown'))v.y-=1;if(v.lengthSq()>1)v.normalize();return v;}
  consumeDash(){const q=this.dashQueued;this.dashQueued=false;return q;}
}

class Game {
  constructor(bridge){
    this.bridge=bridge;this.canvas=$('#game');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.55));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.06;
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x101719);this.scene.fog=new THREE.FogExp2(0x101719,.022);this.camera=new THREE.PerspectiveCamera(50,1,.1,120);this.camera.position.set(0,10.5,11.5);this.clock=new THREE.Clock();this.loader=new GLTFLoader();this.input=new Input();this.assets={};this.state='loading';this.enemies=[];this.pickups=[];this.spawnClock=0;this.elapsed=0;this.kills=0;this.level=1;this.xp=0;this.nextXp=7;this.upgradeRanks={};this.lastAttack=0;this.bossStage=0;this.reviveUsed=false;this.runWon=false;this.cameraKick=0;
    this.lowPower=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||matchMedia('(pointer:coarse)').matches;this.setupScene();this.setupUI();this.resize();addEventListener('resize',()=>this.resize());addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('visibilitychange',()=>document.hidden?this.pauseExternal():this.resumeExternal());this.bridge.onPause=()=>this.pauseExternal();this.bridge.onResume=()=>this.resumeExternal();
  }
  setupScene(){const hemi=new THREE.HemisphereLight(0xa8d7d2,0x1b1513,1.25);this.scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe5b5,2.2);sun.position.set(-8,15,7);sun.castShadow=true;sun.shadow.mapSize.set(this.lowPower?1024:2048,this.lowPower?1024:2048);sun.shadow.camera.left=-19;sun.shadow.camera.right=19;sun.shadow.camera.top=19;sun.shadow.camera.bottom=-19;sun.shadow.bias=-.00035;this.scene.add(sun);const rim=new THREE.DirectionalLight(0x4d91a1,.85);rim.position.set(10,7,-10);this.scene.add(rim);}
  setupUI(){ $('#start-btn').onclick=()=>this.startRun();$('#how-btn').onclick=()=>$('#controls-panel').classList.add('active');$('#close-controls').onclick=()=>$('#controls-panel').classList.remove('active');$('#restart-btn').onclick=()=>this.restartFromOver();$('#revive-btn').onclick=()=>this.tryRevive();$('#reroll-btn').onclick=()=>this.tryReroll(); }
  localize(lang){this.lang=['ru','be','uk','kk'].includes(lang)?'ru':'en';document.documentElement.lang=this.lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(I18N[this.lang][k])el.textContent=I18N[this.lang][k];});}
  async load(progress={}){this.progress=progress;$('#best-time').textContent=this.format(progress.bestTime||0);const files={hero:'/assets/hero.glb',orc:'/assets/orc.glb',demon:'/assets/demon.glb',tree:'/assets/tree.glb',rock:'/assets/rock.glb',gem:'/assets/gem.glb',arena:'/assets/arena.glb'};const entries=Object.entries(files);let done=0;for(const [key,url] of entries){this.assets[key]=await this.loader.loadAsync(url);this.setLoading(++done/entries.length);}this.buildEnvironment();this.state='menu';$('#loading').classList.remove('screen--visible');$('#menu').classList.add('active');this.bridge.ready();this.animate();}
  setLoading(p){$('#loading-fill').style.width=`${Math.round(p*100)}%`;$('#loading-text').textContent=`${Math.round(p*100)}%`;}
  prepareVisual(gltf,targetHeight){const model=cloneSkinned(gltf.scene);model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),size=new THREE.Vector3();box.getSize(size);model.scale.multiplyScalar(targetHeight/Math.max(size.y,.001));model.updateMatrixWorld(true);const box2=new THREE.Box3().setFromObject(model);model.position.y-=box2.min.y;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=true;if(o.material)o.material=o.material.clone();}});const root=new THREE.Group();root.add(model);root.userData.model=model;return root;}
  prepareGround(gltf,targetSize){const model=cloneSkinned(gltf.scene);model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),size=new THREE.Vector3();box.getSize(size);model.scale.multiplyScalar(targetSize/Math.max(size.x,size.z,.001));model.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(model);model.position.y-=b.min.y;model.traverse(o=>{if(o.isMesh){o.receiveShadow=true;o.castShadow=false;if(o.material)o.material=o.material.clone();}});const root=new THREE.Group();root.add(model);return root;}
  buildEnvironment(){this.environment=new THREE.Group();this.scene.add(this.environment);this.environment.add(this.prepareGround(this.assets.arena,64));const trees=[[-23,-17],[-18,-22],[-11,-25],[-2,-27],[8,-26],[17,-22],[23,-15],[26,-6],[26,5],[23,15],[16,22],[7,26],[-3,27],[-13,24],[-21,18],[-26,10],[-27,0],[-25,-9],[-18,-15],[19,-11],[-14,14],[15,15]];trees.forEach((p,i)=>{const t=this.prepareVisual(this.assets.tree,3.8+(i%4)*.45);t.position.set(p[0],0,p[1]);t.rotation.y=(i*.83)%TAU;this.environment.add(t);});const rocks=[[-9,-11],[9,-13],[13,7],[-14,6],[-5,17],[18,-2],[3,-21],[-20,-3],[7,18],[-17,-18],[20,18]];rocks.forEach((p,i)=>{const r=this.prepareVisual(this.assets.rock,1.2+(i%3)*.25);r.position.set(p[0],0,p[1]);r.rotation.y=(i*1.37)%TAU;this.environment.add(r);});}
  resetRunState(){if(this.player?.root)this.scene.remove(this.player.root);this.enemies.forEach(e=>this.scene.remove(e.root));this.pickups.forEach(p=>this.scene.remove(p.root));this.enemies=[];this.pickups=[];this.elapsed=0;this.kills=0;this.level=1;this.xp=0;this.nextXp=7;this.spawnClock=.4;this.lastAttack=0;this.bossStage=0;this.reviveUsed=false;this.runWon=false;this.upgradeRanks={};this.player={root:this.prepareVisual(this.assets.hero,1.82),mixer:null,action:null,pos:new THREE.Vector3(),hp:100,maxHp:100,speed:5.1,damage:24,attackDelay:.7,attackRange:2.35,cleave:1,damageTaken:1,crit:.05,dashCooldown:2.15,dashTimer:0,dashTime:0,invuln:0,facing:new THREE.Vector3(0,0,1)};this.scene.add(this.player.root);this.player.mixer=new THREE.AnimationMixer(this.player.root);this.playPlayerAnim('idle',true,.16);this.updateHud();}
  findClip(gltf,words){const clips=gltf.animations||[],w=words.map(x=>x.toLowerCase());return clips.find(c=>w.some(x=>c.name.toLowerCase().includes(x)))||clips[0]||null;}
  playPlayerAnim(kind,loop=true,fade=.12){const map={idle:['idle'],run:['run','walk'],attack:['attack','slash','sword','hit'],death:['death','die']};const clip=this.findClip(this.assets.hero,map[kind]||[kind]);if(!clip)return;const next=this.player.mixer.clipAction(clip);if(this.player.action===next&&next.isRunning())return;next.reset().setLoop(loop?THREE.LoopRepeat:THREE.LoopOnce,loop?Infinity:1);next.clampWhenFinished=!loop;if(this.player.action&&this.player.action!==next)this.player.action.fadeOut(fade);next.fadeIn(fade).play();this.player.action=next;}
  startRun(){$('#menu').classList.remove('active');$('#gameover').classList.remove('active');$('#upgrade').classList.remove('active');$('#hud').classList.remove('hidden');if(this.lowPower)$('#mobile-controls').classList.remove('hidden');this.resetRunState();this.state='playing';this.clock.getDelta();this.bridge.startGameplay();}
  restartFromOver(){this.bridge.showFullscreen().finally(()=>this.startRun());}
  pauseExternal(){if(this.state==='playing'){this.state='paused-external';this.bridge.stopGameplay();}}
  resumeExternal(){if(this.state==='paused-external'){this.state='playing';this.clock.getDelta();this.bridge.startGameplay();}}
  async tryRevive(){if(this.reviveUsed)return;const ok=await this.bridge.showRewarded();if(!ok){this.toast(I18N[this.lang].noAd);return;}this.reviveUsed=true;$('#gameover').classList.remove('active');this.player.hp=this.player.maxHp*.7;this.player.invuln=2.5;this.player.root.visible=true;this.state='playing';this.bridge.startGameplay();this.toast(I18N[this.lang].revived);this.updateHud();}
  async tryReroll(){const ok=await this.bridge.showRewarded();if(ok)this.showUpgrade(true);else this.toast(I18N[this.lang].noAd);}
  movePlayer(dt){const p=this.player;p.invuln=Math.max(0,p.invuln-dt);p.dashTimer=Math.max(0,p.dashTimer-dt);const v=this.input.vector();if(this.input.consumeDash()&&p.dashTimer<=0&&v.lengthSq()>.05){p.dashTimer=p.dashCooldown;p.dashTime=.18;p.invuln=Math.max(p.invuln,.28);}if(p.dashTime>0)p.dashTime-=dt;const mul=p.dashTime>0?2.65:1;if(v.lengthSq()>.02){const dir=new THREE.Vector3(v.x,0,-v.y).normalize();p.facing.lerp(dir,Math.min(1,dt*10)).normalize();p.pos.addScaledVector(dir,p.speed*mul*dt);if(p.pos.length()>27)p.pos.normalize().multiplyScalar(27);p.root.rotation.y=Math.atan2(p.facing.x,p.facing.z);if(!p.action||!p.action.getClip().name.toLowerCase().includes('attack'))this.playPlayerAnim('run');}else if(!p.action||!p.action.getClip().name.toLowerCase().includes('attack'))this.playPlayerAnim('idle');p.root.position.copy(p.pos);}
  spawnEnemy(type='orc',elite=false,boss=false){const angle=Math.random()*TAU,radius=24+Math.random()*4,base=type==='demon'?this.assets.demon:this.assets.orc,root=this.prepareVisual(base,boss?3.4:elite?2.45:1.75),pos=new THREE.Vector3(Math.sin(angle)*radius,0,Math.cos(angle)*radius);root.position.copy(pos);this.scene.add(root);const mixer=new THREE.AnimationMixer(root),clip=this.findClip(base,['run','walk','idle']),action=clip?mixer.clipAction(clip):null;action?.play();const scale=1+this.elapsed/720;this.enemies.push({root,pos,mixer,action,type,elite,boss,hp:(boss?1500:elite?210:62)*scale,speed:(boss?2.15:elite?2.55:2.85)*(1+this.elapsed/1800),damage:(boss?18:elite?12:8)*(1+this.elapsed/900),attackTimer:0,dead:false,baseGltf:base});}
  spawnLogic(dt){this.spawnClock-=dt;if(this.spawnClock<=0){this.spawnClock=Math.max(.34,1.08-this.elapsed/850);const cap=this.lowPower?26:42;if(this.enemies.length<cap)this.spawnEnemy(this.elapsed>260&&Math.random()<.28?'demon':'orc');}if(this.elapsed>240&&this.bossStage<1){this.bossStage=1;this.spawnEnemy('demon',true);this.toast(I18N[this.lang].minBoss);}if(this.elapsed>480&&this.bossStage<2){this.bossStage=2;this.spawnEnemy('demon',true);this.spawnEnemy('orc',true);this.toast(I18N[this.lang].minBoss);}if(this.elapsed>690&&this.bossStage<3){this.bossStage=3;$('#boss-warning').classList.remove('hidden');setTimeout(()=>$('#boss-warning').classList.add('hidden'),3200);this.spawnEnemy('demon',false,true);this.toast(I18N[this.lang].boss);}}
  updateEnemies(dt){const p=this.player;for(const e of this.enemies){if(e.dead)continue;e.mixer.update(dt);e.attackTimer=Math.max(0,e.attackTimer-dt);const to=p.pos.clone().sub(e.pos),d=to.length();if(d>.001)to.multiplyScalar(1/d);if(d>1.15){e.pos.addScaledVector(to,e.speed*dt);e.root.position.copy(e.pos);e.root.rotation.y=Math.atan2(to.x,to.z);}else if(e.attackTimer<=0){e.attackTimer=e.boss?.65:.9;if(p.invuln<=0){p.hp-=e.damage*p.damageTaken;p.invuln=.35;this.cameraKick=.22;if(p.hp<=0){p.hp=0;this.gameOver(false);}}}}}
  autoAttack(){if(this.elapsed-this.lastAttack<this.player.attackDelay)return;const p=this.player,targets=this.enemies.filter(e=>!e.dead).map(e=>({e,d:e.pos.distanceToSquared(p.pos)})).filter(x=>x.d<=p.attackRange*p.attackRange).sort((a,b)=>a.d-b.d).slice(0,p.cleave);if(!targets.length)return;this.lastAttack=this.elapsed;this.playPlayerAnim('attack',false,.06);setTimeout(()=>{if(this.state==='playing')this.playPlayerAnim(this.input.vector().lengthSq()>.02?'run':'idle',true,.08);},Math.min(450,p.attackDelay*700));for(const {e} of targets)this.damageEnemy(e,p.damage*(Math.random()<p.crit?2:1));}
  damageEnemy(e,amount){e.hp-=amount;e.root.scale.multiplyScalar(1.035);setTimeout(()=>e.root.scale.multiplyScalar(1/1.035),70);if(e.hp<=0)this.killEnemy(e);}
  killEnemy(e){if(e.dead)return;e.dead=true;this.kills++;const clip=this.findClip(e.baseGltf,['death','die']);if(clip){e.action?.stop();e.action=e.mixer.clipAction(clip);e.action.setLoop(THREE.LoopOnce,1);e.action.clampWhenFinished=true;e.action.play();}this.spawnPickup(e.pos,e.boss?30:e.elite?8:1);setTimeout(()=>{this.scene.remove(e.root);const i=this.enemies.indexOf(e);if(i>=0)this.enemies.splice(i,1);},e.boss?1100:620);if(e.boss)this.victory();}
  spawnPickup(pos,value){const root=this.prepareVisual(this.assets.gem,value>10?.72:value>2?.48:.34);root.position.copy(pos);root.position.y=.22;this.scene.add(root);this.pickups.push({root,pos:pos.clone(),value,t:Math.random()*TAU});}
  updatePickups(dt){for(let i=this.pickups.length-1;i>=0;i--){const o=this.pickups[i];o.t+=dt*2.3;o.root.rotation.y+=dt*2.4;o.root.position.y=.28+Math.sin(o.t)*.08;const d=o.pos.distanceTo(this.player.pos);if(d<4.2){const dir=this.player.pos.clone().sub(o.pos).normalize();o.pos.addScaledVector(dir,(7+(4.2-d)*4)*dt);o.root.position.x=o.pos.x;o.root.position.z=o.pos.z;}if(d<.75){this.gainXp(o.value);this.scene.remove(o.root);this.pickups.splice(i,1);}}}
  gainXp(v){this.xp+=v;if(this.xp>=this.nextXp){this.xp-=this.nextXp;this.level++;this.nextXp=Math.floor(this.nextXp*1.28+3);this.showUpgrade();}this.updateHud();}
  showUpgrade(reroll=false){if(!reroll){this.state='upgrade';this.bridge.stopGameplay();$('#upgrade').classList.add('active');}const pool=UPGRADE_POOL.filter(u=>(this.upgradeRanks[u.id]||0)<u.max),chosen=[];while(chosen.length<Math.min(3,pool.length))chosen.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0]);const wrap=$('#upgrade-cards');wrap.innerHTML='';for(const u of chosen){const rank=(this.upgradeRanks[u.id]||0)+1,b=document.createElement('button');b.className='upgrade-card';b.innerHTML=`<b>${u.name[this.lang]}</b><span>${u.desc[this.lang]}</span><small>${this.lang==='ru'?'Ранг':'Rank'} ${rank}/${u.max}</small>`;b.onclick=()=>{u.apply(this);this.upgradeRanks[u.id]=rank;$('#upgrade').classList.remove('active');this.state='playing';this.bridge.startGameplay();this.updateHud();};wrap.appendChild(b);}}
  updateHud(){if(!this.player)return;$('#time').textContent=this.format(this.elapsed);$('#level').textContent=this.level;$('#kills').textContent=this.kills;$('#hp-fill').style.width=`${clamp(this.player.hp/this.player.maxHp*100,0,100)}%`;$('#hp-text').textContent=`${Math.ceil(this.player.hp)} / ${Math.ceil(this.player.maxHp)}`;$('#xp-fill').style.width=`${clamp(this.xp/this.nextXp*100,0,100)}%`;}
  gameOver(victory=false){if(['gameover','victory'].includes(this.state))return;this.runWon=victory;this.state=victory?'victory':'gameover';this.bridge.stopGameplay();$('#hud').classList.add('hidden');$('#mobile-controls').classList.add('hidden');$('#result-title').textContent=victory?I18N[this.lang].victory:I18N[this.lang].fallen;$('#result-kicker').textContent=victory?'RUN COMPLETE':'RUN ENDED';$('#result-time').textContent=this.format(this.elapsed);$('#result-kills').textContent=this.kills;$('#result-level').textContent=this.level;$('#revive-btn').style.display=!victory&&!this.reviveUsed?'block':'none';$('#gameover').classList.add('active');const best=Math.max(this.progress.bestTime||0,Math.floor(this.elapsed));this.progress={...this.progress,bestTime:best,bestKills:Math.max(this.progress.bestKills||0,this.kills)};this.bridge.saveProgress(this.progress);$('#best-time').textContent=this.format(best);}
  victory(){this.elapsed=Math.max(this.elapsed,720);this.gameOver(true);}
  updateCamera(dt){const desired=this.player.pos.clone().add(new THREE.Vector3(0,10.3,11.2));this.camera.position.lerp(desired,1-Math.exp(-dt*5));const target=this.player.pos.clone().add(new THREE.Vector3(0,.75,0));if(this.cameraKick>0){this.cameraKick=Math.max(0,this.cameraKick-dt);this.camera.position.x+=(Math.random()-.5)*this.cameraKick;this.camera.position.y+=(Math.random()-.5)*this.cameraKick*.45;}this.camera.lookAt(target);}
  animate(){requestAnimationFrame(()=>this.animate());const dt=Math.min(this.clock.getDelta(),.033);if(this.state==='playing'){this.elapsed+=dt;this.player.mixer.update(dt);this.movePlayer(dt);this.spawnLogic(dt);this.updateEnemies(dt);this.autoAttack();this.updatePickups(dt);this.updateCamera(dt);this.updateHud();}else if(this.state==='menu'){this.camera.position.x=Math.sin(performance.now()*.00012)*2;this.camera.lookAt(0,0,0);}this.renderer.render(this.scene,this.camera);}
  resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
  format(s){s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
  toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('show'),1500);}
}

async function boot(){const bridge=new YandexBridge();await bridge.init();const game=new Game(bridge);game.localize(bridge.lang);const progress=await bridge.loadProgress();try{await game.load(progress);}catch(err){console.error(err);$('#loading-text').textContent=I18N[game.lang].loadError;$('#loading-fill').style.width='100%';$('#loading-fill').style.background='#a53e43';}}
boot();
