import Phaser from 'phaser';
import './styles.css';
import { WORLD_THEMES, LEVELS, BOSSES, STORY, UPGRADES, upgradeCost } from './content.js';
import { loadSave, persist } from './save.js';

const uiHost=document.querySelector('#ui');
const coarse=matchMedia('(pointer: coarse)').matches;
let save=loadSave();

function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function formatTime(sec){const s=Math.max(0,Math.floor(sec));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function setAccent(hex){document.documentElement.style.setProperty('--accent',hex);}
function clearUI(){uiHost.innerHTML='';}
function el(html){const wrap=document.createElement('div');wrap.innerHTML=html.trim();return wrap.firstElementChild;}
function mount(node){clearUI();uiHost.append(node);return node;}
function bindClick(root,selector,fn){root.querySelector(selector)?.addEventListener('click',fn);}

class Synth {
  constructor(){this.ctx=null;this.master=.8;}
  ensure(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();}if(this.ctx.state==='suspended')this.ctx.resume();}
  tone(freq=220,dur=.06,type='triangle',gain=.04,slide=0){if(!save.settings.sfx)return;this.ensure();const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(35,freq+slide),t+dur);g.gain.setValueAtTime(gain*this.master,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+dur+.02);}
  jump(){this.tone(210,.08,'triangle',.05,170);} dash(){this.tone(95,.1,'sawtooth',.04,220);} slash(n=0){this.tone(150+n*38,.055,'square',.035,-55);} hit(){this.tone(80,.08,'square',.05,-30);} coin(){this.tone(780,.05,'sine',.035,260);} hurt(){this.tone(105,.14,'sawtooth',.055,-50);} checkpoint(){this.tone(330,.12,'sine',.035,330);setTimeout(()=>this.tone(650,.12,'triangle',.03,120),70);} boss(){this.tone(75,.35,'sawtooth',.045,55);} win(){[440,660,880].forEach((f,i)=>setTimeout(()=>this.tone(f,.18,'sine',.03,120),i*90));}
}
const sfx=new Synth();
addEventListener('pointerdown',()=>sfx.ensure(),{once:true});

function menuScreen(scene){
  setAccent('#d9485f');
  const completed=Object.values(save.levels).filter(v=>v?.stars).length;
  const root=mount(el(`
    <div class="ui-root screen">
      <div class="panel menu">
        <section class="hero-card">
          <div class="logo">SHADOW<br>RONIN<span>ПУТЬ ТЕНИ</span></div>
          <div class="tagline">Атмосферный 2D action-platformer о ронине, который проходит пять земель, собирает осколки печати и охотится на Пять Теней.</div>
        </section>
        <section class="menu-actions">
          <div class="currency"><i class="coin-dot"></i>${save.coins} монет</div>
          <button class="btn primary" id="continue">${save.unlocked>1?'Продолжить':'Начать путь'}</button>
          <button class="btn" id="levels">Выбор уровней</button>
          <button class="btn" id="upgrades">Прокачка</button>
          <button class="btn" id="settings">Настройки</button>
          <div class="small-note">Открыто уровней: ${save.unlocked}/30 · Завершено: ${completed}/30<br>Прогресс сохраняется автоматически на устройстве.</div>
        </section>
      </div>
    </div>`));
  bindClick(root,'#continue',()=>scene.scene.start('Map',{focus:Math.min(save.unlocked,30),autoStart:true}));
  bindClick(root,'#levels',()=>scene.scene.start('Map'));
  bindClick(root,'#upgrades',()=>scene.scene.start('Map',{modal:'upgrades'}));
  bindClick(root,'#settings',()=>scene.scene.start('Map',{modal:'settings'}));
}

function renderUpgradeModal(root,scene){
  const old=root.querySelector('.modal-wrap');old?.remove();
  const modal=el(`<div class="modal-wrap"><div class="panel modal"><h2>Путь ронина</h2><p>Улучшения постоянные и действуют на всех уровнях.</p><div class="currency"><i class="coin-dot"></i><span id="coinCount">${save.coins}</span> монет</div><div class="upgrade-grid"></div><div class="modal-row"><button class="btn ghost close">Закрыть</button></div></div></div>`);
  root.append(modal);
  const grid=modal.querySelector('.upgrade-grid');
  for(const [key,u] of Object.entries(UPGRADES)){
    const lv=save.upgrades[key]; const cost=upgradeCost(key,lv); const max=lv>=u.max;
    const card=el(`<div class="upgrade"><h3>${u.name}</h3><p>${u.desc}</p><div class="upgrade-meta"><div class="dots">${Array.from({length:u.max},(_,i)=>`<i class="dot ${i<lv?'on':''}"></i>`).join('')}</div><button class="btn buy" ${max||save.coins<cost?'disabled':''}>${max?'MAX':`${cost} ◉`}</button></div></div>`);
    card.querySelector('.buy')?.addEventListener('click',()=>{if(lv>=u.max||save.coins<cost)return;save.coins-=cost;save.upgrades[key]++;persist(save);renderUpgradeModal(root,scene);});
    grid.append(card);
  }
  modal.querySelector('.close').addEventListener('click',()=>modal.remove());
}

function renderSettingsModal(root){
  root.querySelector('.modal-wrap')?.remove();
  const modal=el(`<div class="modal-wrap"><div class="panel modal"><h2>Настройки</h2><p>Настройки применяются сразу и сохраняются.</p><div class="settings-grid">
    <div class="setting"><label>Звуковые эффекты</label><div id="sfxToggle" class="toggle ${save.settings.sfx?'on':''}"><i></i></div></div>
    <div class="setting"><label>Музыка / атмосфера</label><div id="musicToggle" class="toggle ${save.settings.music?'on':''}"><i></i></div></div>
    <div class="setting"><label>Качество</label><select id="quality"><option value="low">Эконом</option><option value="balanced">Баланс</option><option value="high">Высокое</option></select></div>
    <div class="setting"><label>Чувствительность камеры</label><input id="sens" type="range" min="0.7" max="1.5" step="0.1" value="${save.settings.sensitivity}"></div>
  </div><div class="modal-row"><button class="btn ghost close">Закрыть</button></div></div></div>`);
  root.append(modal); modal.querySelector('#quality').value=save.settings.quality;
  modal.querySelector('#sfxToggle').onclick=()=>{save.settings.sfx=!save.settings.sfx;modal.querySelector('#sfxToggle').classList.toggle('on',save.settings.sfx);persist(save);};
  modal.querySelector('#musicToggle').onclick=()=>{save.settings.music=!save.settings.music;modal.querySelector('#musicToggle').classList.toggle('on',save.settings.music);persist(save);};
  modal.querySelector('#quality').onchange=e=>{save.settings.quality=e.target.value;persist(save);};
  modal.querySelector('#sens').oninput=e=>{save.settings.sensitivity=Number(e.target.value);persist(save);};
  modal.querySelector('.close').onclick=()=>modal.remove();
}

function storyModal(scene,level){
  const world=WORLD_THEMES[level.world];
  const root=uiHost.querySelector('.ui-root');
  const modal=el(`<div class="modal-wrap"><div class="panel story-panel"><div class="story-kicker">ГЛАВА ${level.world+1}</div><div class="story-title">${world.name}</div><div class="story-text">${STORY[level.world]}</div><div class="modal-row"><button class="btn ghost cancel">Назад</button><button class="btn primary go">Начать</button></div></div></div>`);
  root.append(modal);
  modal.querySelector('.cancel').onclick=()=>modal.remove();
  modal.querySelector('.go').onclick=()=>scene.scene.start('Game',{levelId:level.id});
}

class BootScene extends Phaser.Scene{
  constructor(){super('Boot');}
  create(){this.makeTextures();this.scene.start('Menu');}
  makeTextures(){
    const g=this.add.graphics();
    g.fillStyle(0x050609,1);g.fillCircle(31,18,13);g.fillRoundedRect(19,27,25,34,7);g.fillRect(17,56,12,20);g.fillRect(35,56,12,20);g.fillRect(9,33,12,30);g.fillRect(43,33,12,30);g.fillStyle(0xd9485f,1);g.fillRect(39,17,19,4);g.fillTriangle(55,17,64,13,57,22);g.fillStyle(0xe8e2dc,1);g.fillRect(23,15,17,3);g.generateTexture('ninja',68,80);g.clear();
    const enemy=(key,color,shape='normal')=>{g.fillStyle(0x08090c,1);if(shape==='brute'){g.fillCircle(35,20,17);g.fillRoundedRect(14,34,43,39,8);}else if(shape==='mage'){g.fillTriangle(35,5,15,34,55,34);g.fillRoundedRect(19,30,32,43,8);}else{g.fillCircle(31,18,13);g.fillRoundedRect(16,30,30,42,7);}g.fillStyle(color,1);g.fillRect(18,17,28,4);g.generateTexture(key,70,78);g.clear();};
    enemy('enemySword',0xb83f50);enemy('enemyArcher',0x6a95b3);enemy('enemyBrute',0xe07542,'brute');enemy('enemyMage',0x66b790,'mage');enemy('enemyAssassin',0x985bc7);
    g.fillStyle(0xf0c66a,1);g.fillCircle(10,10,8);g.lineStyle(2,0xffe9ad,1);g.strokeCircle(10,10,7);g.generateTexture('coin',20,20);g.clear();
    g.fillStyle(0xe8ded0,1);g.fillRoundedRect(2,2,22,28,3);g.fillStyle(0x9a2f42,1);g.fillRect(5,8,16,2);g.fillRect(5,14,12,2);g.fillRect(5,20,15,2);g.generateTexture('scroll',26,32);g.clear();
    g.fillStyle(0xb9dbe8,1);g.fillTriangle(0,6,14,0,10,7);g.fillTriangle(0,6,14,12,10,5);g.generateTexture('shuriken',14,12);g.clear();
    g.fillStyle(0xe0674f,1);g.fillCircle(7,7,6);g.generateTexture('enemyShot',14,14);g.clear();
    g.fillStyle(0xabcad8,1);g.fillCircle(6,6,5);g.generateTexture('playerShot',12,12);g.clear();
    g.fillStyle(0xbec8d0,.9);g.fillTriangle(0,18,12,0,24,18);g.generateTexture('spike',24,18);g.clear();
    g.fillStyle(0xaab0b8,1);g.fillCircle(18,18,16);g.fillStyle(0x1d2026,1);for(let i=0;i<8;i++){const a=i*Math.PI/4;g.fillTriangle(18+Math.cos(a)*14,18+Math.sin(a)*14,18+Math.cos(a-.18)*24,18+Math.sin(a-.18)*24,18+Math.cos(a+.18)*24,18+Math.sin(a+.18)*24);}g.fillStyle(0x101218,1);g.fillCircle(18,18,5);g.generateTexture('saw',48,48);g.clear();
    g.fillStyle(0x16191f,1);g.fillRoundedRect(0,0,64,64,10);g.lineStyle(3,0xd9485f,1);g.strokeRoundedRect(7,7,50,50,8);g.generateTexture('checkpoint',64,64);g.clear();
    g.fillStyle(0x17191f,1);g.fillRect(14,10,10,70);g.fillStyle(0xd9485f,.75);g.fillTriangle(24,12,66,30,24,48);g.generateTexture('goal',70,82);g.clear();
    g.fillStyle(0xffffff,1);g.fillCircle(3,3,3);g.generateTexture('particle',6,6);g.clear();g.fillStyle(0xffffff,1);g.fillRect(0,0,5,12);g.generateTexture('rain',5,12);g.destroy();
  }
}

class MenuScene extends Phaser.Scene{constructor(){super('Menu');}create(){menuScreen(this);this.events.once(Phaser.Scenes.Events.SHUTDOWN,clearUI);}}

class MapScene extends Phaser.Scene{
  constructor(){super('Map');}
  init(data){this.dataIn=data||{};}
  create(){
    const root=mount(el(`<div class="ui-root screen map-screen"><div class="map-head"><div><div class="map-title">Карта пути</div><div class="map-sub">Пять земель · 30 уровней · 5 хранителей печати</div></div><div class="map-actions"><div class="currency"><i class="coin-dot"></i>${save.coins}</div><button class="btn" id="upgradeBtn">Прокачка</button><button class="btn" id="settingsBtn">Настройки</button><button class="btn ghost" id="backBtn">Меню</button></div></div><div class="map-content"></div></div>`));
    const content=root.querySelector('.map-content');
    WORLD_THEMES.forEach((w,wi)=>{const levels=LEVELS.filter(l=>l.world===wi);const stars=levels.reduce((a,l)=>a+(save.levels[l.id]?.stars||0),0);const block=el(`<section class="panel world-block"><div class="world-head"><div><div class="world-name">${wi+1}. ${w.name}</div><div class="world-sub">${w.subtitle}</div></div><div class="world-progress">${stars}/18 ★</div></div><div class="levels"></div></section>`);const grid=block.querySelector('.levels');levels.forEach(level=>{const unlocked=level.id<=save.unlocked;const rec=save.levels[level.id]||{};const card=el(`<button class="level-card ${unlocked?'':'locked'} ${level.boss?'boss':''}" ${unlocked?'':'disabled'}><span class="level-num">УРОВЕНЬ ${level.id}</span><div class="level-name">${level.title}</div>${level.boss?'<span class="boss-tag">БОСС</span>':''}<div class="stars">${'★'.repeat(rec.stars||0)}${'☆'.repeat(3-(rec.stars||0))}</div>${save.scrolls[level.id]?'<span class="scroll-mark">▣</span>':''}</button>`);if(unlocked)card.onclick=()=>{if(level.stage===0&&!save.levels[level.id]?.stars)storyModal(this,level);else this.scene.start('Game',{levelId:level.id});};grid.append(card);});content.append(block);});
    bindClick(root,'#backBtn',()=>this.scene.start('Menu'));bindClick(root,'#upgradeBtn',()=>renderUpgradeModal(root,this));bindClick(root,'#settingsBtn',()=>renderSettingsModal(root));if(this.dataIn.modal==='upgrades')renderUpgradeModal(root,this);if(this.dataIn.modal==='settings')renderSettingsModal(root);if(this.dataIn.autoStart){const level=LEVELS[Math.min(save.unlocked,30)-1];setTimeout(()=>{if(level.stage===0&&!save.levels[level.id]?.stars)storyModal(this,level);else this.scene.start('Game',{levelId:level.id});},120);}this.events.once(Phaser.Scenes.Events.SHUTDOWN,clearUI);
  }
}

class GameScene extends Phaser.Scene{
  constructor(){super('Game');}
  init(data){this.level=LEVELS[(data.levelId||1)-1];this.theme=WORLD_THEMES[this.level.world];}
  create(){
    setAccent(`#${this.theme.accent.toString(16).padStart(6,'0')}`);this.runDeaths=0;this.collected=0;this.totalCoins=0;this.startedAt=this.time.now;this.levelDone=false;this.bossStarted=false;this.bossDefeated=false;this.checkpoint={x:180,y:510};this.worldPlatforms=[];this.enemies=[];this.hazards=[];this.movingPlatforms=[];this.pendingEnemies=[];this.physics.world.setBounds(0,0,this.level.width,900);this.cameras.main.setBounds(0,0,this.level.width,720);this.buildBackground();this.buildLevel();this.createPlayer();this.createGroupsAndCollisions();this.createHUD();this.createInputs();this.cameras.main.startFollow(this.player,true,.08,.08,-130,30);this.cameras.main.setDeadzone(220,100);this.showToast(`ГЛАВА ${this.level.world+1}`,`${this.theme.name} · ${this.level.title}`,1700);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{clearUI();save.stats.playSeconds+=Math.floor((this.time.now-this.startedAt)/1000);persist(save);});
  }
  buildBackground(){const t=this.theme;this.cameras.main.setBackgroundColor(t.sky);const moon=this.add.circle(1020,130,70,t.moon,.88).setScrollFactor(.03).setDepth(-20);moon.setBlendMode(Phaser.BlendModes.ADD);const far=this.add.graphics().setScrollFactor(.08).setDepth(-18);far.fillStyle(t.far,1);for(let x=-300;x<1900;x+=190){const h=120+((x*7)%160+160)%160;far.fillTriangle(x,720,x+170,720,x+85,720-h);}const mid=this.add.graphics().setScrollFactor(.22).setDepth(-16);mid.fillStyle(t.mid,1);for(let x=-200;x<1800;x+=100){const h=80+((x*13)%120+120)%120;if(t.id==='bamboo'||t.id==='swamp'){mid.fillRect(x,720-h,12,h);mid.fillRect(x+12,720-h+20,48,5);}else{mid.fillTriangle(x,720,x+120,720,x+60,720-h);}}const haze=this.add.rectangle(640,600,1500,280,t.haze,.24).setScrollFactor(0).setDepth(-14);haze.setBlendMode(Phaser.BlendModes.ADD);this.weather=[];const count=save.settings.quality==='low'?26:save.settings.quality==='high'?80:48;for(let i=0;i<count;i++){const kind=t.weather;let obj;if(kind==='rain')obj=this.add.image(Phaser.Math.Between(0,1280),Phaser.Math.Between(0,720),'rain').setTint(0x8fb1c9).setAlpha(.28);else obj=this.add.image(Phaser.Math.Between(0,1280),Phaser.Math.Between(0,720),'particle').setTint(kind==='embers'?0xff7b42:kind==='leaves'?0x8f9b67:kind==='mist'?0xb7d8cf:0xaaa1b8).setAlpha(kind==='mist'?.1:.32).setScale(kind==='mist'?Phaser.Math.FloatBetween(2,5):Phaser.Math.FloatBetween(.35,1));obj.setScrollFactor(0).setDepth(30);obj.wv=Phaser.Math.FloatBetween(.35,1.4);obj.kind=kind;this.weather.push(obj);}}
  addPlatform(x,y,w,h=42,style=0){const color=style===1?0x101116:0x0a0b0e;const r=this.add.rectangle(x,y,w,h,color,1).setDepth(2);r.setStrokeStyle(1,0x262a31,.75);this.physics.add.existing(r,true);this.worldPlatforms.push(r);this.add.rectangle(x,y-h/2+2,w,4,this.theme.accent,.3).setDepth(3);return r;}
  addMovingPlatform(x,y,w,axis='x',range=130){const r=this.add.rectangle(x,y,w,28,0x111318,1).setDepth(3).setStrokeStyle(1,this.theme.accent,.65);this.physics.add.existing(r);r.body.setAllowGravity(false).setImmovable(true);r.startX=x;r.startY=y;r.axis=axis;r.range=range;r.speed=axis==='x'?65:48;r.dir=1;this.movingPlatforms.push(r);return r;}
  addSpikes(x,y,count=3){for(let i=0;i<count;i++){const s=this.physics.add.staticImage(x+i*22,y,'spike').setDepth(4);s.body.setSize(18,12).setOffset(3,6);this.hazards.push(s);}}
  addSaw(x,y,moving=false){const s=this.physics.add.image(x,y,'saw').setDepth(5).setAllowGravity(false).setImmovable(true);s.body.setCircle(17,7,7);s.moving=moving;s.anchorX=x;s.range=120;s.dir=1;s.body.setVelocityX(moving?85:0);this.hazards.push(s);return s;}
  addCoin(x,y){const c=this.coins.create(x,y,'coin').setDepth(7);c.body.setAllowGravity(false);c.baseY=y;c.phase=Math.random()*6;this.totalCoins++;return c;}
  addEnemy(type,x,y){const key={swordsman:'enemySword',archer:'enemyArcher',brute:'enemyBrute',mage:'enemyMage',assassin:'enemyAssassin',scout:'enemySword'}[type]||'enemySword';const e=this.physics.add.sprite(x,y,key).setDepth(7).setCollideWorldBounds(false);e.body.setSize(type==='brute'?50:38,type==='brute'?66:62).setOffset(type==='brute'?10:16,10);e.type=type;e.hp=type==='brute'?5:type==='assassin'?4:type==='mage'?3:2;e.maxHp=e.hp;e.damage=type==='brute'?2:1;e.speed=type==='assassin'?145:type==='brute'?65:type==='scout'?125:90;e.dir=Math.random()>.5?1:-1;e.homeX=x;e.range=Phaser.Math.Between(120,240);e.attackCd=Phaser.Math.Between(250,900)/1000;e.setFlipX(e.dir<0);this.enemies.push(e);return e;}
  buildLevel(){this.coins=this.physics.add.group({allowGravity:false});this.addPlatform(430,650,860,90);for(let x=140;x<820;x+=95)this.addCoin(x,560-(x%190===0?45:0));let x=850,platformIndex=0;const patterns=this.level.patterns;while(x<this.level.width-1050){x=this.buildPattern(patterns[platformIndex%patterns.length],x,650,platformIndex);platformIndex++;}const arenaX=this.level.width-520;this.addPlatform(arenaX,650,1040,90,1);for(let cx=this.level.width-960;cx<this.level.width-240;cx+=95)this.addCoin(cx,550);this.goal=this.physics.add.staticImage(this.level.width-150,550,'goal').setDepth(6);this.goal.body.setSize(55,80).setOffset(8,2);this.checkpointObj=this.physics.add.staticImage(Math.floor(this.level.width*.52),560,'checkpoint').setDepth(6);this.checkpointObj.body.setSize(50,60).setOffset(7,4);this.checkpointObj.activated=false;const sx=Math.floor(this.level.width*this.level.secretXRatio);this.secret=this.physics.add.staticImage(sx,350,'scroll').setDepth(7);this.secret.body.setSize(22,28);if(save.scrolls[this.level.id])this.secret.setVisible(false).disableBody(true,true);if(this.level.boss){this.bossGate=this.add.rectangle(this.level.width-1030,510,18,280,0x15171c,1).setDepth(8);this.physics.add.existing(this.bossGate,true);this.worldPlatforms.push(this.bossGate);}}
  buildPattern(pattern,x,baseY,i){const pool=this.theme.enemyPool;const enemyChance=.55+Math.min(.28,this.level.difficulty*.08);const spawnOn=(px,py,w)=>{for(let cx=px-w*.34;cx<px+w*.35;cx+=92)if(Math.random()>.42)this.addCoin(cx,py-72);if(Math.random()<enemyChance)this.pendingEnemies.push({type:pool[(i+Math.floor(px/200))%pool.length],x:px+Phaser.Math.Between(-Math.floor(w*.25),Math.floor(w*.25)),y:py-62});};if(pattern==='flat'){const w=450;this.addPlatform(x+w/2,baseY,w,70);spawnOn(x+w/2,baseY,w);if(i%3===1)this.addSpikes(x+220,baseY-53,3);x+=w;}else if(pattern==='gap'){this.addPlatform(x+110,baseY,220,70);spawnOn(x+110,baseY,220);this.addPlatform(x+410,baseY-45,210,70);spawnOn(x+410,baseY-45,210);this.addSpikes(x+235,baseY+8,4);x+=520;}else if(pattern==='stairsUp'){for(let k=0;k<4;k++){const y=baseY-k*52;this.addPlatform(x+70+k*145,y,135,42);if(k===2)spawnOn(x+70+k*145,y,135);this.addCoin(x+70+k*145,y-55);}x+=610;}else if(pattern==='stairsDown'){for(let k=0;k<4;k++){const y=baseY-160+k*48;this.addPlatform(x+70+k*145,y,135,42);if(k===1)spawnOn(x+70+k*145,y,135);this.addCoin(x+70+k*145,y-55);}x+=610;}else if(pattern==='pit'){this.addPlatform(x+110,baseY,220,70);spawnOn(x+110,baseY,220);this.addSpikes(x+235,baseY+10,6);this.addPlatform(x+480,baseY,250,70);spawnOn(x+480,baseY,250);x+=610;}else if(pattern==='roof'){this.addPlatform(x+210,baseY,420,70);this.addPlatform(x+225,baseY-185,230,35,1);spawnOn(x+225,baseY-185,230);for(let k=0;k<4;k++)this.addCoin(x+120+k*85,baseY-250);x+=450;}else if(pattern==='tower'){this.addPlatform(x+140,baseY,280,70);this.addPlatform(x+245,baseY-150,150,35);this.addPlatform(x+410,baseY-275,150,35);spawnOn(x+410,baseY-275,150);this.addCoin(x+410,baseY-335);x+=540;}else if(pattern==='zigzag'){for(let k=0;k<5;k++){const y=baseY-75-(k%2)*90;this.addPlatform(x+65+k*120,y,115,34);this.addCoin(x+65+k*120,y-52);}spawnOn(x+305,baseY-165,115);x+=620;}else if(pattern==='moving'){this.addPlatform(x+90,baseY,180,70);this.addMovingPlatform(x+310,baseY-90,120,i%2?'y':'x',90);this.addPlatform(x+520,baseY-20,190,70);spawnOn(x+520,baseY-20,190);this.addSpikes(x+190,baseY+8,4);x+=630;}if(i%4===2)this.addSaw(x-85,baseY-92,this.level.world>0);return x;}
  createPlayer(){for(const e of this.pendingEnemies)this.addEnemy(e.type,e.x,e.y);this.player=this.physics.add.sprite(180,510,'ninja').setDepth(12);this.player.body.setSize(34,64).setOffset(17,10);this.player.setCollideWorldBounds(false);this.player.setMaxVelocity(720,900);this.player.maxHp=5+save.upgrades.vitality;this.player.hp=this.player.maxHp;this.player.energy=100+save.upgrades.focus*20;this.player.maxEnergy=this.player.energy;this.player.damage=1+save.upgrades.blade;this.player.face=1;this.player.jumps=0;this.player.coyote=0;this.player.jumpBuffer=0;this.player.attackCd=0;this.player.combo=0;this.player.comboTimer=0;this.player.dashCd=0;this.player.dashing=0;this.player.invuln=0;this.player.dead=false;this.player.wallSide=0;}
  createGroupsAndCollisions(){for(const p of this.worldPlatforms)this.physics.add.collider(this.player,p);for(const m of this.movingPlatforms)this.physics.add.collider(this.player,m);for(const e of this.enemies){for(const p of this.worldPlatforms)this.physics.add.collider(e,p);for(const m of this.movingPlatforms)this.physics.add.collider(e,m);}this.physics.add.overlap(this.player,this.coins,(p,c)=>this.collectCoin(c));this.physics.add.overlap(this.player,this.secret,()=>this.collectScroll());this.physics.add.overlap(this.player,this.checkpointObj,()=>this.activateCheckpoint());this.physics.add.overlap(this.player,this.goal,()=>this.tryFinish());for(const h of this.hazards)this.physics.add.overlap(this.player,h,()=>this.hurtPlayer(1,h.x));this.playerShots=this.physics.add.group({allowGravity:false});this.enemyShots=this.physics.add.group({allowGravity:false});this.physics.add.overlap(this.player,this.enemyShots,(p,b)=>{b.destroy();this.hurtPlayer(b.damage||1,b.x);});this.physics.add.overlap(this.playerShots,this.enemies,(b,e)=>{if(!e.active)return;b.destroy();this.damageEnemy(e,b.damage||1);});}
  createHUD(){const root=mount(el(`<div class="ui-root"><div id="hud"><div class="hud-left"><div class="hud-row"><div class="hud-chip"><div class="hp-pips"></div></div><div class="hud-chip">◉ <b id="coinHud">0</b></div><div class="hud-chip"><div class="energy-bar"><i id="energyFill"></i></div></div></div><div class="hud-chip"><div class="hud-world">${this.theme.name}</div><div class="hud-level">${this.level.id}. ${this.level.title}</div></div></div><button class="pause-btn" id="pauseBtn">Ⅱ</button></div><div id="bossHud" style="display:none"><div class="boss-name"></div><div class="boss-bar"><i></i></div></div><div id="toast" class="toast"><b></b><span></span></div>${coarse?`<div id="controls"><div class="move-zone"><div class="move-pad"><button class="move-btn" id="leftBtn">‹</button><button class="move-btn" id="rightBtn">›</button></div></div><div class="action-zone"><button class="game-btn btn-range" id="rangeBtn">СЮРИКЕН</button><button class="game-btn btn-attack" id="attackBtn">УДАР</button><button class="game-btn btn-dash" id="dashBtn">РЫВОК</button><button class="game-btn btn-jump" id="jumpBtn">ПРЫЖОК</button></div></div>`:''}</div>`));this.uiRoot=root;this.hpPips=root.querySelector('.hp-pips');this.energyFill=root.querySelector('#energyFill');this.coinHud=root.querySelector('#coinHud');this.bossHud=root.querySelector('#bossHud');this.toast=root.querySelector('#toast');this.refreshHUD();bindClick(root,'#pauseBtn',()=>this.pauseGame());}
  createInputs(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('A,D,W,SPACE,SHIFT,E,F,Q');this.mobile={left:false,right:false,jump:false,attack:false,dash:false,range:false};if(coarse){const hold=(id,key)=>{const b=this.uiRoot.querySelector(id);const down=e=>{e.preventDefault();this.mobile[key]=true;b.setPointerCapture?.(e.pointerId);};const up=e=>{e?.preventDefault?.();this.mobile[key]=false;};b?.addEventListener('pointerdown',down);b?.addEventListener('pointerup',up);b?.addEventListener('pointercancel',up);};hold('#leftBtn','left');hold('#rightBtn','right');hold('#jumpBtn','jump');hold('#attackBtn','attack');hold('#dashBtn','dash');hold('#rangeBtn','range');}this.was={jump:false,attack:false,dash:false,range:false};}
  refreshHUD(){if(!this.hpPips)return;this.hpPips.innerHTML=Array.from({length:this.player.maxHp},(_,i)=>`<i class="heart ${i<this.player.hp?'on':''}"></i>`).join('');this.energyFill.style.width=`${clamp(this.player.energy/this.player.maxEnergy*100,0,100)}%`;this.coinHud.textContent=this.collected;}
  showToast(a,b='',ms=1200){if(!this.toast)return;this.toast.querySelector('b').textContent=a;this.toast.querySelector('span').textContent=b;this.toast.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.toast?.classList.remove('show'),ms);}
  pauseGame(){if(this.levelDone)return;this.physics.pause();this.scene.pause();const root=this.uiRoot;const modal=el(`<div class="modal-wrap"><div class="panel modal"><h2>Пауза</h2><p>${this.theme.name} · ${this.level.title}</p><div class="modal-row"><button class="btn ghost map">Карта</button><button class="btn settings">Настройки</button><button class="btn primary resume">Продолжить</button></div></div></div>`);root.append(modal);modal.querySelector('.resume').onclick=()=>{modal.remove();this.scene.resume();this.physics.resume();};modal.querySelector('.map').onclick=()=>{this.scene.stop();this.scene.start('Map');};modal.querySelector('.settings').onclick=()=>renderSettingsModal(root);}
  collectCoin(c){if(!c.active)return;c.disableBody(true,true);this.collected++;sfx.coin();this.refreshHUD();this.spawnBurst(c.x,c.y,0xf0c66a,5);}
  collectScroll(){if(!this.secret.active)return;this.secret.disableBody(true,true);save.scrolls[this.level.id]=true;persist(save);this.showToast('Свиток найден','Секрет уровня сохранён',1400);sfx.checkpoint();}
  activateCheckpoint(){if(this.checkpointObj.activated)return;this.checkpointObj.activated=true;this.checkpoint={x:this.checkpointObj.x,y:this.checkpointObj.y-65};this.checkpointObj.setTint(this.theme.accent);this.showToast('Точка тени','Возрождение сохранено',1100);sfx.checkpoint();}
  update(time,dtMs){const dt=Math.min(.034,dtMs/1000);if(!this.player||this.levelDone)return;this.updateWeather(dt);this.updateMoving(dt);this.updateCoins(time);this.updatePlayer(dt);this.updateEnemies(dt);this.updateShots(dt);this.updateBoss(dt);this.checkBossTrigger();if(this.player.y>820&&!this.player.dead)this.killPlayer();}
  updateWeather(dt){for(const p of this.weather){if(p.kind==='rain'){p.y+=520*dt*p.wv;p.x-=120*dt;}else if(p.kind==='embers'){p.y-=50*dt*p.wv;p.x+=Math.sin(p.y*.03)*18*dt;}else if(p.kind==='leaves'||p.kind==='ash'){p.y+=32*dt*p.wv;p.x+=Math.sin(p.y*.02+p.wv)*38*dt;p.rotation+=dt*p.wv;}else{p.x+=18*dt*p.wv;p.alpha=.06+.05*Math.sin(this.time.now*.001*p.wv);}if(p.y>740){p.y=-20;p.x=Phaser.Math.Between(0,1280);}if(p.y<-30){p.y=740;p.x=Phaser.Math.Between(0,1280);}if(p.x>1310)p.x=-20;if(p.x<-30)p.x=1310;}}
  updateMoving(dt){for(const m of this.movingPlatforms){if(m.axis==='x'){if(Math.abs(m.x-m.startX)>m.range)m.dir*=-1;m.body.setVelocityX(m.speed*m.dir);}else{if(Math.abs(m.y-m.startY)>m.range)m.dir*=-1;m.body.setVelocityY(m.speed*m.dir);}}for(const h of this.hazards){if(h.texture?.key==='saw'){h.rotation+=dt*5;if(h.moving&&Math.abs(h.x-h.anchorX)>h.range)h.body.setVelocityX(-h.body.velocity.x);}}}
  updateCoins(time){for(const c of this.coins.getChildren()){if(c.active){c.y=c.baseY+Math.sin(time*.004+c.x)*6;c.rotation+=.015;}}}
  updatePlayer(dt){const p=this.player;if(p.dead)return;p.invuln=Math.max(0,p.invuln-dt);p.attackCd=Math.max(0,p.attackCd-dt);p.comboTimer=Math.max(0,p.comboTimer-dt);p.dashCd=Math.max(0,p.dashCd-dt);p.energy=Math.min(p.maxEnergy,p.energy+18*dt);p.coyote=Math.max(0,p.coyote-dt);p.jumpBuffer=Math.max(0,p.jumpBuffer-dt);const left=this.cursors.left.isDown||this.keys.A.isDown||this.mobile.left,right=this.cursors.right.isDown||this.keys.D.isDown||this.mobile.right;const jump=this.cursors.up.isDown||this.keys.W.isDown||this.keys.SPACE.isDown||this.mobile.jump;const attack=this.keys.E.isDown||this.keys.F.isDown||this.mobile.attack;const dash=this.keys.SHIFT.isDown||this.mobile.dash;const range=this.keys.Q.isDown||this.mobile.range;const jumpPressed=jump&&!this.was.jump,attackPressed=attack&&!this.was.attack,dashPressed=dash&&!this.was.dash,rangePressed=range&&!this.was.range;this.was={jump,attack,dash,range};if(jumpPressed)p.jumpBuffer=.14;const dir=(right?1:0)-(left?1:0);if(dir)p.face=dir;p.setFlipX(p.face<0);const grounded=p.body.blocked.down||p.body.touching.down;if(grounded){p.coyote=.11;p.jumps=0;}p.wallSide=!grounded?(p.body.blocked.left?-1:p.body.blocked.right?1:0):0;if(p.wallSide&&p.body.velocity.y>110)p.body.setVelocityY(Math.min(p.body.velocity.y,120));if(p.dashing>0){p.dashing-=dt;p.body.setAllowGravity(false);p.body.setVelocityX(p.face*(690+save.upgrades.shadow*32));p.body.setVelocityY(0);if(p.dashing<=0)p.body.setAllowGravity(true);}else{p.body.setAllowGravity(true);const target=dir*310;const accel=grounded?1500:780;p.body.velocity.x=Phaser.Math.Linear(p.body.velocity.x,target,Math.min(1,accel*dt/Math.max(1,Math.abs(target-p.body.velocity.x))));if(!dir&&grounded)p.body.velocity.x*=Math.pow(.0005,dt);}if(p.jumpBuffer>0){if(p.wallSide){p.body.setVelocity(-p.wallSide*390,-555);p.face=-p.wallSide;p.jumpBuffer=0;sfx.jump();this.spawnBurst(p.x,p.y+24,0xdddddd,5);}else if(grounded||p.coyote>0||p.jumps<1){p.body.setVelocityY(p.jumps===0?-575:-535);if(!grounded&&p.coyote<=0)p.jumps=1;p.jumpBuffer=0;sfx.jump();this.spawnBurst(p.x,p.y+32,0x9aa0a8,5);}}if(dashPressed&&p.dashCd<=0&&p.energy>=18){p.energy-=18;p.dashing=.14;p.dashCd=Math.max(.38,.76-save.upgrades.shadow*.07);p.invuln=Math.max(p.invuln,.18);sfx.dash();this.afterImage();}if(attackPressed&&p.attackCd<=0)this.playerAttack();if(rangePressed&&p.energy>=22&&p.attackCd<=0)this.throwShuriken();p.alpha=p.invuln>0&&Math.floor(p.invuln*18)%2===0?.38:1;if(Math.abs(p.body.velocity.x)>20&&grounded)p.angle=Math.sin(this.time.now*.022)*2*p.face;else p.angle=Phaser.Math.Linear(p.angle,0,.18);if(p.dashing>0&&Math.random()>.45)this.afterImage();this.refreshHUD();}
  playerAttack(){const p=this.player;p.combo=p.comboTimer>0?(p.combo%3)+1:1;p.comboTimer=.42;p.attackCd=.17+(p.combo===3?.06:0);sfx.slash(p.combo);const reach=72+save.upgrades.blade*5;const cx=p.x+p.face*(48+save.upgrades.blade*3),cy=p.y+2;this.drawSlash(cx,cy,p.face,p.combo);let hit=false;for(const e of this.enemies){if(!e.active)continue;if(Math.abs(e.x-cx)<reach&&Math.abs(e.y-cy)<72){this.damageEnemy(e,p.damage+(p.combo===3?1:0));hit=true;}}if(this.boss?.active&&Math.abs(this.boss.x-cx)<reach+45&&Math.abs(this.boss.y-cy)<100){this.damageBoss(p.damage+(p.combo===3?1:0));hit=true;}if(hit){this.cameras.main.shake(55,.0022);this.time.timeScale=.72;this.time.delayedCall(45,()=>this.time.timeScale=1);}}
  throwShuriken(){const p=this.player;p.energy-=22;const b=this.playerShots.create(p.x+p.face*35,p.y-5,'shuriken').setDepth(11);b.body.setAllowGravity(false);b.body.setVelocityX(p.face*(520+save.upgrades.focus*18));b.life=1.5;b.damage=1+Math.floor(save.upgrades.focus/2);b.setFlipX(p.face<0);p.attackCd=.12;sfx.slash(1);}
  drawSlash(x,y,face,combo){const gr=this.add.graphics().setDepth(15);gr.lineStyle(4,combo===3?0xf0c66a:0xe8e2dc,.85);gr.beginPath();const start=face>0?-1.1:Math.PI+1.1,end=face>0?1.1:Math.PI-1.1;gr.arc(x,y,48+combo*5,start,end,face<0);gr.strokePath();this.tweens.add({targets:gr,alpha:0,scale:1.25,duration:130,onComplete:()=>gr.destroy()});}
  afterImage(){const im=this.add.image(this.player.x,this.player.y,'ninja').setDepth(10).setFlipX(this.player.flipX).setTint(this.theme.accent).setAlpha(.22);this.tweens.add({targets:im,alpha:0,duration:160,onComplete:()=>im.destroy()});}
  updateEnemies(dt){const p=this.player;for(const e of this.enemies){if(!e.active)continue;e.attackCd-=dt;const dx=p.x-e.x,dist=Math.abs(dx),sameY=Math.abs(p.y-e.y)<120;e.setFlipX(dx<0);if(e.type==='archer'){if(dist<430&&sameY){e.body.setVelocityX(dist<220?-Math.sign(dx)*80:0);if(e.attackCd<=0){this.enemyShoot(e,Math.sign(dx)*300,0,1);e.attackCd=1.35;}}else this.patrol(e);}else if(e.type==='mage'){e.body.setAllowGravity(false);e.body.setVelocityY(Math.sin(this.time.now*.003+e.homeX)*24);if(dist<480&&e.attackCd<=0){const ang=Phaser.Math.Angle.Between(e.x,e.y,p.x,p.y);this.enemyShoot(e,Math.cos(ang)*230,Math.sin(ang)*230,1);e.attackCd=1.1;}e.body.setVelocityX(dist>180&&dist<500?Math.sign(dx)*35:0);}else if(e.type==='assassin'){if(dist<360&&sameY){e.body.setVelocityX(Math.sign(dx)*e.speed);if(e.attackCd<=0&&dist<150){e.body.setVelocity(Math.sign(dx)*280,-360);e.attackCd=1.1;}}else this.patrol(e);}else{if(dist<330&&sameY){e.dir=Math.sign(dx)||1;e.body.setVelocityX(e.dir*e.speed);if(dist<52&&e.attackCd<=0){this.hurtPlayer(e.damage,e.x);e.attackCd=e.type==='brute'?1.2:.7;}}else this.patrol(e);}if(e.y>850)e.disableBody(true,true);}}
  patrol(e){if(Math.abs(e.x-e.homeX)>e.range)e.dir=-Math.sign(e.x-e.homeX);e.body.setVelocityX(e.dir*e.speed*.52);e.setFlipX(e.dir<0);if(e.body.blocked.left)e.dir=1;if(e.body.blocked.right)e.dir=-1;}
  enemyShoot(e,vx,vy,damage=1){const b=this.enemyShots.create(e.x,e.y-10,'enemyShot').setDepth(10);b.body.setAllowGravity(false);b.body.setVelocity(vx,vy);b.life=3;b.damage=damage;}
  updateShots(dt){for(const b of this.playerShots.getChildren()){if(!b.active)continue;b.rotation+=dt*12;b.life-=dt;if(b.life<=0)b.destroy();}for(const b of this.enemyShots.getChildren()){if(!b.active)continue;b.life-=dt;if(b.life<=0)b.destroy();}}
  damageEnemy(e,dmg){if(!e.active)return;e.hp-=dmg;e.setTintFill(0xffffff);this.time.delayedCall(55,()=>e.active&&e.clearTint());sfx.hit();this.spawnBurst(e.x,e.y,0xd9485f,7);if(e.hp<=0){save.stats.kills++;this.collected+=2+this.level.world;this.spawnBurst(e.x,e.y,0xeeeeee,12);e.disableBody(true,true);}}
  checkBossTrigger(){if(!this.level.boss||this.bossStarted||this.player.x<this.level.width-1250)return;this.bossStarted=true;const def=BOSSES[this.level.bossType];this.boss=this.physics.add.sprite(this.level.width-560,500,'enemyBrute').setScale(1.55).setTint(def.tint).setDepth(13);this.boss.body.setSize(54,70).setOffset(8,8);this.boss.hp=def.hp;this.boss.maxHp=def.hp;this.boss.def=def;this.boss.attackCd=.8;this.boss.phase=0;this.boss.invuln=0;for(const p of this.worldPlatforms)this.physics.add.collider(this.boss,p);this.bossHud.style.display='block';this.bossHud.querySelector('.boss-name').textContent=def.name;sfx.boss();this.showToast(def.name,'Хранитель печати',1500);}
  updateBoss(dt){const b=this.boss;if(!b?.active)return;b.attackCd-=dt;b.invuln=Math.max(0,b.invuln-dt);const p=this.player,dx=p.x-b.x,dist=Math.abs(dx),def=b.def;b.setFlipX(dx<0);const hpRatio=b.hp/b.maxHp,mult=hpRatio<.35?1.45:hpRatio<.65?1.2:1;if(def.behavior==='charge'){b.body.setVelocityX(Math.sign(dx)*def.speed*mult);if(b.attackCd<=0&&dist<260){b.body.setVelocityX(Math.sign(dx)*410);b.attackCd=1.4/mult;}}else if(def.behavior==='blade'){b.body.setVelocityX(dist>110?Math.sign(dx)*def.speed:0);if(b.attackCd<=0){if(dist<145){this.hurtPlayer(2,b.x);this.cameras.main.shake(130,.005);}else this.bossSpread(3,260,1);b.attackCd=1.1/mult;}}else if(def.behavior==='fire'){b.body.setVelocityX(dist>220?Math.sign(dx)*def.speed*.55:0);if(b.attackCd<=0){this.bossSpread(hpRatio<.5?7:5,220,1);b.attackCd=1.25/mult;}}else if(def.behavior==='teleport'){if(b.attackCd<=0){b.setPosition(clamp(p.x+Phaser.Math.Between(-260,260),this.level.width-930,this.level.width-160),430);b.body.setVelocityY(0);if(dist<180)this.hurtPlayer(2,b.x);else this.bossSpread(3,300,1);b.attackCd=.88/mult;}}else{b.body.setVelocityX(dist>170?Math.sign(dx)*def.speed*.78:0);if(b.attackCd<=0){if(Math.random()>.45)this.bossSpread(hpRatio<.5?9:5,270,hpRatio<.3?2:1);else b.body.setVelocity(Math.sign(dx)*390,-430);b.attackCd=.82/mult;}}if(dist<65&&Math.abs(p.y-b.y)<90&&b.attackCd<.25)this.hurtPlayer(def.damage,b.x);this.bossHud.querySelector('.boss-bar i').style.width=`${clamp(hpRatio*100,0,100)}%`;}
  bossSpread(count,speed,damage){const base=Phaser.Math.Angle.Between(this.boss.x,this.boss.y,this.player.x,this.player.y);for(let i=0;i<count;i++){const spread=count===1?0:Phaser.Math.Linear(-.65,.65,i/(count-1));const ang=base+spread;const b=this.enemyShots.create(this.boss.x,this.boss.y-35,'enemyShot').setScale(1.1).setTint(this.boss.def.tint).setDepth(11);b.body.setAllowGravity(false);b.body.setVelocity(Math.cos(ang)*speed,Math.sin(ang)*speed);b.life=3;b.damage=damage;}}
  damageBoss(dmg){const b=this.boss;if(!b?.active||b.invuln>0)return;b.hp-=dmg;b.invuln=.08;b.setTintFill(0xffffff);this.time.delayedCall(65,()=>b.active&&b.setTint(b.def.tint));this.spawnBurst(b.x,b.y,b.def.tint,10);sfx.hit();if(b.hp<=0){this.bossDefeated=true;save.stats.bosses++;this.spawnBurst(b.x,b.y,b.def.tint,28);b.disableBody(true,true);this.bossHud.style.display='none';if(this.bossGate)this.bossGate.destroy();this.showToast('Хранитель повержен','Путь к печати открыт',1600);sfx.win();}}
  hurtPlayer(amount,sourceX){const p=this.player;if(p.invuln>0||p.dead||this.levelDone)return;p.hp-=amount;p.invuln=.9;p.body.setVelocity((p.x<sourceX?-1:1)*260,-330);sfx.hurt();this.cameras.main.shake(120,.005);this.spawnBurst(p.x,p.y,0xd9485f,10);this.refreshHUD();if(p.hp<=0)this.killPlayer();}
  killPlayer(){const p=this.player;if(p.dead)return;p.dead=true;p.setVisible(false);p.body.enable=false;this.runDeaths++;save.stats.deaths++;this.showToast('Тень рассеялась','Возвращение к последней печати…',900);this.time.delayedCall(900,()=>this.respawn());}
  respawn(){const p=this.player;p.setPosition(this.checkpoint.x,this.checkpoint.y);p.body.enable=true;p.setVisible(true);p.hp=p.maxHp;p.energy=p.maxEnergy;p.invuln=1.1;p.dead=false;p.body.setVelocity(0,0);this.refreshHUD();}
  tryFinish(){if(this.levelDone)return;if(this.level.boss&&!this.bossDefeated){this.showToast('Печать закрыта','Сначала победи хранителя',900);return;}this.completeLevel();}
  completeLevel(){this.levelDone=true;this.physics.pause();sfx.win();const elapsed=(this.time.now-this.startedAt)/1000;const ratio=this.totalCoins?this.collected/this.totalCoins:1;const stars=1+(ratio>=.7?1:0)+(this.runDeaths===0?1:0);const old=save.levels[this.level.id]||{};const reward=35+this.level.world*15+this.level.stage*6+stars*12+(this.level.boss?70:0);save.coins+=reward;save.unlocked=Math.max(save.unlocked,Math.min(30,this.level.id+1));save.levels[this.level.id]={stars:Math.max(stars,old.stars||0),bestTime:old.bestTime?Math.min(old.bestTime,elapsed):elapsed,bestCoins:Math.max(old.bestCoins||0,this.collected)};persist(save);const root=mount(el(`<div class="ui-root screen"><div class="panel results"><div class="results-title">ПУТЬ ПРОЙДЕН</div><div class="results-stars">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><div class="result-stats"><div class="result-stat"><b>${this.collected}/${this.totalCoins}</b><span>монеты</span></div><div class="result-stat"><b>${formatTime(elapsed)}</b><span>время</span></div><div class="result-stat"><b>+${reward}</b><span>награда</span></div></div><div class="modal-row"><button class="btn ghost map">Карта</button><button class="btn replay">Повторить</button><button class="btn primary next">${this.level.id<30?'Дальше':'Финал'}</button></div></div></div>`));root.querySelector('.map').onclick=()=>this.scene.start('Map');root.querySelector('.replay').onclick=()=>this.scene.restart({levelId:this.level.id});root.querySelector('.next').onclick=()=>{if(this.level.id<30){const next=LEVELS[this.level.id];if(next.stage===0)this.scene.start('Map',{focus:next.id});else this.scene.start('Game',{levelId:next.id});}else this.scene.start('Menu');};}
  spawnBurst(x,y,color,count){for(let i=0;i<count;i++){const p=this.add.image(x,y,'particle').setTint(color).setDepth(20).setScale(Phaser.Math.FloatBetween(.6,1.7));const a=Phaser.Math.FloatBetween(0,Math.PI*2),d=Phaser.Math.Between(30,110);this.tweens.add({targets:p,x:x+Math.cos(a)*d,y:y+Math.sin(a)*d,alpha:0,scale:.1,duration:Phaser.Math.Between(180,420),ease:'Quad.easeOut',onComplete:()=>p.destroy()});}}
}

const config={type:Phaser.AUTO,parent:'game',backgroundColor:'#050609',width:1280,height:720,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH,width:1280,height:720},render:{antialias:save.settings.quality!=='low',pixelArt:false,roundPixels:false,powerPreference:'high-performance'},physics:{default:'arcade',arcade:{gravity:{x:0,y:1450},debug:false,fps:60}},input:{activePointers:4},scene:[BootScene,MenuScene,MapScene,GameScene]};
new Phaser.Game(config);
