(() => {
'use strict';
const debug=window.__UMK3_DEBUG__, DATA=window.UMK3_DATA;
if(!debug||!DATA)return;
const W=1280,H=720,FLOOR=594,FW=240,FH=320,COLS=8,TAU=Math.PI*2;
const game=debug.game,app=document.getElementById('app'),touch=document.getElementById('touch-ui');
if(!app)return;
const old=document.getElementById('raster-game');if(old)old.remove();
const canvas=document.createElement('canvas');canvas.id='raster-game';canvas.width=W;canvas.height=H;canvas.setAttribute('aria-hidden','true');
Object.assign(canvas.style,{position:'absolute',inset:'0',width:'100%',height:'100%',objectFit:'contain',pointerEvents:'none',background:'#030304'});
app.insertBefore(canvas,touch||null);const ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fighters=new Map(),stages=new Map(),fReady=new Map(),sReady=new Map();
function img(map,ready,key,src){if(map.has(key))return map.get(key);if(typeof Image==='undefined')return null;const im=new Image();ready.set(key,false);im.onload=()=>ready.set(key,true);im.onerror=()=>ready.set(key,false);im.src=src;map.set(key,im);return im}
function fighterImage(d){return d?img(fighters,fReady,d.id,`assets/fighters/${encodeURIComponent(d.id)}/atlas.png`):null}
function stageImage(s){return s?img(stages,sReady,s.id,`assets/stages/${encodeURIComponent(s.id)}.png`):null}
function text(s,x,y,size,align='center',fill='#fff',font='Impact'){ctx.save();ctx.font=`${size}px ${font},Arial,sans-serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillStyle=fill;ctx.shadowColor='rgba(0,0,0,.95)';ctx.shadowBlur=Math.max(4,size*.12);ctx.shadowOffsetY=3;ctx.fillText(String(s),x,y);ctx.restore()}
function rr(x,y,w,h,r,fill,stroke,lw=1){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function frameIndex(f,t){if(!f)return 0;if(f.state==='dizzy'||f.state==='hit'||f.state==='frozen'||f.stun>0)return 13;if(f.blocking||f.state==='block')return 14;if(f.attack){if(f.attack.kind==='special')return 12;const id=f.attack.id;if(id==='LP'||id==='jumpPunch')return 9;if(id==='HP'||id==='uppercut'||id==='grab')return 10;if(id==='LK'||id==='sweep')return 11;if(id==='HK'||id==='jumpKick')return 12}if(f.air)return f.vy<0?7:8;if(f.crouch)return 6;if(f.state==='run'||f.state==='walk'){const a=[3,4,5,4];return a[(t*(f.state==='run'?12:8)|0)%a.length]}if(f.finishPose>0||f.dead)return 15;const a=[0,1,2,1];return a[(t*5|0)%a.length]}
function drawFighter(f,t,mini=false){if(!f||f.invisible>50)return false;const d=f.activeData||f.data,im=fighterImage(d);if(!im||!fReady.get(d.id))return false;const idx=frameIndex(f,t),sx=(idx%COLS)*FW,sy=((idx/COLS)|0)*FH;const dw=d.style==='motaro'?225:(mini?196:202),dh=d.style==='motaro'?300:(mini?261:270);ctx.save();ctx.globalAlpha=f.invisible>0?.28:1;ctx.translate(f.x,f.y);ctx.scale(f.face||1,1);ctx.fillStyle='rgba(0,0,0,.5)';ctx.beginPath();ctx.ellipse(0,4,d.style==='motaro'?86:54,14,0,0,TAU);ctx.fill();ctx.drawImage(im,sx,sy,FW,FH,-dw/2,-dh+8,dw,dh);ctx.restore();return true}
function fake(d,x=0,y=0){return{x,y,face:1,data:d,activeData:d,state:'idle',stateT:game.clock,air:false,crouch:false,blocking:false,attack:null,invisible:0,stun:0,vx:0,vy:0,finishPose:0,dead:false}}
function drawStage(s){const im=stageImage(s);if(im&&sReady.get(s.id)){ctx.drawImage(im,0,0,W,H);return true}ctx.fillStyle=s&&s.sky?s.sky[0]:'#050506';ctx.fillRect(0,0,W,H);return false}
function healthBar(x,y,w,h,v,flip,color){rr(x,y,w,h,5,'#111216','#d4c59c',2);const q=clamp(v,0,1),ww=(w-8)*q;ctx.fillStyle=q<.25?'#c52828':'#c8b63a';if(flip)ctx.fillRect(x+w-4-ww,y+4,ww,h-8);else ctx.fillRect(x+4,y+4,ww,h-8);ctx.globalAlpha=.22;ctx.fillStyle=color;if(flip)ctx.fillRect(x+w-4-ww,y+4,ww,5);else ctx.fillRect(x+4,y+4,ww,5);ctx.globalAlpha=1}
function hud(){const p=game.player,e=game.enemy;if(!p||!e)return;const mh=f=>f.data.boss?(f.data.id==='shao-kahn'?135:120):100;text(p.data.name,58,35,25,'left','#f4ebd2');text(e.data.name,W-58,35,25,'right','#f4ebd2');healthBar(54,56,505,30,p.health/mh(p),false,p.data.primary);healthBar(W-559,56,505,30,e.health/mh(e),true,e.data.primary);text(Math.ceil(game.timer),W/2,58,43,'center','#f3e5be');if(game.intro>0)text(game.intro>1.15?`ROUND ${game.round}`:'FIGHT!',W/2,H*.42,game.intro>1.15?58:88,'center',game.intro>1.15?'#e7ddc1':'#dc3027');if(game.finishT>0&&!game.finisher){const l=game.winner===p?e:p;text(l.data.gender==='female'?'FINISH HER!':'FINISH HIM!',W/2,H*.32,80,'center','#da2d24')}if(game.paused){ctx.fillStyle='rgba(0,0,0,.78)';ctx.fillRect(0,0,W,H);text('ПАУЗА',W/2,180,64,'center','#e5d6ae');text('ESC / Ⅱ — продолжить',W/2,285,24,'center','#f2cd67','Arial')}}
function title(){drawStage(DATA.stages[12]);ctx.fillStyle='rgba(0,0,0,.43)';ctx.fillRect(0,0,W,H);text('ULTIMATE',W/2,392,48,'center','#e3d5ae');text('MORTAL KOMBAT 3',W/2,455,72,'center','#dc342b');text('RASTER REMASTER',W/2,520,32,'center','#d8c59b');text('НАЖМИ ENTER / КОСНИСЬ ЭКРАНА',W/2,620,22,'center','#f4e8c9','Arial');text(`v${DATA.version} • OFFLINE`,W/2,674,15,'center','#9b9da2','Arial')}
function select(){ctx.fillStyle='#070709';ctx.fillRect(0,0,W,H);text('CHOOSE YOUR FIGHTER',W/2,48,43,'center','#e0d2aa');const list=DATA.allPlayable,cols=7,cw=132,ch=122,sx=(W-cols*cw)/2,sy=90;for(let i=0;i<list.length;i++){const d=list[i],x=sx+(i%cols)*cw,y=sy+((i/cols)|0)*ch,sel=i===game.select;rr(x+5,y+5,cw-10,ch-10,7,sel?'#44291a':'#111216',sel?'#edbd52':'#41434a',sel?4:2);const f=fake(d,x+cw/2,y+96);ctx.save();ctx.translate(f.x,f.y);ctx.scale(.38,.38);f.x=0;f.y=0;drawFighter(f,game.clock,true);ctx.restore();text(d.name,x+cw/2,y+104,13,'center',sel?'#ffe29a':'#ddd','Arial')}const d=list[game.select]||list[0];text(d.name,W/2,620,37,'center',d.primary);text('ENTER — выбрать • ←↑↓→ — персонаж',W/2,674,18,'center','#bdc0c4','Arial')}
function tower(){drawStage(DATA.stages[9]);ctx.fillStyle='rgba(0,0,0,.68)';ctx.fillRect(0,0,W,H);text('KOMBAT TOWER',W/2,55,49,'center','#e6d8b2');const n=game.tower.length;for(let i=0;i<n;i++){const idx=n-1-i,d=game.tower[idx],y=116+i*50,a=idx===game.towerStep;rr(W/2-220,y-21,440,42,6,a?'#4d281a':'rgba(17,17,20,.88)',a?'#e7b34b':'#44464c',a?3:1);text(`${idx+1}. ${d.name}`,W/2,y,20,'center',a?'#ffdc88':'#d0d2d5','Arial')}text('ENTER — следующий бой',W/2,686,17,'center','#ddd','Arial')}
function fight(){drawStage(DATA.stages[game.stageIndex]||DATA.stages[0]);drawFighter(game.player,game.clock);drawFighter(game.enemy,game.clock);hud();if(game.outro>0&&game.winner)text(`${game.winner.data.name} WINS`,W/2,225,51,'center','#e2d3ab')}
function simple(label,stage=6){drawStage(DATA.stages[stage]);ctx.fillStyle='rgba(0,0,0,.68)';ctx.fillRect(0,0,W,H);text(label,W/2,300,62,'center','#d32e27');text('ENTER',W/2,400,24,'center','#ead9ae')}
let switched=false;function render(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,W,H);if(game.state==='title')title();else if(game.state==='select')select();else if(game.state==='tower')tower();else if(game.state==='fight')fight();else if(game.state==='ending')simple('EARTHREALM IS FREE',15);else if(game.state==='gameover')simple('YOU HAVE BEEN DEFEATED',6);else{ctx.fillStyle='#050506';ctx.fillRect(0,0,W,H)}if(!switched){const base=document.getElementById('hd-game');if(base)base.style.opacity='0';switched=true}requestAnimationFrame(render)}
for(const d of DATA.allPlayable)fighterImage(d);for(const s of DATA.stages)stageImage(s);requestAnimationFrame(render);
window.__UMK3_RASTER__={canvas,fighters,stages,fReady,sReady,drawFighter,drawStage};
})();
